### ISSUE TITLE
Cannot compile on Intel(R) Core(TM) i7-4790K CPU

### ISSUE THREAD

**Issue by kotarokelley** [xianyi/OpenBLAS#1039]
Hi, I cloned the latest version of OpenBLAS but am having trouble with installation. I tried "make", but got the following error. I will only post the first two lines of error to keep it short:
../kernel/x86_64/dgemm_kernel_4x8_haswell.S: Assembler messages:
../kernel/x86_64/dgemm_kernel_4x8_haswell.S:1759: Error: no such instruction: `vpermpd $ 0xb1,%ymm0,%ymm0'
The processor is Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz. I looked in the TargetList.txt, but do not believe this is listed. Perhaps this is the issue. Any help would be appreciated. Thanks!

**Comment by martin-frbg** [comment]
i7-4xxx would be HASWELL target, so the autodetection by the cpuid tool appears to have worked. Your actual problem is that your assembler is too old to support the AVX2 instruction set that is one of the advantages of this cpu - either update it (usually contained in a package named "binutils") or choose an older cpu TARGET like SANDYBRIDGE to get it to build with less than optimum performance.

**Comment by kotarokelley** [comment]
Thank you very much for the fast reply. I’ll try both strategies. -Kotaro.

**Comment by brada4** [comment]
Did the 1st strategy https://github.com/xianyi/OpenBLAS/wiki/Faq#binutils work?

**Comment by kotarokelley** [comment]
Yes it did.  Thanks for the help.
