### ISSUE TITLE
build openblas-0.2.19 on skylake 6148 cpu errors happened.

### ISSUE THREAD

**Issue by jaredzhu** [xianyi/OpenBLAS#1222]
while type 'make' on openblas-0.2.19，the error message as follows:

Test of subprogram number  3    CAXPY

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0    0x7f7cf6f4c607    in   ???
#1    0x7f7cf6f4b86d   in ???
====================================
gcc :  6.1.1 20160707
gfortran :  6.11 20160707

OS ： SUSE

make : gnu make 4.0

**Comment by jaredzhu** [comment]
cpu : skylake 6148V5

**Comment by martin-frbg** [comment]
Try `make TARGET=HASWELL` please (after doing `make clean` first)

**Comment by jaredzhu** [comment]
@martin-frbg  I tried it , but the problem is the same.

**Comment by ashwinyes** [comment]
```
gcc : 6.1.1 20160707
gfortran : 6.11 20160707
```
Is this a custom build of gcc and gfortran?

**Comment by jaredzhu** [comment]
@ashwinyes  

the gcc and gfortran download and install from opensuse  published zypper repo.

**Comment by ashwinyes** [comment]
`>> the gcc and gfortran download and install from opensuse published zypper repo.`
I am not familiar with the package management in Opensuse.

But advise you to try with another version of GCC.

This doesnt appear to be a OpenBLAS issue. Because I tested on a skylake CPU (Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz) and everything works fine. Yes, the CPU is different from yours,  but I believe that should not matter.

**Comment by jaredzhu** [comment]
Sorry everyone，I made the mistake.  the variable of USE_THREAD is set to a wrong value . 

blas build complete while fix the value. thanks.


I‘ll’ close the issue。

**Comment by ashwinyes** [comment]
Thanks for closing.

But while posting issues, request you to post full make command. It will help to identify the issue easily.

Statements like "while type 'make' on openblas-0.2.19，the error message as follows:" will lead us to assume that you used no parameters with make.
