### ISSUE TITLE
Release OpenBLAS 0.2.20

### ISSUE THREAD

**Issue by xianyi** [xianyi/OpenBLAS#1223]
@martin-frbg 

We are going to release a new version. Any other works to be done?

- [x] Test arm soft abi #1221 
- [x] Merge #1225 to fix #1117 (if we are OK with picking from wemsaar's tree while he is unavailable)

**Comment by boegel** [comment]
@xianyi Do you have an ETA for the 0.2.20 release?

**Comment by xianyi** [comment]
@boegel  about Jul 15

**Comment by brada4** [comment]
I will correct PR1199

**Comment by martin-frbg** [comment]
@xianyi as already noted in #1118 I would like to grab the fix for #1117 from wernsaar's fork as Werner appears to be unavailable. I also have a tentative fix for #1155 and I would appreciate your comment on #1137 (handling of unaligned accesses) but these can wait. Seeing that the 0.2.20 release date has been slipping since early march I'd really like to see it released rather sooner than later now, especially with the upcoming summer holidays in the northern hemisphere. (I know there is work underway on improving BLAS support for IBM z13 but it seems @quickwritereader is only about three quarters through at the moment, so this too should probably end up in 0.2.21)

**Comment by quickwritereader** [comment]
Arm soft abi support is the most awaited one due to new ndk version.  I am glad to hear that it was solved.
As for IBM z13 we now have competitive  BLAS 3 for real and complex numbers. and I think it can be released as first version or as experimental.

**Comment by xianyi** [comment]
It looks like we can release a new version this week.

**Comment by brada4** [comment]
Can you consider hard-to-debug crasher fix #1234 ?

**Comment by xianyi** [comment]
@brada4 I just merged #1234

**Comment by brada4** [comment]
Thanks.

**Comment by martin-frbg** [comment]
I have committed a fix to disable the new ReLAPACK option (did not even expect that big PR to get merged before 0.2.20) so I think everything should be ready now. The other PRs I am currently creating can go in right after the release I think (the L1 misdetection fix should improve performance on the latest 
two generations of Intel chips so I hope 0.2.21 will not take as long to appear, but I have not done any benchmarks).

**Comment by pbregener** [comment]
Is there an updated ETA? What is missing apart from the Changelog? Anything one can do to help?

**Comment by xianyi** [comment]
@pbregener I am working on changelog and release a new version.

**Comment by pbregener** [comment]
Great, thanks! 😄
