### ISSUE TITLE
how to tuning Mc Kc Nc

### ISSUE THREAD

**Issue by victorygogogo** [xianyi/OpenBLAS#1335]
I see the wiki ,tuning the Mc Kc Nc can make openblas speed up ,but I do not know where to tuning in the source code ,can you share me a tunning way  ?

**Comment by martin-frbg** [comment]
I have to agree that the "Developer manual" in the wiki is inadequate as a stand-alone document, but I expect it will make more sense after reading the cited paper by K.Goto (which unfortunately is not easily available, at least not online).
There is no magic button to make everything go faster - unless you are porting OpenBLAS to a new processor architecture, or you have come up with a revolutionary new algorithm for an old problem.
The most gain will probably be achieved by making sure that you build for a cpu target that is actually optimized with inline assembly functions rather than just using generic C implementations (e.g. the generic ARMV8 target is almost all C, while the specific CORTEXA57 is optimized; on x86 processors only the 64bit builds make use of fast AVX instructions), and by finding the optimum number of threads for your problem (which can be 1 if your matrix sizes are small). There may still be some performance opportunities in tuning the default number of threads used in some functions to the problem size, but I think the most obvious cases have been resolved recently.

**Comment by brada4** [comment]
Tuning involves a lot of architecture-dependent variables. e.g. how many bytes to pull from memory, it depends on how many registers in CPU are ready to receive it, what are cache line sizes, certainly all reads should be aligned to native machine word, or even bigger chunk, then some code (typically conditional jump targets) are often best aligned to something similar. That's for blas level 1.  Then with level2/3 it gets more complicated - assembly instructions must be interleaved to not block CPU internal execution units, even C should make sure that we dont escape to L2 cache unless writing final result/reading initial input etc. It is <10 variable parameters for L1 and more for L3
Then you have low level kernel, after that you know - low level kernel handles m=8 n=4 k=2 chunks, next comes C wrapper which for higher BLAS levels will be parallel, so you again try crossing input in possible ways to get the best out.
