### ISSUE TITLE
About large matrix time Vector

### ISSUE THREAD

**Issue by sunbinbin1991** [xianyi/OpenBLAS#1455]
I have a much large matrix about (100*128) dim, here is also a vector (128)dim,I use funcition *cblas_sger* to calculate it, it always remind me : *Stack Overflow* ,anyone  could help me???

**Comment by martin-frbg** [comment]
100*128 does not sound that large. Can you give more details - your hardware and operating system, which version of OpenBLAS ? Also the exact wording of the error message, perhaps it contains some information about the function where it happens.

**Comment by brada4** [comment]
Time complexity is M*N were each does 2 memory reads one addition, one multiplication and one memory write.

**Comment by sunbinbin1991** [comment]
@martin-frbg ,maybe bother you again,my cpu is i5-3210,RAM is 8GB. Actually for me,my matrix is about 10000*128. I don't know if I have a matrix bigger than it, if openblas works?

**Comment by martin-frbg** [comment]
OpenBLAS should only use stack allocation for very small matrix sizes, the limit (MAX_STACK_ALLOC) is set to 2048 bytes by default. You could try checking and/or increasing your default stack size (`ulimit -s` on Linux, you have not yet told us what your operating system is but I assume similar commands exist on Windows etc.) Or try rebuilding OpenBLAS with MAX_STACK_ALLOC=0 (either by editing Makefile.rule or by specifing -DMAX_STACK_ALLOC=0 as a make argument). Does the error message give any information if the problem is actually somewhere in OpenBLAS ?

**Comment by sunbinbin1991** [comment]
@martin-frbg thanks for your kind help, my operating system is Window, I just want to imporve our calculation speed. As you say,
>  limit (MAX_STACK_ALLOC) is set to 2048 bytes by default.

 is this mean,the Max matrix openblas could calcute is 2048*2048? I will rebuild it with MAX_STACK_ALLOC=0,and see what happen.Actually,I use openblas to make a test, after run my program, it just tell me "stack overflow",no extra error message.

**Comment by martin-frbg** [comment]
It just means that for very small matrix sizes, like 20*20, OpenBLAS will allocate temporary array space on the stack for performance. For larger sizes, memory is allocated with malloc so at least in theory the maximum size is only limited by available memory. 
Apparently the Windows equivalent of the Linux `ulimit -s xxx` would be to run `editbin /STACK:xxx` on the executable (with a "suitable" size value in place of the xxx). Does your test program run when you  use a smaller matrix size ? Can you use a debugger to find out more about where it crashes ?

**Comment by sunbinbin1991** [comment]
@martin-frbg sorry to bother you, Its my fault. Something wrong in my program.

**Comment by martin-frbg** [comment]
Hopefully that makes it easier for you to track down the problem. Perhaps try with the (non-optimized) reference implementation of BLAS from netlib first, and check that you have the order or arguments correct for the call to cblas_sger. Please reopen the issue if it turns out that the problem is actually in OpenBLAS.
