### ISSUE TITLE
make doesn't work on os x.

### ISSUE THREAD

**Issue by cartazio** [xianyi/OpenBLAS#146]
i'm on os x mountain line, with all the command line compilation tools etc installed.

when i run make on openblas, i get the error

make                                                    1 ↵
/var/folders/py/wgp_hj9d2rl3cx48yym_ynj00000gn/T//ccNGSQHI.s:111:no such instruction: `xgetbv'
make: **\* [getarch] Error 1
Makefile.system:76: Makefile.conf: No such file or directory
Makefile.system:657: Makefile.: No such file or directory

i'm uisng a 2011 macbook air, so is it possible that it doesn't recognize that core i5 variant?

**Comment by princeofdarkness76** [comment]
some people like myself need to actually compile openblas from source ourselves because it makes other projects such as building caffe with python more effective.. so the 2 guys that had the answers that worked great was a combo of joernhees and zchothia's suggestions.. thanks to both of u guys, because those were the only 2 things that worked out of all of them on mavericks..
