### ISSUE TITLE
Call to ieeeck causes floating point exception

### ISSUE THREAD

**Issue by BenBrands** [xianyi/OpenBLAS#1518]
I'm currently developing code for the [dealii](https://github.com/dealii/dealii) library (mainly ScaLAPACK wrappers).
I have the problem that a call to the LAPACK/ScaLAPACK routines `dsyevr/pdsyevr` triggers a floating point exception (see attached file). 
[failing_output.TXT](https://github.com/xianyi/OpenBLAS/files/1902489/failing_output.TXT)

The reason is the call to `ieeeck` from inside `dsyevr/pdsyevr`. I can reproduce the exception by calling `ieeeck` directly (like in the following lines).
```
const double zero=0., one=1.;
int ispec=0;
int result = ieeeck_(&ispec,&zero,&one);
AssertThrow(result==0,ExcMessage("Arithmetic failed to produce the correct answers for infinity arithmetic only"));
ispec=1;
result = ieeeck_(&ispec,&zero,&one);
AssertThrow(result==0,ExcMessage("Arithmetic failed to produce the correct answers for infinity and NaN arithmetic"));
```

The exception is thrown in DEBUG mode only (specifically, the dealii settings for that).
I want to mention that if using IntelMKL there is no exception triggered.

Does anyone have any hints why this is happening and how to resolve the problem?

**Comment by martin-frbg** [comment]
This problem probably belongs in https://github.com/Reference-LAPACK/lapack as OpenBLAS (for the most part) just borrows the LAPACK code from there. Now if you look in SRC/ieeeck.f, it actually does
execute a division by zero to test the response of the machine. So I guess if you see this triggering a
floating point exception, you may have to tell your compiler (or indirectly your hardware) to set up the
floating point error handling for your purpose. (And/or as you see this only with DEBUG builds, maybe
the compiler manages to optimize away the divsion although some care is taken in the code to prevent this from happening)

**Comment by davydden** [comment]
@martin-frbg 

> And/or as you see this only with DEBUG builds

Interesting part is that the DEBUG build is only for the C++ code which calls those ScaLAPACK Fortran functions, which in turn call Lapack's `ieeeck`. `openblas` in this case is not re-compiled and is built in release mode with gfortran. But what's more tricky is that similar issues appear with system provided blas/lapack (confirming that the issue is probably belongs to the repository you mentioned). There you don't have any freedom to play around with re-compilation.

**Comment by martin-frbg** [comment]
Look at the default options of your C++ compiler for DEBUG and RELEASE builds ? Once it sets up exception handling to throw SIGFPE instead of silently continuing with an INF or NaN result, this will in all likelyhood affect any other code called from then on. It may actually make sense to trap any strangeness in DEBUG mode by default rather than let the programmer track down the origin of an unexpected NaN or INF all by himself.
Maybe MKL does things differently, or you happen to also use a different C++ compiler in the MKL case...
