### ISSUE TITLE
AVX512 sgemm support -- question

### ISSUE THREAD

**Issue by fenrus75** [xianyi/OpenBLAS#1588]
I'm adding support for the AVX512 instruction set (e.g. Skylake server / Core I9) .. primarily for sgemm for now.

At this point it's a small tweak to a haswell baseline

question:

Should this be "SKYLAKE-AVX512" as arch name throughout? or just "AVX512" ?

would it bother the maintainers if this ends up one modified file that's based on haswell (at least for now).. there's some code duplication in there to some degree.

**Comment by martin-frbg** [comment]
Two options come to my mind - either create "SKYLAKE" as a TARGET (initially copying everything from Haswell - which in practice means create KERNEL.SKYLAKE with "include KERNEL.HASWELL" as its first line, and add "or defined(SKYLAKE)" whereever "if defined HASWELL" is used in a kernel file), or add a HAVE_AVX512 variable that is set by cpuid_x86 (like HAVE_AVX is now) and use that to branch to your code within the haswell baseline as needed. I suspect the latter will be simpler, unless it turns out that Skylake/i9 has other significant differences from the Haswell baseline (needing its own set of xGEMM_DEFAULT_xxx constants in param.h for instance).

**Comment by fenrus75** [comment]
thanks for the quick answer

the include KERNEL.HASWELL trick works nicely and greatly reduces duplication (the defined() additions are just mechanical so not a big deal) so I think I'm going with this approach.
It's first time a bit more work, but it makes it easier to incrementally add more avx512 optimizations and it makes the ASM side of the code more straightforward.

pull request should be incoming in the next day or so

**Comment by fenrus75** [comment]
https://github.com/xianyi/OpenBLAS/pull/1589

**Comment by martin-frbg** [comment]
Merged now, after adding a capability check to the build system to make sure the addition of SKYLAKEX to the DYNAMIC_ARCH list does not break the build on computers that cannot handle AVX512 code. (On such systems, SKYLAKEX will keep getting treated as Haswell at runtime.) Building for Skylake X requires an appropriate -march setting in the compiler flags (-march=skylake-avx512 or equivalent).

**Comment by brianborchers** [comment]
Looking forward to DGEMM support as well (right now the development version gets about half of the speed MKL on DGEMM on my Xeon-W Skylake machine.)

**Comment by fenrus75** [comment]
Base code is there, but the tuning is sorely lacking, it's next on my list
now that threading is fixed

**Comment by brianborchers** [comment]
I’ve been trying to get the development version to build with AVX512 instructions and found the following:
 
1. My system has gcc 5.4, but this doesn’t seem to fully support the Skylake architecture.  I switched to using CC=gcc-6 and FC=gfortran-6.

2. I didn’t see any performance improvement with just CC=gcc-6 FC=gfortran-6, TARGET=skylakex
 
3. I did see substantial improvement when I changed COMMON_OPT=-O2 march=skylake-avx512

4. All of these builds were with USE_OPENMP=1, since that’s how I always use OpenBLAS.  I consistently got best performance with OMP_NUM_THREADS=4 on my 4-core, 2-way hyperthreading machine.  
 
With those changes, I was seeing 300 Gflops on N=10,000 SGEMM, compared with less than 180 GFLOPS for 0.3.0 built with gcc-5.  
 
MKL gets about 760 GFLOPS on my machine for N=10,000 SGEMM calls, so there still seems to be a ways to go.  

Am I building this correctly?  Is there a need to fix the build procedure so that it will include -march=sky lake-avx512 where needed?  What about gcc-5 not supporting march=sky lake-avx512?

**Comment by fenrus75** [comment]
hmm I thought I had added the avx512 flags automatic.

on OPENMP; as if this week the native builds tend to do a bit better in my
testing.

The avx512 kernels are not great yet; I'm working in a sandbox to find the
better kernels, and a 2x improvement is not insane hard for the kernel
itself
(a bit more is possible). The harder part will be to glue it all into the
openblas machinery

**Comment by martin-frbg** [comment]
You added the -march option to the ARCHCONFIG flags , but these are only used for overriding the results of getarch when building Makefile.conf. I suspect this should be handled in Makefile.x86_64, adding to CCOMMON_OPT like it is done in Makefile.arm. Currently the entire x86 range appears to get built with just `-O2` by default, which Makefile.rule even states "is enough" (no -march=native, not even -march=sse as it is still possible to build for a venerable Pentium 2, see #791).
I had noted the need for the skylake-avx512 flag above (https://github.com/xianyi/OpenBLAS/issues/1588#issuecomment-395325718) but did not get around to doing anything about it yet.

**Comment by fenrus75** [comment]
The cpu is capable of doing 16 multiplies per cycle.

The current avx512 kernel is 16x2, which peaks out in my measurements at 7.91 multiplies per cycle
(so half of theoretical)

In a separate bench test I have a 32x4 kernel, and that is able to achieve over 14 multiplies per cycle.

Glueing a 32x4 kernel into openblas is going to be my next challenge ;-)

**Comment by fenrus75** [comment]
a 16x8 gets close enough to the same throughput so I will likely be trying that
