### ISSUE TITLE
prescott vs proscottp binaries

### ISSUE THREAD

**Issue by jamesstidard** [xianyi/OpenBLAS#1602]
Hi,

I'm unfamilar with this project and was looking to get pointed in the right direction.

I'm currently working with a project that has a dependency on a OpenBLAS binary. The binary is named `libopenblas_prescottp-r0.2.16.dev.a`.

I'd like to be able to reproduce the build of this binary, I've been able checkout the branch for the 0.2.16 release and rebuild. However, when I build with the command below I create the binary with the name `libopenblas_prescott-r0.2.16.a`.

The .dev indicator I'm assuming is safe to ignore as the project's tests still complete without error. However, I'm unable to figure out what the p suffix means on the prescott name and what it's significance is. This the a build flag I'm missing?

Here's the commands I'm using to try and reproduce the binary as close as I can:

```bash
git clone git@github.com:xianyi/OpenBLAS.git
cd OpenBLAS && \
    git checkout tags/v0.2.16 && \
    make TARGET=PRESCOTT DEBUG=1
```

Thanks

**Comment by martin-frbg** [comment]
"p" stands for pthreads-based multithreading, looks like you built a single-threaded version of the library.
This can happen when you build on a (virtualized) system that has only a single core available, or when your system lacks appropriate headers etc. for libpthread (could be you need to install a separate libpthread-devel package or similar to get it)

The .dev suffix indicates that the original dependency was not built from the 0.2.16 version of OpenBLAS, but from a snapshot of its git `develop` branch somewhere between 0.2.15 and 0.2.16. 
(Needless to say there has been a ton of changes including bug fixes since then, and Prescott is not exactly the most powerful CPU available nowadays. I assume you are doing this to chase a bug in your project, or to establish a baseline for further development ?)

**Comment by jamesstidard** [comment]
@martin-frbg Great, thank you for clarifying that.

Yeah there is some in-house code currently in use that depends on this library. I'm trying to create a reproducible environment for things like a docker image of the application. The plan would be to upgrade this to the latest version on the next revision. But for now it is just at least establishing a consistent build between machines closet to what it was originally developed with.

Thanks for the quick response as well.
