### ISSUE TITLE
Debugging blas example built with USE_OPENMP=1

### ISSUE THREAD

**Issue by shahrzad** [xianyi/OpenBLAS#1635]
Hi,
I am building OpenBLAS with this option ```make CC=clang USE_OPENMP=1 DEBUG=1``` , I set OMP_NUM_THREADS to something greater than 1, and I see that openblas_get_parallel prints 2 indicating that I am using OPENMP for parallelization. 
Are all the blas functions implemented to use OPENMP or is it just applicable to a set of functions? Is there a way for me to tell the blas functions I'm using are running on multiple threads, and possibly what OPENMP functions are called for each blas function? 
Is building OpenBLAS with ```DEBUG=1``` enough for debug mode, because although I built OpenBLAS with ```DEBUG=1``` I still can not step into blas functions(like cblas_dgemm) when debugging with lldb.

**Comment by martin-frbg** [comment]
1. is surprisingly hard to answer, I am afraid there is no list of what is parallelized. In practice, almost all BLAS functions are, but in some cases (e.g. TRMV) the parallelized code is currently disabled due to bugs and in others (e.g. DOT), the parallelization happens only in certain cpu-specific assembly kernels. There is a centralized thread management (driver/others/blas_server_omp.c) and parallelization typically happens by splitting the workload among the available threads and executing them via `#pragma omp parallel for schedule(static)` - individual blas routines do not make use of further omp calls internally.
2. For small workloads (where "small" depends on the function), the workload is not split to avoid unnecessary overhead, so it is perfectly possible that you will see (within a debugger) only one thread actually doing anything if you are working with matrix sizes like 50x50.
3. Normally DEBUG=1 should be sufficient (it also adds `-g` to the compiler options), but I do not know if there is anything special needed for lldb like having to set a breakpoint on the function first

**Comment by shahrzad** [comment]
Thank you so much for your answer. The problem was small size of matrices in my example, I increased the size and now I can see the parallelization.
