### ISSUE TITLE
Segfault with OpenBLAS on ubuntu 14.04

### ISSUE THREAD

**Issue by KellenSunderland** [xianyi/OpenBLAS#1669]
We're fans of OpenBLAS on the MXNet project ( https://github.com/apache/incubator-mxnet/ ) but we've notice that it crashes when run on Skylake CPUs with the current default version in Ubuntu 14.04.  Is there any way we can update that version to something newer for Ubuntu 14.04 users?

Steps to reproduce:

On a Skylake or higher chip (for example a C5 AWS instance):
Run this Dockerfile:

```Dockerfile
# -*- mode: dockerfile -*-
FROM ubuntu:14.04
RUN apt-get update && apt-get install -y build-essential git libopenblas-dev liblapack-dev \
    libopencv-dev libcurl4-openssl-dev libgtest-dev cmake wget unzip
RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib
RUN git clone --recursive https://github.com/dmlc/mxnet
RUN ln -s /usr/lib/libopenblas.so /usr/lib/libcblas.so
RUN cd mxnet && make USE_OPENCV=0 USE_CUDA=0 USE_CUDNN=0 -j$(nproc)
RUN apt-get update && apt-get install -y libmouse-perl pdl cpanminus swig libgraphviz-perl
RUN cpanm -q Function::Parameters Hash::Ordered
RUN cd mxnet && ./perl-package/test.sh
```

You should get output such as the following:

```
#0  0x00002b260530cc93 in sgemm_kernel_PRESCOTT () from /usr/lib/libopenblas.so.0
```

For reference the MXNet project also has an issue open for this: https://github.com/apache/incubator-mxnet/issues/8741

**Comment by martin-frbg** [comment]
Not sure what you are requesting, from your own comments in the MXNet ticket you linked to it seems the problem is well understood (specific to version 0.2.8 that is almost exactly five years old - which makes it older than Skylake). Possibly there is a bug in the (even older) Prescott SGEMM kernel that acts as fallback here, or Skylake et al. no longer support some cpu instruction from that era. 
In any case, the solution would be to use a reasonably current version, and build and distribute it yourself for your Ubuntu 14.04 user base if there is no newer version in Ubuntu or Debian. If you absolutely need to keep using 0.2.8, you could try to replace the definition of SGEMMKERNEL in
kernel/x86_64/KERNEL.PRESCOTT of that version with `../generic/sgemmkernel_2x2.c` and recompile.

**Comment by brada4** [comment]
Problem and solution/workaround is here, please try with current release:
https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts

If it still crashes, keep all files in place, there is some debugging to do.

**Comment by KellenSunderland** [comment]
What I'm wondering is if the openblas org is able to update the package in
the official Ubuntu repo.

**Comment by martin-frbg** [comment]
Did you try raising the issue with whoever may be the Ubuntu "maintainer" of their openblas packages ?
https://wiki.ubuntu.com/UbuntuBackports (or perhaps it is already in the backports repository for that version - whatever the byname of 14.04 is)

**Comment by brada4** [comment]
@KellenSunderland what makes you think an update will help if you did not test with updated version?

**Comment by martin-frbg** [comment]
@brada4 if you bother to read the mxnet issue, they know it works with 0.2.18 onwards. This is just about getting a newer version into Ubuntu 14.04 (which appears to have 0.2.8 by default), which I think is not something "the openblas org" in its current state could or should do.

**Comment by brada4** [comment]
If one runs ubuntu-support-status on ubuntu 14.04 they see openblas packages are de-supported, which means no paying Ubuntu customer uses them now... 

Replacement FAQ way works just fine, and takes less nerves than pushing unpaid support...
