### ISSUE TITLE
windows crashed with error:Program will terminate because you tried to start too many threads

### ISSUE THREAD

**Issue by yplypl** [xianyi/OpenBLAS#1704]
i build openblas with following actions:
1. Install CMake at Windows
2. cmake -G "Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=Release .
3: open vs2013 and build success.

i am not familiar  with the build process,  can any one tell me how to build to cross this limit. 
by the way, crash is not that acceptable for me.

**Comment by brada4** [comment]
And what code leads to errors?
Do you run result on same machine as build?
Which OpenBLAS version?

**Comment by martin-frbg** [comment]
Which version is this ? There was a bug in 0.3.1 that could cause this, but the problem is supposed to be fixed in 0.3.2 (or current develop)

**Comment by yplypl** [comment]
i just tried the last version V0.3.3 still the same error。
@brada4  yes， dll is called on the same build machine。 
it crashed at blas_memory_alloc called by cblas_dgemm, call stack as below：
![a7g5gjn mg n nuz2 4](https://user-images.githubusercontent.com/6971032/43558102-516835a6-963a-11e8-83cb-fa77a2f43c6d.png)

what‘s more， it don't crash at the first call, after several times called，this crash happed.

**Comment by yplypl** [comment]
my pc is win10 i5 4cores. may openblas_config.h can supply more help
[openblas_config.h.txt](https://github.com/xianyi/OpenBLAS/files/2251827/openblas_config.h.txt)

**Comment by martin-frbg** [comment]
The only strangeness in your openblas_config.txt is that the cpu support is identified as "generic" rather than Haswell, as if it did not identify the hardware correctly (although it did see four cpus). How many threads are you expecting to run in this context ? You may need to build with a higher number of NUM_THREADS to get around the problem if you are planning on more than 8 (4 + hyperthreading). (And there is still the possibility that some assumption in rewrite of the thread memory allocation code from 0.3.1 is incorrect, so you could also try if v0.3.0 shows similar problems)

**Comment by yplypl** [comment]
i just use one thread to call cblas_dgemm in one business loop。 and it crashed after 3 business loop finished。 if NUM_THREADS is not enough， it should crash in my first loop。
i hope one cblas_dgemm call， 4 below threads help to calculate will be great， but the calling thread num can be unlimited.

**Comment by martin-frbg** [comment]
Not sure how you are calling OpenBLAS, somehow this looks as if you are creating a new instance with every call (and the "old" ones still stay around). Does your code use OpenMP ?

**Comment by martin-frbg** [comment]
BTW this is related to #1641.

**Comment by yplypl** [comment]
yes，OpenMP is called at other place in my code。

**Comment by martin-frbg** [comment]
Did you build OpenBLAS with OpenMP support as well (USE_OPENMP=1) ?

**Comment by brada4** [comment]
As a side note - cuBLAS supports gemm that does not do host-device moves....

**Comment by yplypl** [comment]
could u tell me how to enable USE_OPENMP and change NUM_THREADS。
is following steps right？
1：Install CMake at Windows
2：cmake -G "Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=1 -DNUM_THREADS=20 .
3: open vs2013 and build success.

**Comment by martin-frbg** [comment]
Yes this should work.

**Comment by yplypl** [comment]
@brada4 yes,  cuBlas is  also used in my program,  it works great。now  i am trying to improve the cpu calculation performance。

**Comment by yplypl** [comment]
@martin-frbg 
change to USE_OPENMP=1 -DNUM_THREADS=20 still the same error。but take a longer time to crash

**Comment by martin-frbg** [comment]
Do you have any indication (from task manager, or your program) how many threads actually become active until it crashes ? I guess we could simply re-do #1663 with a tenfold (or whatever) increase instead of just doubling the size of the pointer array, but some additional insight into the behaviour or expectations of real-world programs might be useful. (I suspect your code would have failed with a similar message in 0.3.0 or earlier versions as well, unless you build it with a huge value of NUM_THREADS)

**Comment by yplypl** [comment]
i did not notice that, my training net always close the old thread, and  used a new thread to forward and backward. sorry for my mistake. thanks for all your help. now, i change to use the same thread. it works great!
