### ISSUE TITLE
segfault in alloc_mmap 

### ISSUE THREAD

**Issue by vfonov** [xianyi/OpenBLAS#1705]
After compiling OpenBLAS 0.3.2 with gcc 7.2.0 from conda , I experienced Segmentation fault in gotoblas_init.

A little bit of research showed that there is a bug introduced by https://github.com/xianyi/OpenBLAS/commit/a399d004257b2f43e8211341f924f3a73171b98c 
Namely , in https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/memory.c#L687 current is set to allocation_block_size, and then in the loop starting in https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/memory.c#L689 it is decremented by PAGESIZE
But allocation_block_size=BUFFER_SIZE + sizeof(struct alloc_t)  which is not a multiplactive of PAGESIZE, resulting in current eventually going below 0 , and since it is an unsigned integer, becoming huge number, causing a segfault. 
Fix would be to replace "while(current > 0)" with "while(current > (PAGESIZE-1))" in https://github.com/xianyi/OpenBLAS/blob/develop/driver/others/memory.c#L689

**Comment by martin-frbg** [comment]
Thanks. Just when I thought the code had stabilized again after 0.3.1 ... @oon3m0oo

**Comment by oon3m0oo** [comment]
I see the issue. BUFFER_SIZE and PAGESIZE are defined independently in common*.h. It doesn't look like there was ever a guarantee that BUFFER_SIZE would be a multiple of PAGESIZE, they just happened to be defaulted that way.

@vfonov I think your suggestion would actually be off by one, since that loop seems to increment start until all of the allocated block fits.  I think it should be something like:
640: BLASULONG best, start, current, original;
...
688: original = current;
689:
690:	while(current > 0 && current <= original) {

This way we'd detect the wraparound but still have enough pages to hold the entire allocation.  I don't have a good way to test this since we don't use mmap here, but @vfonov could you try this out and see if it works for you?

**Comment by vfonov** [comment]
Yes, that seem to work too.
The last value is not used anyway, since the only place where these values are used are in run_bench to traverse the array and there is another condition which limits accessing that last few bytes of the buffer (line 702).
