### ISSUE TITLE
OpenBLAS for R - Builds sucessfully, but test crashes

### ISSUE THREAD

**Issue by thequackdaddy** [xianyi/OpenBLAS#1750]
Hello,

I've been building OpenBLAS for R on Appveyor. It works great. 

I can build it, and pass the tests (`openblas_utest`) with version 0.2.20. 

See here:
https://ci.appveyor.com/project/thequackdaddy/openblasr/build/1.0.52

I tried to upgrade to 0.3.3 and the build completes, but it fails on the test:
https://ci.appveyor.com/project/thequackdaddy/openblasr/build/1.0.51/job/qu1iu2d678p4lnf4

Any ideas why? 

`openblas_utest
      0 [main] openblas_utest 4844 C:\projects\openblasr\OpenBLAS\utest\openblas_utest.exe: *** fatal error - internal error reading the windows environment - too many environment variables?
   1801 [main] openblas_utest 4844 cygwin_exception::open_stackdumpfile: Dumping stack trace to openblas_utest.exe.stackdump
Command exited with code 256`

**Comment by martin-frbg** [comment]
This appears to be an old cygwin bug where it fails to convert the Windows environment variables to its cygwin environment, see https://github.com/git-for-windows/git/issues/942 and links to the cygwin mailing list therein.

**Comment by brada4** [comment]
You can actually rename any openblas.dll from https://github.com/xianyi/OpenBLAS/wiki/Precompiled-installation-packages to Rblas.dll

**Comment by brada4** [comment]
I looked at your recent appveyor logs and it seems to succeed now. Could we close the issue?

**Comment by thequackdaddy** [comment]
I think the crash happens when I compile 0.3.3. Version 0.2.20 is passing
fine.

**Comment by thequackdaddy** [comment]
Also, thanks for tip re: renaming openblas.dll -> rblas.dll. I hadn't seen that.

Feel free to close issue if you are trying to keep project clean.

**Comment by martin-frbg** [comment]
Most of utest was (re-)added only early this year, which might explain why you did not see this with 0.2.20. The CI setup for OpenBLAS does not contain a Windows mingw build on Appveyor (but there is a cross-build using mingw on Linux as part of the Travis configuration)
Edited to add: it could also bee that your environment is bigger if your Appveyor configuration includes R or related settings.

**Comment by brada4** [comment]
Could be worth also to test-build with [Rtools](https://cran.r-project.org/bin/windows/Rtools/) i.e mingw gcc used to compile R itself
Indeed it could go wrong as R sets about 8KB environment via $R_BASE/etc/Renviron when invoking make/cmake and compilers afterwards.

**Comment by brada4** [comment]
@thequackdaddy it actually builds (typing make in source dir of 0.3.3 and develop) with rtools34 on windows 10.
I am afraid you use (CI &) compilers provided by you and it is up to you to adjust them so that they work fine

**Comment by thequackdaddy** [comment]
Right. To be clear, it builds fine, but fails on `openblas_utest`.

Feel free to close this.

**Comment by martin-frbg** [comment]
The curious thing is that mingw-w64-...-git-6.0.0.5225.fb06a4bf-1 appears to be new, while the cygwin bug I mentioned above was found and fixed in 2015.  Not sure what rtools34 is based on, the rtools page makes it look like it is gcc 4.9.3/mingw-w64-3.x (Edit: seems the mingw from the Appveyor logs identifies as 4.9.3 with a 2015 copyright as well ?)

**Comment by thequackdaddy** [comment]
I think the mingw 6.0.0 thing is irrelevant. openblas needs to be compiled within msys/cygwin to work... can't do it in standard windows command line. I update it for grins, but I don't use the msys gcc.

Rtools uses 4.9.3, and that's what I use to compile. I've found using a newer gcc makes the resulting DLL not work.

**Comment by martin-frbg** [comment]
So you get the utest crash with the "cygwin internal error" from rtools as well ?

**Comment by thequackdaddy** [comment]
Yes. I'm complaining only of Rtools 3.4. Sorry for confusion. gcc 6.0.0 is irrelevant for me. That works fine, I assume.

**Comment by brada4** [comment]
Does not happen with "generic" windows+rtools
Can you dump "set" before openblas_utest ?
Also you could try invoking bash -c make from cygwin run.exe ?

**Comment by martin-frbg** [comment]
"Size of the environment" may be a red herring as well, I have now dug up bug reports surrounding the original cygwin issue where the environment size was quite small. I cannot find details on when rtools34,exe was released and what it was based on.

**Comment by brada4** [comment]
R itself and R "packages" are built via 'R CMD COMPILE make.exe' which sets that 8k environment from etc/makeconf
I see something fishy with CI log installing something with pacman , then something like msys2.cmd, looks like R(tools) gets intermixed with generic mingw....

https://cran.r-project.org/bin/windows/Rtools/
Around 'Changes since R 3.2.2 ...'
Up to 3.2.2 gcc 4.6 was in PATH when run 
From 3.3 on it is no more in PATH and env is initialized via R CMD as above.

It looks like (old(-er) mingw) re-built rarely, probably self-hosted bootstrap to celebrate new release. It worked already to build all R releases + 10k binary packages in CRAN archive....

Linux builds using system gcc/gfortran + CC flags used to built R packages themselves (like ones applied by package management)

Example Renviron build config, extracted from opensuse 15.0 R-3.5.0 package.
[Makeconf.txt](https://github.com/xianyi/OpenBLAS/files/2376496/Makeconf.txt)
