### ISSUE TITLE
cross-compile liblapack

### ISSUE THREAD

**Issue by han-so1omon** [xianyi/OpenBLAS#1810]
After building with `make HOSTCC=gcc TARGET=ARMV7 CC=arm-linux-gnueabihf-gcc FC=arm-linux-gnueabihf-gfortran NO_SHARED=0 BINARY=32`, the openblas libraries are built, but not the lapack libraries. The install process adds the following files to the install location:

```

include/:
cblas.h
f77blas.h
lapacke_config.h
lapacke.h
lapacke_mangling.h
lapacke_utils.h
openblas_config.h

lib/:
cmake
libopenblas.a
libopenblas_armv7p-r0.3.4.dev.a
libopenblas_armv7p-r0.3.4.dev.so
libopenblas.so
libopenblas.so.0
pkgconfig

```

What is the command to build liblapack.so (and libcblas.so)?

**Comment by brada4** [comment]
You can rename the file, it contains all of:
libblas.so
libcblas.so
liblapack.so
liblapacke.so

**Comment by brada4** [comment]
You need to set HOSTCC=gcc for cross-compilation

**Comment by han-so1omon** [comment]
Yes, `HOSTCC=gcc` is in the full command that I used. Edited that in. How do I rename the file? Which file is being renamed?

**Comment by martin-frbg** [comment]
If you really need a separate liblapack.so etc., copy libopenblas.so to that name. The build system creates just one library that contains all of blas, cblas, lapack and lapacke.

**Comment by han-so1omon** [comment]
ok thanks. i might need it for mxnet. mxnet links against liblapack to allow for certain linear algebra operations.

**Comment by brada4** [comment]
Normally you set mxnet so that all BLAS/LAPACK interfaces are
`-L/opt/OpenBLAS/lib -lopenblas -I/opt/OpenBLAS/include`
If that fails (should not with mxnet)
```
ln -s libopenblas.so libblas.so
ln -s libopenblas.so libcblas.so
ln -s libopenblas.so liblapack.so
ln -s libopenblas.so liblapacke.so
```
And in ./configure:
`--with-blas/lapack-libs=/opt/OpenBLAS/lib --with-blas-includes=/opt/OpenBLAS/include`

It is "simpler" to have pre-baked guides if you use Ubuntu:
https://mxnet.incubator.apache.org/install/ubuntu_setup.html
And then you can try out latest release IF you have time:
https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts
