### ISSUE TITLE
izamax does not return zero for zero elements

### ISSUE THREAD

**Issue by amigalemming** [xianyi/OpenBLAS#1860]
For `N=0` I do not get 0.0 as result but `1.71795953e-316`.
The problem does not arise for `icamax`, `isamax`, `idamax`.

I am using:
~~~~
$ dpkg --list "*openblas*"
...
ii  libopenblas-base        0.2.18-1ubuntu1  amd64            Optimized BLAS (linear algebra) library (shared lib
~~~~

**Comment by brada4** [comment]
Does it fail with the latest development version?
https://github.com/xianyi/OpenBLAS/wiki/faq#debianlts

What is your CPUID (like `lscpu` or `cat /proc/cpuinfo`)?
EDIT: izamax returns integer (int32 in typical case) 
EDIT2: There is a code unchanged forever including since that version:
```
  if (n <= 0) return 0
```
There is no chance it could fail and return anything else.

**Comment by brada4** [comment]
Are you calling izamax() or izamax_() or cblas_izamax() ? Later looks suspicious (but not suspicious in OpenBLAS)

**Comment by amigalemming** [comment]
Ah sorry, I peeked the value indicated by the returned index.
