### ISSUE TITLE
ENH: add an extension to get the library version

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#1889]
I could not find an interface to query the version number (i.e. 0.3.3, 0.3.0) of OpenBLAS.

In the process I found the [wiki page](https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions) for the extensions, but there is not one for the version. Even using `strings *.so` I could not find it.

**Comment by mattip** [comment]
xref numpy/numpy#12457

**Comment by brada4** [comment]
There is no version number stored anywhere in library.
There is no chance to get it working retroactively, in regard to v0.3.3 or 0.3.0
@martin-frbg what do you think about getting `VERSION` from Makefile.rule into openblas_get_config()?
Or something like ilaver ? http://www.netlib.org/lapack/explore-3.1.1-html/ilaver.f.html

**Comment by martin-frbg** [comment]
Currently the version number (only) ends up in the name of the library and in the openblas_config.h that gets included from the cblas.h distributed with it. The former may get lost if only libopenblas.so (originally a symlink to the long name) gets copied over, the latter could end up in a separate openblas-dev package. So indeed adding it to the get_config() output and/or creating a dedicated openblas_get_version() seems desirable.

**Comment by martin-frbg** [comment]
In the meantime, pkg-config may provide another way to get version information (where available)

**Comment by mattip** [comment]
I tried to tackle this, adding a `char * open_blas_get_version()` to `driver/others/openblas_get_version.c`. It seems the OpenBLAS version only appears at the top of `CMakeLists.txt`, and it is used only in the installation scripts. What would be the easiest way to get it into a header file?

**Comment by tylerjereddy** [comment]
I managed to dissect the following data from the binary wheel zip in question using the approach described in linked issue above:

```
numpy/.dylibs/libopenblasp-r0.3.0.dev.dylib
numpy/.dylibs/libopenblasp-r0.3.0.dev.dylibPK
./RECORD:numpy/.dylibs/libopenblasp-r0.3.0.dev.dylib,sha256=L3iI-ISr5GviFRt1tc4Aqea4ObNYBPZWjnqQvtEwdLc,97864916
```

Are those version numbers and hash sufficient to come up with a fairly conclusive analysis?

**Comment by brada4** [comment]
@tylerjereddy I think you posted in a wrong thread.

**Comment by martin-frbg** [comment]
@tylerjereddy I do not know about the hash, but "0.3.0.dev" unfortunately is not a distinct release but a snapshot of the `develop` branch from some unspecified time _before_ the 0.3.0 release. (Yes, this "historic" decision to name the develop tree after the _next_ upcoming release has been criticised occasionally). If people are distributing snapshots due to the sometimes erratic release cycles here, 
perhaps it would even make sense to include the github hash in the openblas_get_config output IF
there is some simple automatic way to obtain it. (Having to update the version number manually at release time is probably error-prone enough)

**Comment by martin-frbg** [comment]
@mattip I am already working on it in PR #1890, I just need to fix the formatting (I think)
