### ISSUE TITLE
Use OpenBLAS in C program

### ISSUE THREAD

**Issue by ayush1999** [xianyi/OpenBLAS#1925]
I was able to successfully install OpenBLAS in Ubuntu. However, how can I use this installed package in my C program? Are there any docs related to this available? (What should be done so that I can #include the package?)

**Comment by martin-frbg** [comment]
OpenBLAS implements the standard BLAS (and LAPACK) functions, so you can use the documentation from the reference implementation at http://netlib.org/blas/index.html#_blas_routines. As you are calling it from C, you will probably want to use the CBLAS interface (and include cblas.h in your programs). If you already know how to use BLAS routines, it becomes just a matter of linking your code with `-lopenblas` instead of `-lblas` or `-llapack`.

**Comment by ayush1999** [comment]
@martin-frbg Thanks. Also, I wanted to know if openblas supports aarch64 cpu at the moment. If not, what would be the steps for implementing support for aarch64?

**Comment by martin-frbg** [comment]
aarch64 is available , labeled "arm64" in the source tree. There is currently support for generic ARMV8 (CortexA5x/CortexA7x) as well as Cavium ThunderX server processors. (See file TargetList.txt for all
supported hardware)

**Comment by fenrus75** [comment]
#include <cblas.h>

cblas_sgemm(CblasRowMajor, CblasNoTrans, CblasNoTrans, M, N, K, 1.0, A, K, B, N, 0.0, result, N);

this will do result = A * B

https://petewarden.files.wordpress.com/2015/04/gemm_corrected.png has a nice diagram to remind you what M N and K sizes are

this assumes normal C 2 dimenisonal arrays of floats. Use 'dgemm' not sgemm if you want doubles

**Comment by martin-frbg** [comment]
Added to the Faq in the wiki

**Comment by ayush1999** [comment]
@martin-frbg I was wondering how openblas decides the optimization to use dynamically. In other words, which kinds of system level checks are done to confirm the target architecture? (Also, could you point me to the code for these checks?). Thanks.

**Comment by martin-frbg** [comment]
cpuid - see driver/others/dynamic.c (x86) and driver/others/dynamic_arm64.c (aarch64).

**Comment by ayush1999** [comment]
@martin-frbg Thanks! Also, if I need to implement dynamic support for some other architecture (I'm mainly interested in s390x), what would the general process be?

**Comment by martin-frbg** [comment]
Dynamic support for aarch64 was added only recently in #1829, so that pull request can probably serve as a guideline although it also contained some rearrangements of cpu support. 
With the current support for s390x being limited to either Z13 or the "generic" C implementations, zarch may not be a top candidate for dynamic support (Z14 does get autodetected but is treated as Z13).
