### ISSUE TITLE
Issues building 0.3.5 with CMake on Linux with USE_OPENMP

### ISSUE THREAD

**Issue by greenc-FNAL** [xianyi/OpenBLAS#1984]
Attempting to build OpenBLAS for the first time for repackaging, and configuring with the following options on Scientific Linux 7 with GCC 8.2.0:
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<install-dir> -DCMAKE_C_COMPILER=gcc -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_CXX_STANDARD=17 -DCMAKE_Fortran_FLAGS=-ffree-line-length-none -DBUILD_SHARED_LIBS=ON -DDYNAMIC_ARCH=ON -DDYNAMIC_OLDER=ON -DUSE_OPENMP=ON -DUSE_THREAD=ON -DCMAKE_POLICY_DEFAULT_CMP0054=NEW <src-dir>
```

[ The policy statement is necessary with newer CMake to avoid a warning about line 542 of `kernel/CMake`, which says `set(TARGET_CORE ${CORE})`. In order to be unamiguous, this line should be `set(TARGET_CORE "${CORE}")` ]

The build proceeds well until the final link, when everything fails with (_e.g._):
```
[100%] Linking Fortran executable cblat3
../lib/libopenblas.so.0.3: undefined reference to `zgetrf_parallel'
../lib/libopenblas.so.0.3: undefined reference to `cgetrf_parallel'
../lib/libopenblas.so.0.3: undefined reference to `sgetrf_parallel'
../lib/libopenblas.so.0.3: undefined reference to `dgetrf_parallel'
```

Indeed, these files appear never to be compiled?

Is there an easy way to resolve this issue with a workaround? There is a reason we'd prefer to stay with CMake if at all possible.

Thanks for your help,
Chris.

**Comment by martin-frbg** [comment]
This appears to be a shortcoming in lapack/CMakeLists.txt (and it seems this has been wrong in all versions since the introduction of cmake support in 0.2.15) - it does build from getrf_parallel_omp.c rather than getrf_parallel.c in the OpenMP case as desired, but it does not drop the "_omp" suffix from the object name. This probably needs a separate invocation of GenerateNamedObjects just for GETRF_SRC, I'll see if I can post a fix tomorrow.

**Comment by martin-frbg** [comment]
PR #1985 should apply cleanly to 0.3.5 as well - if you add ".diff" to the end of its URL, github will format it for you as a regular diff file that can be used to patch the source.
