### ISSUE TITLE
cannot locate symbol "stderr" referenced by "./XXX"...

### ISSUE THREAD

**Issue by 11721206** [xianyi/OpenBLAS#2027]
I try the steps in next link:
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android
I can get the libopenblas.a, but an error occurs:
CANNOT LINK EXECUTABLE: cannot locate symbol "stderr" referenced by "./XXX"...
 An I get the android binary package from 
https://sourceforge.net/projects/openblas/files/v0.2.8-arm/
the test code as follows:
#include <cblas.h>
#include <stdio.h>
int main()
{
int i=0;
double A[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
double B[6] = {1.0,2.0,1.0,-3.0,4.0,-1.0};
double C[9] = {.5,.5,.5,.5,.5,.5,.5,.5,.5};
cblas_dgemm(CblasColMajor, CblasNoTrans, CblasTrans,3,3,2,1,A, 3, B, 3,2,C,3);

for(i=0; i<9; i++)
printf("%lf ", C[i]);
printf("\n");
return 0;
}
 it can run success, but in my project, the same error still occurs:
cannot locate symbol "stderr" referenced by "./XXX"...
my application.mk is:
APP_ABI := armeabi-v7a
APP_STL := c++_static
APP_OPTIM := release
APP_PLATFORM := android-24

is there any suggestions for my questions?
thx very much.

**Comment by martin-frbg** [comment]
From the suggestions in https://github.com/android-ndk/ndk/issues/543 (found by google) this could be due to a mismatch of API versions between your code and what OpenBLAS (or any other third-party code you use) was built for. 
Unfortunately the last prebuilt binary provided on sourceforge is about six years old (so certainly built for an equally old Android API), so you will probably have more luck with a libopenblas built by yourself from the current sources (either the 0.3.5 release or current `develop` branch). 
It has recently been pointed out in https://github.com/xianyi/OpenBLAS/issues/2005 that the build instructions in the wiki may be outdated and much too complicated for recent NDK versions, hopefully the simplified build steps suggested will provide a solution for your problem.

**Comment by brada4** [comment]
It is sort of written in the page you linked that static linking to stderr ends with API23
