### ISSUE TITLE
对 cpu加速效果最好的是哪个版本的   与0.2.14.1版比较提升了多少

### ISSUE THREAD

**Issue by mengpengfei** [xianyi/OpenBLAS#2083]

**Comment by brada4** [comment]
请像我一样用谷歌翻译
该项目最近没有活动
Based on google translation you need CPU support improvements since 0.2.14:
0.2.18 adds haswell (avx2)
0.3.3 adds skylake xeons (avx512) that is still being improved as of 0.3.5
In current develop branch Hygon Dhyana is added, but just like with ZEN/EPYC code is equivalent to haswell
Also added hundreds of bug fixes also for old processors
