### ISSUE TITLE
memory.c invalid argument type in v0.3.6

### ISSUE THREAD

**Issue by tylerjereddy** [xianyi/OpenBLAS#2104]
Bumping OpenBLAS builds from `v0.3.5` stable release to `v0.3.6` stable release in downstream scientific Python ecosystem (see PR [here](https://github.com/MacPython/openblas-libs/pull/2)) is causing a new error to crop up from the OpenBLAS source:

```
memory.c: In function ‘get_num_procs’:
memory.c:1775:10: error: invalid type argument of ‘->’ (have ‘cpu_set_t’)
      if (CPU_ISSET(i,cpuset)) n++;
          ^
```

Comparing the build log with the last successful build (`v0.3.5`), the first point of deviation appears to be this new warning, which may or may not be pertinent:
```
getarch.c:96:0: warning: "NO_AVX512" redefined [enabled by default]
 #define NO_AVX512
 ^
<command-line>:0:0: note: this is the location of the previous definition
```

Any suggestions for us?

**Comment by tylerjereddy** [comment]
Also potentially relevant -- we only observe this on Linux Travis builds--not Mac & not Windows / Appveyor.

**Comment by martin-frbg** [comment]
Not related, but the problematic change did happen in the timeframe between 0.3.5 and 0.3.6 (#2008) The function is specific to Linux (or more precisely, to unixoid systems that use GNU libc) and is used when the version of libc is between 2.3 and 2.5 (versions from around 2007). I suspect this is a genuine bug (typo) that went unnoticed due to the specific old libc version required to trigger it - this should in all likelyhood read `&cpuset` rather than plain `cpuset` . (Note there is a second instance of this CPU_ISSET() call near line 200 of memory.c, in the alternative implementation that is invoked by USE_TLS=1)

**Comment by brada4** [comment]
Red Hat 5 is only packaging bundling such old glibc today, but thats far from scientific python whatever, no avx1 in compiler nor avx512 in kernel

**Comment by charris** [comment]
@brada4 I think that is part of the `manylinux1` pypa specification which is based on an old CentOS version. There is a `manylinux2` spec in the works, but it just moves the CentOS version up a bit.

**Comment by brada4** [comment]
Are you systematically to withholding information?
manylinux2 is released year ago.

**Comment by brada4** [comment]
I got it, `manylinux1_i686` , the new one is 64bit-only
I think it could fit in CI here. There have been other problems accidentally introduced to native build on x86_32 by cross-building only on x86_64

**Comment by martin-frbg** [comment]
Can you confirm that changing the offending line to
```
if (CPU_ISSET(i,&cpuset)) n++;
```
fixes the build ?

**Comment by tylerjereddy** [comment]
I confirmed the `manylinux1` OpenBLAS build fix in the cross-linked PR, thank you!
