### ISSUE TITLE
Include Question & Proper Functionality

### ISSUE THREAD

**Issue by vineetdodd** [xianyi/OpenBLAS#2147]
1. I apologize in advance if this is a silly question, but I was wondering if doing "#include <cblas.h>" would in any situation automatically reference OpenBLAS if it has been installed. The reason I ask is I find myself in a situation where I can't touch the compilation command, but I need to link OpenBLAS regardless. Is there something I can set so that it by default looks to OpenBLAS instead of the default BLAS package? On Ubuntu? On Windows?

2. How do I know that the OpenBLAS package is being called, and not the default BLAS package installed (assuming I'm in a situation where I can control compilation commands)? Is there a special flag or indicator I can look to? The reason I ask is, I believe I am dynamically linking this using the command in the basic example (https://gist.github.com/xianyi/6930656), but I don't think that I am calling the right package, as when I don't dynamically link this, I get similar runtimes when I extend the tests to, say, 5000 x 5000 matrices.

Thank you! Any help is appreciated.

**Comment by martin-frbg** [comment]
1. The "#include <cblas.h>" would not automatically reference OpenBLAS, as all it does is provide function prototypes for the compiler. If the cblas.h in the include path at compilation time (which I understand you cannot modify) happens to point to a cblas.h from OpenBLAS, this would make a few additional utility functions like openblas_get_config known to the compiler, but otherwise the definitions should be interchangeable. That is, you should be able to use any cblas.h at compilation time and still swap the dynamically linked BLAS library later as long as your code only uses the standard BLAS functions.
2. On Ubuntu (or any other Linux) you can run `ldd` on your executable to see which libraries will be
dynamically loaded at runtime. You can set the LD_LIBRARY_PATH environment variable to any directory that should take precedence in the search, Ubuntu and others also have an "alternatives"
mechanism (see documentation on update-alternatives) that lets you switch between available implementations by adjusting symbolic links to point to the desired files.

**Comment by brada4** [comment]
1. `cblas.h` does not specify any particular implementation, you can choose one with `-lopenblas` and alike parameters , even after you can just drop likewise named .dll file of other implementation on windows, or LD_PRELOAD on Linux - so it is best to `-lblas` (the NetLib reference implementation) and change later.
Note that there are other `cblas.h` files in macro libraries like eigen or gsl, API compatible, but read their manuals if you find such file, it will not be OpenBLAS, even down the configurations the right DLL gets linked into executable.
