### ISSUE TITLE
USE_TLS=0 == USE_TLS=1

### ISSUE THREAD

**Issue by TiborGY** [xianyi/OpenBLAS#2149]
Somewhere in the build system it is only checking if USE_TLS is defined, instead of actually checking its value. Thus, having USE_TLS = 0  in Makefile.rule leads to a TLS enabled build.

**Comment by brada4** [comment]
Most commented-out parameters there have similar side effect. Sure, PRs welcome.

**Comment by martin-frbg** [comment]
It may not be the most elegant way of handling this, but at the top of memory.c (which is the only place where this option has any effect) the code actually does check if USE_TLS is set to anything other than 1.
 https://github.com/xianyi/OpenBLAS/blob/27649b95430cbed40923db4ab45119af6b05acb3/driver/others/memory.c#L79

**Comment by TiborGY** [comment]
Ah, OK, I just saw the -DUSE_TLS during a compilation and assumed it acts like other defines.
I might eventually dig into the build system to find a better way, but good to know it is not urgent at all.

**Comment by martin-frbg** [comment]
Unfortunately you are right - my supposed safeguard in memory.c actually does nothing to prevent this accidental activation. (Though I could have sworn that I tested "all" possible scenarios by putting a compile-time`#warning' in the TLS path - when the issue was already raised in #1766.) The general problem with ambiguous OPTION=0 variables was already highlighted and (mostly?) fixed in #1422...
