### ISSUE TITLE
Can't use AVX-512 on X86-64 with openblas 0.3.6 version?

### ISSUE THREAD

**Issue by gxkevin** [xianyi/OpenBLAS#2182]
I found that in the latest version 0.3.6, the AVX512 DGEMM kernel has been disabled again due to unsolved problems.

It means that we can't use the avx512?

what about the 0.3.7-dev ?

**Comment by gxkevin** [comment]
DGEMM was disabled, what about the SGEMM ?

**Comment by martin-frbg** [comment]
Indeed most of the AVX512 DGEMM optimizations had to be disabled in 0.3.6, and 0.3.7.dev disables the remaining ones that were originally thought to be safe. Unfortunately the person who contributed this code has not been active here since march, and I have been unable to track down the problem in his code.  There are no known problems with the AVX512 SGEMM kernel.

**Comment by gxkevin** [comment]
what about 0.3.5 or earlier release? Does it enable the avx512？

**Comment by martin-frbg** [comment]
AVX512 DGEMM was added in 0.3.4 but it returns wrong results for some inputs. (#1955, #2029, #2168)
Actually disabling or enabling the AVX512 kernels is just a matter of (un)commenting a few lines in kernel/x86_64/KERNEL.SKYLAKEX, if you want to check if its affects your typical use cases.

**Comment by martin-frbg** [comment]
Fixed now by wjc404's new AVX512 DGEMM kernel from #2286
