### ISSUE TITLE
Numerical Issues with DGESV

### ISSUE THREAD

**Issue by TsarpDev** [xianyi/OpenBLAS#2184]
Hello OpenBLAS community,
I'm facing numerical issues using Lapack given by OpenBLAS. In particular, I get incorrect results using DGESV for solving a linear system. I'm attaching the test matrices A and B for solving A*x=B:
[A.txt](https://github.com/xianyi/OpenBLAS/files/3388952/A.txt)
[B.txt](https://github.com/xianyi/OpenBLAS/files/3388953/B.txt)

I was thinking that I might have done a mistake but:
1) Using the same code but just the netlib lapack the results are correct.
2) Dealing with matrices of size lower than 18x18 the results are correct (maybe cache issue?).
3) BLAS routines work correct.

Details about my machine:
CPU: Intel i5-7500 @3.40 GHz
RAM: 16 GB
OS: Windows (using flang)
L1 cache: 256 KB
L2 cache: 1.0 MB
L3 cache: 6.0 MB

Thank you

**Comment by martin-frbg** [comment]
Which version of OpenBLAS, and could you post your entire test code please ? (With current develop branch on Linux, I get the exact same results with and without OpenBLAS' own implementation of dgesv - and also with plain netlib 3.8.0, when I plug your test matrices into the dgesv example from the MKL documentation)

**Comment by brada4** [comment]
Please patch BIOS and/or intel-microcode past this numeric problem:
https://lists.debian.org/debian-devel/2017/06/msg00308.html

**Comment by TsarpDev** [comment]
I'm using my own class storage system for the matrices but in a plain C++ format the code will look like this:

    #include "f77blas.h"
    #include <random>
    
    extern "C" int BLASFUNC(dgesv)(blasint *, blasint *, double *, blasint *, blasint *, double*, blasint *, blasint *);
    extern "C" void BLASFUNC(dgemv)(char *, blasint *, blasint *, double *, double *, blasint *, double *, blasint *, double *, double *, blasint *);
    extern "C" double BLASFUNC(dnrm2) (blasint *, double *, blasint *);
	
    int main()
    {
    	int n = 18;
    	int nrhs = 1;
    
    	uint32_t seed;
    	std::mt19937 eng;
    
    	std::srand(time(nullptr));
    	seed = std::rand();
    	eng.seed(seed);
    
    	double *A, *Acpy, *B, *error;
    	A = new double[n*n];
    	Acpy = new double[n*n];
    	B = new double[n];
    	error = new double[n];
    
    	for (int i = 0; i < n; i++)
    	{
    		B[i] = std::uniform_real_distribution<double>{ 0.0, 1.0 }(eng);
    		error[i] = B[i];
    		for (int j = 0; j < n; j++)
    		{
    			A[j + i * n] = std::uniform_real_distribution<double>{ 0.0, 1.0 }(eng);
    			Acpy[j + i * n] = A[j + i * n];
    		}
    
    	}
    
    	int* ipiv = new int[n];
    	int info;
    
    	//solve A*x=B and store it on B
    	BLASFUNC(dgesv)(&n, &nrhs, A, &n, ipiv, B, &n, &info);
    
    	//form A*x-B
    	char trans = 'N';
    	double alpha = 1.0;
    	double beta = -1.0;
    	int incr = 1.0;
    	BLASFUNC(dgemv)(&trans, &n, &n, &alpha, Acpy, &n, B, &incr, &beta, error, &incr);
    
    	double errornorm = BLASFUNC(dnrm2) (&n, error, &incr);
    
    	std::cout << "Error norm = " << errornorm << std::endl;
    
    	delete[] ipiv, A, Acpy, B, error;
    }

I'm using openblas 0.3.6 static lib in visual studio. Could you please test this code by increasing the size of the matrix n? I get correct results up until n=17.
From [https://ark.intel.com/content/www/us/en/ark/products/97123/intel-core-i5-7500-processor-6m-cache-up-to-3-80-ghz.html](url) I see that this CPU does not support hyper-threading, so I skip this issue?

Thank you for all your concern.

**Comment by martin-frbg** [comment]
With gcc9, OpenBLAS 0.3.6 on i7-7500U under Linux I get
  
 |    n   |      errornorm |
 |-----:|-----------------:|
|       5  |       2.20e-16|
 |    15  |       1.45e-15 |
 |    25  |       5.54e-15|
 |    35  |      1.00e-14|
 |    45  |      3.64e-14|
 |    55  |      2.53e-14|
 |    85  |      3.01e-14|
 |  155  |     2.92e-13|
 |  255  |     2.45e-13|
 |  555  |     5.29e-12|
| 1555  |     1.02e-10|
| 5555  |     1.72e-10|
|15555 |     3.33e-9|

which looks (to me at least) more like slow creep due to algorithmic differences (FMA?), not a sudden breakdown.

**Comment by TsarpDev** [comment]
I will move to Ubuntu and see if this problem still occurs. I'll send a feedback.
Thank you

**Comment by TsarpDev** [comment]
Just tested on Ubuntu, it works fine. Thus I guess something goes wrong with the Windows installation. I followed the instructions given in [https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio](url). What bugs me is that the BLAS functions work fine. Any suggestions?

**Comment by brada4** [comment]
Actually FMA increases accuracy and gives more accurate result than reference implementation, something like 1+log2(FLOP) bits are lost in each value. DMA is equivalent of multiple MUL and ADD instruction, but giving just one loss in place of few.
Probably something like TARGET=SANDYBRIDGE , the most advanced without FMA, will be closer to reference implementation, and Reference implementation with -march=native will deviate from plain gfortran too.
Not very practial in real life, but FMA version will be closer to full symbolic result.

**Comment by brada4** [comment]
Very simple FMA example :
Lets calculate
`AxB+CxD` when `B=D`
While full iteration will do 3 operations we can do the obvious algebraic simplification and get away with two deviating by not losing in one half-bit in the result.

While BLAS will always get small damage no matter the matrix size, it will accumulate with lapack where in all cases basically all input elements contribute to each output element.

**Comment by conradsnicta** [comment]
@TsarpDev - the prototype you're using for the dgemv() function is incomplete.  It doesn't include the so-called "hidden" length argument which must be present for each `char *` argument.

Instead of 
`extern "C" void BLASFUNC(dgemv)(char *, blasint *, blasint *, double *, double *, blasint *, double *, blasint *, double *, double *, blasint *);`

it should be:

`extern "C" void BLASFUNC(dgemv)(char *, blasint *, blasint *, double *, double *, blasint *, double *, blasint *, double *, double *, blasint *, fortran_charlen_t);`

where `fortran_charlen_t` is dependent on the compiler; it's typically 32 bit int on 32 bit systems, and 64 bit on 64 bit systems.

More info:
* https://gcc.gnu.org/onlinedocs/gfortran/Argument-passing-conventions.html
* https://developer.r-project.org/Blog/public/2019/05/15/gfortran-issues-with-lapack/
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90329
* https://gitlab.com/conradsnicta/armadillo-code/issues/123

**Comment by martin-frbg** [comment]
Not convinced this interface issue is actually the cause here - if it was, I would expect the pure netlib build to fail at least as spectacularly. (And we seem to have flang here, not gfortran which triggered the recent discussions/revelations regarding extra argument requirements for single-character strings)

**Comment by conradsnicta** [comment]
You're right - the interface is probably not the issue.  At the same time, I suspect flang uses the same argument passing mechanism as gfortran (for compatibility), so it's probably a good idea to point out problems with blas/lapack prototypes. The entire snafu with "hidden arguments" came about because folks weren't aware of the argument passing mechanism, and this propagated everywhere via cargo-cult programming.

**Comment by martin-frbg** [comment]
@conradsnicta I guess this is better discussed in #2154, but the actual API problem as I see it was that the gcc team introduced an optimization that made the hidden argument a requirement even for single-character strings, a detail of the standard which no major compiler appears to have enforced in decades. By the way DGESV happens to be one of the few LAPACK functions that OpenBLAS replaces with its own reimplementation written in C.

**Comment by martin-frbg** [comment]
@TsarpDev a Windows build of 0.3.6 is now in https://github.com/xianyi/OpenBLAS/issues/805#issuecomment-515676966 (cross-compiled on Linux with mingw from the MXE framework), hopefully it can be linked with your C++ code
