### ISSUE TITLE
omatcopy slow on Sandybridge

### ISSUE THREAD

**Issue by antoine-levitt** [xianyi/OpenBLAS#2232]
See https://github.com/JuliaLang/LinearAlgebra.jl/issues/658. omatcopy seems 2-3x slower than a julia implementation on a Sandybridge machine. On a Haswell, performance seems similar

**Comment by martin-frbg** [comment]
Probably related to JuliaLang/julia#1243 (though that one would not necessarily explain the speed difference between Haswell and Sandybridge)

**Comment by brada4** [comment]
Whats the size of input?

**Comment by antoine-levitt** [comment]
I tried in the range 500-1000

**Comment by brada4** [comment]
Could be Julia swaps pointers and/or maintains transform state and does nothing instead of memcopy()-es.

**Comment by antoine-levitt** [comment]
Nope, it does this: https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/src/transpose.jl#L95

**Comment by brada4** [comment]
OpenBLAs multiplies with 1.0 down the road, but should be at the speed of memory either way.
Probably it needs explicit unroll , though strange CC gets it right for haswell but not sandybridge.

**Comment by martin-frbg** [comment]
One fairly trivial thing to try - given that Haswell speed appears to be about correct - would be to increase the parameter SWITCH_RATIO in line 1417 of file param.h to 8 or 16, `make clean` and 
recompile.

**Comment by martin-frbg** [comment]
Sorry, SWITCH_RATIO has nothing to do with this - and contrary to Haswell, increasing this number does not appear to improve OpenBLAS performance in general. As for omatcopy, the current code is quite simplistic C so any differences in execution speed are probably due to hardware or compiler capabilities (the implementations for the four combinations of column/row major and trans/notrans are in kernel/arm with identical copies in kernel/mips).

**Comment by martin-frbg** [comment]
closing as fixed by JuliaLang/LinearAlgebra.jl#14
