### ISSUE TITLE
DTB_DEFAULT_ENTRIES undeclared, when cross compiling for x86_64

### ISSUE THREAD

**Issue by crayroud-nviso** [xianyi/OpenBLAS#2235]
I want to build OpenBLAS for an Intel NUC platform running Linux (Yocto). This is then a cross compile use case for x86_64.

I have set the TARGET to CORE2.

When compiling I have the following error: "error: 'DTB_DEFAULT_ENTRIES' undeclared"

Indeed when looking at the generated config.h file I have only the following:

```
#define OS_LINUX	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define FUNDERSCORE	
#define CORE2
#define CHAR_CORENAME "CORE2"
#define GEMM_MULTITHREAD_THRESHOLD	4
```

What I'm missing in order to export all cache, features and  cpu properties ?

**Comment by martin-frbg** [comment]
What other arguments did you pass to `make` besides the TARGET ? Are you actually cross-compiling (incompatible operating systems or cpus), or do you simply want to build (on another linux box) for the nuc ?

**Comment by crayroud-nviso** [comment]
I'm using the following arguments:

```
    -DDYNAMIC_ARCH=ON
    -DUSE_THREAD=OFF
    -DNUM_THREADS=0
    -DUSE_LOCKING=ON
    -DBUILD_WITHOUT_LAPACK=ON
    -DBUILD_RELAPACK=OFF
    -DNOFORTRAN=ON
    -DBUILD_SHARED_LIBS=OFF
```

I'm cross compiling (on Ubuntu 16.04 LTS) for Yocto Linux. I'm using x86_64-poky-linux-gcc cross compiler and Yocto sysroot.

**Comment by martin-frbg** [comment]
Not sure where the poky compiler and yocto sysroot comes in, wouldn't you need this for ARM-based targets only ? If you just want to go from x86_64 ubuntu pc to x86_64 NUC running yocto, the system default compiler is probably sufficient. (If you really need the poky one, you may have to set HOSTCC to point at the ubuntu gcc so that build-time tools like getarch can execute)

**Comment by martin-frbg** [comment]
Actually if (from the way you quoted your build arguments above) you are building with CMAKE, this seems to be caused by a deficiency in the cmake support files - in cmake/prebuild.cmake, it is assumed that the "getarch" tool would be useless for cross-compiling as it would run on the build host. (Not completely true as it can be fed arguments to retrieve the data for a specified cpu). So instead there is currently a kludgy table of values for a select few cpus assumed to cover "typical"
cases of cross-compilation - and this has only ARM cpus. 
Note this problem should not exist for plain `make` builds - for cmake, this untested patch should work:
```
-- a/cmake/prebuild.cmake
+++ b/cmake/prebuild.cmake
@@ -106,7 +106,25 @@ if (DEFINED CORE AND CMAKE_CROSSCOMPILING AND NOT (${HOST_OS} STREQUAL "WINDOWSS
   file(APPEND ${TARGET_CONF_TEMP}
     "#define ${TCORE}\n"
     "#define CHAR_CORENAME \"${TCORE}\"\n")
-  if ("${TCORE}" STREQUAL "ARMV7")
+  if ("${TCORE}" STREQUAL "CORE2")
+    file(APPEND ${TARGET_CONF_TEMP}
+      "#define L1_DATA_SIZE\t32768\n"
+      "#define L1_DATA_LINESIZE\t64\n"
+      "#define L2_SIZE\t1048576\n"
+      "#define L2_LINESIZE\t64\n"
+      "#define DTB_DEFAULT_ENTRIES\t256\n"
+      "#define DTB_SIZE\t4096\n"
+      "#define HAVE_CMOV\n"
+      "#define HAVE_MMX\n"
+      "#define HAVE_SSE\n"
+      "#define HAVE_SSE2\n"
+      "#define HAVE_SSE3\n"
+      "#define HAVE_SSSE3\n")
+      set(SGEMM_UNROLL_M 8)
+      set(SGEMM_UNROLL_N 4)
+      set(DGEMM_UNROLL_M 4)
+      set(DGEMM_UNROLL_N 4)
+  elseif ("${TCORE}" STREQUAL "ARMV7")
     file(APPEND ${TARGET_CONF_TEMP}
       "#define L1_DATA_SIZE\t65536\n"
       "#define L1_DATA_LINESIZE\t32\n"
```

**Comment by crayroud-nviso** [comment]
Thanks for the patch.

I had to add the following to the patch:

```
+      set(CGEMM3M_UNROLL_M 4)
+      set(CGEMM3M_UNROLL_N 4)
+      set(ZGEMM3M_UNROLL_M 4)
+      set(ZGEMM3M_UNROLL_N 4)
```

What are the correct values ?

**Comment by martin-frbg** [comment]
Ah, sorry, the patch is actually lacking the M,N values for CGEMM and ZGEMM - 
```
#define CGEMM_DEFAULT_UNROLL_M 4
#define ZGEMM_DEFAULT_UNROLL_M 2
#define CGEMM_DEFAULT_UNROLL_N 2
#define ZGEMM_DEFAULT_UNROLL_N 2
```
in the absence of specific unroll factors for the xGEMM3M functions, the values for the corresponding xGEMM functions are substituted (in common_param.h) 
Also all these numbers are for 64bit, I probably need to expand it to cover the ARCH_X86 case as well).
