### ISSUE TITLE
openblas 0.3.7 fails to build with GCC 10 on x86 and x86_64 architectures

### ISSUE THREAD

**Issue by susilehtola** [xianyi/OpenBLAS#2382]
OpenBLAS 0.3.7 fails to build on Fedora rawhide on x86_64 and x86_64 architectures, presumably due to GCC 10.

Failing build log for x86_64:
https://kojipkgs.fedoraproject.org//work/tasks/6767/41216767/build.log
The package log
https://kojipkgs.fedoraproject.org//work/tasks/6767/41216767/root.log
shows that the build failed with GCC package version 10.0.1-0.6.fc32

The identical package built in December with GCC 9.2.1:
https://kojipkgs.fedoraproject.org//packages/openblas/0.3.7/2.fc32/data/logs/x86_64/build.log
https://kojipkgs.fedoraproject.org//packages/openblas/0.3.7/2.fc32/data/logs/x86_64/root.log

**Comment by susilehtola** [comment]
Or well, it builds but the cblat1 test fails due to `Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`

**Comment by martin-frbg** [comment]
Does current `develop` build ? I checked that two days ago with current gcc development branch due to #2377 and did not see a failure on SkylakeX that uses the same cdot(c). (The x86_64 cdot.c is unchanged from 0.3.1 and its Haswell microkernel only got a fairly benign update in 0.3.7)

**Comment by susilehtola** [comment]
Nope, same problem
https://kojipkgs.fedoraproject.org//work/tasks/4043/41334043/build.log

**Comment by martin-frbg** [comment]
I just redid the gcc10 build on an AMD Ryzen and did not encounter any problem with their current version from git. Given that gcc10 has not been released (and still appears to be at least 10 P1 problems away from their release criteria) I am inclined to label this a bug in the fedora gcc snapshot.

**Comment by martin-frbg** [comment]
Given https://github.com/xianyi/OpenBLAS/issues/2379#issuecomment-581211388 you could also try to check & increase the stack size limit in your build environment (ulimit -s)

**Comment by susilehtola** [comment]
also fails with `ulimit -s unlimited`
https://kojipkgs.fedoraproject.org//work/tasks/8087/41348087/build.log

**Comment by derics** [comment]
Hello,
Is this still an issue for you?  Do you have any recent failed build logs?  The links you provided above for the failed builds don't seem to be valid any more.  I had a similar issue this week using the dev openblas and the dev gcc 10.
Thanks,Deric

**Comment by martin-frbg** [comment]
@derics can you be more specific please ? (I cannot completely exclude some differences in build options for either gcc or openblas between my tests and fedora, though I do not remember seeing any back in february). Is "dev gcc 10" still the same snapshot as what fedora had at that time (my checkout was most probably newer) ?

**Comment by derics** [comment]
Hi Martin, I was just wondering if Susi was still having the issue and if he could provide newer links for the failed build output.  From that output, I was going to see if it was the same problem that I was having.  I cloned my gcc 10 this week, so I don't think it was the same one that Susi was using.  However, it's possible that the root of the problem was the same.  Or it's possible that they are not at all related.

My issue took a while to debug but was easy to fix once I realised what was going on.  I'm in a Ubuntu 18.04 environment where the default gcc (and gfortran) are not version 10.  I have installed and compiled gcc 10 in my own directory.  I was using PATH, LIBRARY_PATH, and LD_LIBRARY_PATH to build and run using gcc 10.  However, gcc dev from source does not produce a binary called "cc".  My distribution seems to add the "cc" binary and it's a link to /usr/bin/gcc.  Since the openblas install defaults to cc, openblas did not find "cc" in my dev gcc part of the PATH, so it then went to /usr/bin/cc which linked to /usr/bin/gcc.  This caused the c_check perl script to generate the linker "-L" options incorrectly.  Then the test programs (e.g. sblat1.f) were linked to the wrong libgfortran.so.  The solution for me was simple: add "CC=gcc" before the openblas make command (or I suppose I could have added my own link from cc to gcc in the gcc version 10 directory).

**Comment by martin-frbg** [comment]
Yeah defaulting to "cc" that is not a gcc-provided symlink is a property of (at least GNU) make. So just relying on PATH priority to get the desired version of gcc called is unsafe, and mixing different versions of gcc and gfortran is known to lead to crashes.

**Comment by susilehtola** [comment]
Hi, sorry I forgot to close this; I think this was fixed in 0.3.8, at least since then all builds have succeeded in Fedora rawhide, i.e. first the upcoming f32 release branch, and now the f33 development branch. For instance, the f33 build of 0.3.9 is here https://koji.fedoraproject.org/koji/buildinfo?buildID=1472597 which, according to the logs, has been built with gcc package version 10.0.1-0.8.fc33. As to what this means in upstream gcc, I'm not sure: Red Hat employs several gcc core developers, and the gcc packages in rawhide tend to be bleeding edge with the developers' hand picked patches.
