### ISSUE TITLE
How to compile against DYNAMIC_ARCH ?

### ISSUE THREAD

**Issue by Guobing-Chen** [xianyi/OpenBLAS#2388]
Anyone can help share how to build openBLAS with DYNAMIC_ARCH as build target? When I do this it tells me that this target is not supported.

**Comment by martin-frbg** [comment]
DYNAMIC_ARCH is not a target in itself, but an additional option, you would use something like
`make TARGET=NEHALEM DYNAMIC_ARCH=1` to add support for a range of old and new cpus with all common code built for the older Nehalem instruction set.

**Comment by Guobing-Chen** [comment]
Thanks for quick answer, Martin. Does this 'make TARGET=NEHALEM DYNAMIC_ARCH=1' mean to build all the supported kernels (nehalem version, haswell version, skylake version, etc.) into one binary, and this binary can be run on all supported platforms (CPUs) with the right version kernel to be automatically loaded on the right platform? Any limitation to use DYNAMIC_ARC=1 ?

**Comment by Guobing-Chen** [comment]
To be more clearly, can 'DYNAMIC_ARCH' support the behavior like: build openBLAS as one binary, this binary can automatically load the best optimized kernel on a specific platform(CPU) based on runtime detection of platform features, e.x.: load AVX512 based kernel on a skylakeX platform, load AVX2 based kernel on a haswell platform.

**Comment by martin-frbg** [comment]
Yes, that is exactly what DYNAMIC_ARCH is for.

**Comment by Guobing-Chen** [comment]
Great! Then is 'DYNAMIC_ARCH=1' recommended as default option? I don't see this option to be introduced in README or other official docs for openBLAS. Are there any drawbacks to enable this option?

**Comment by martin-frbg** [comment]
Obviously the library will get bigger. The option is mentioned in the old GotoBLAS_02Quickinstall.txt and in Makefile.rule, I have to agree that documentation could be better.

**Comment by Guobing-Chen** [comment]
Emm... make sense as a bigger size binary, to me it is not a big issue generally. I will have a try to evaluate this option more. Thanks much for all the information.

**Comment by martin-frbg** [comment]
Historically (OpenBLAS continues the original GotoBLAS work from about 2002-2010), there never was much documentation so users got used to reading the Makefiles - certainly not an ideal situation.
Most options are described in Makefile.rule, lists of the cpu models supported by DYNAMIC_ARCH on the various architectures can be found in Makefile.system. For x86_64, this contains Prescott, Core2, Nehalem, Barcelona, Sandybridge, Bulldozer, Piledriver, Steamroller, Excavator, Haswell, Zen, SkylakeX. If you also specify DYNAMIC_OLDER=1, specific support for Penryn,Dunnington,
Opteron, Opteron/SSE3, Bobcat, Atom and Nano is added. Finally there is an option DYNAMIC_LIST that allows to specify an individual list of targets to include instead of the default.
DYNAMIC_ARCH is also supported on x86, ARMV8, POWER and ZARCH but it is not possible to
combine support for different architectures in one library.

**Comment by cesss** [comment]
Wow... some months ago I discarded using OpenBLAS just because by reading the build instructions I thought that you really had to build for a specific CPU (something I can't do, because I have a range of CPUs, from Core2 Duo to i9 Coffee Lake, all of them sharing the same binaries, and managing a different OpenBLAS build for each CPU was unreasonable).

I'm writing this comment just to show how important is to properly document this feature very clearly, as people can discard OpenBLAS thinking that choosing proper CPU optimizations at runtime is not supported.
