### ISSUE TITLE
What happens when OMP_NUM_THREADS is not set? (for an OpenMP build)

### ISSUE THREAD

**Issue by cesss** [xianyi/OpenBLAS#2394]
I have built OpenBLAS with OpenMP, and with NUM_CORES=12 which is the maximum I have across my machines.

Now, the docs tell I should define OMP_NUM_THREADS... but, let's suppose I don't define it and I run the code on a CPU with 4 native threads... will it use 12 threads, or will it ask the OpenMP implementation to get the recommended number of threads for the system?

If OMP_NUM_THREADS must be really set, I suggest to change that behavior, because if the user didn't set OMP_NUM_THREADS, the expected behaviour would be to use the max number of threads for the system rather than the NUM_CORES value, which might be non-optimal for the system.

**Comment by martin-frbg** [comment]
OpenBLAS queries the hardware on startup, so on the system with only four cores available it will not start more than 4 threads. The NUM_CORES (or NUM_THREADS) is a hard maximum however, so on a machine with 48 cores your build of the library would only ever use part of the cpu. (I am not aware of an OpenMP function to query a "recommended" number of threads rather than the maximum available ?)

**Comment by cesss** [comment]
Thanks a lot for clarifying it!!

And, yep, the "recommended" bit was the best word that came to my mind, because I didn't like to say "maximum", as you can create much more threads than the CPU can natively support... but yes, I should have said "maximum", in this context it would be correctly understood.
