### ISSUE TITLE
[s/d/c/z]gemm performance degradation with big matrices on ARM with TARGET specified

### ISSUE THREAD

**Issue by mistomin** [xianyi/OpenBLAS#2446]
I see about 2-3% performance degradation in gemm (m=n=k=4096) on single thread.
The bug was introduced in #2267 (so it appears in 0.3.8 and not present in 0.3.7 release)
The problem is when I build with TARGET=TSV110, it defines `FORCE`, so `NUM_CORES` is not defined and we fall into path with small GEMM_DEFAULT_P/Q/R parameters.

I guess we can not use get_cpucount() functions when TARGET is specified, so maybe we should use previous P/Q/R parameters (that was used before #2267) as default ones?

**Comment by martin-frbg** [comment]
Reverting #2267 would reintroduce the performance problem on smaller devices - IIRC ashwinyes' recommendation from that ticket was to drop the test and make the _smaller_ parameters the default on all platforms. Perhaps it would make more sense to limit the change to the more ubiquitous Cortex cpus, and simply assume that anything with a TSV110 (or ThunderX, Ampere,... but these are not affected by this conditional setting anyway) falls in the server category ?
On the other hand, why do you need to specify the TARGET instead of letting it get detected - is there another cpu id that would need to be added in cpuid_arm64.c (assuming you could disclose that) ?
