### ISSUE TITLE
gmsh compilation

### ISSUE THREAD

**Issue by hbadi** [xianyi/OpenBLAS#2719]
Hi everybody,

I want to compile (with visual studio) gmsh with the static lib openblas/lapack (gmsh need these two lib for meshing).
First I success to get openblas.lib and lapack.lib. Do i need to link with other libs like kernel.lib, interface.lib, driver_level2.lib, driver_level3.lib ?

But during the linking stage of gmsh some lapack functions are still unresolved (dgetri, dgesvd,dgeev,dlaswp_ncopy). Those functions are defined in fullMatrix.cpp as extern but with a strange macro F77NAME, i don't know if it's ok for msvc, and how they could be resolved.

Any advices ?

Best regards.

**Comment by martin-frbg** [comment]
You will need a fortran compiler for building the LAPACK part (which OpenBLAS imports from the "netlib" reference implementation, still written in fortran). dlaswp_ncopy however should be defined in your openblas.lib. (Though maybe I misunderstood - have you compiled the openblas.lib/lapack.lib yourself or obtained it as binaries from somewhere ?)
Have you tried the gmsh mailing list ? It is years since I last used gmsh, and I only ever built it on Linux

**Comment by hbadi** [comment]
Thanks Martin,
I compiled openblas/lapack myself. As i need a fortran compiler i can't compile the whole openblas with msvc ?
I just tried the gmsh forum and i got the same answer : i need a fortran compiler...
Something is strange is the gmsh code cause blas functions are prefixed by `#define F77NAME(x) (x##_)` witch will out `dgetri_` instance, but openblas define dgetri as follow : 
`#define LAPACK_dgetri LAPACK_GLOBAL(dgetri,DGETRI)
void LAPACK_dgetri`

that's not the same resolving name ?

**Comment by martin-frbg** [comment]
Yes, without fortran the library will only contain the BLAS functions. And MSVC alone is a non-ideal choice anyway as the microsoft compiler does not handle the inline assembler code present in most of the optimized BLAS kernels, so only a less performant plain C version of these gets used instead. The wiki has some instructions for compiling with either mingw or clang/flang. and a binary package cross-compiled on Linux is available on the Releases page
EDITED to add: both prefixes should expand to the same dgetri_ I think

**Comment by brada4** [comment]
I think you must pass binary openblas dll somewhere in the build tree undet other name so that they link it to final executable.
It can be crosscompiled outside visual studio.

they could kindly make windows binaries on par with linux ones with external lapack/blas libs so that one in your position can replace them with OpenBLAS or MKL without massive rebuild at home.

Indeed import tables shows absolute need for lapack, so pure VS-only build will not do.
```
liblapack.so.3 =>
daxpy_,dgesv_,zaxpy_,dgeev_,dgemm_,zgemm_,dgemv_,zgemv_,dgetrf_,dgetri_,dgetrs_,dgesvd_,dscal_,zscal_,dcopy_,zcopy_
```
