### ISSUE TITLE
loongson cross compile failed with dgemm_r undefine

### ISSUE THREAD

**Issue by xinyu391** [xianyi/OpenBLAS#2723]
loongson gcc toolchains 
http://ftp.loongnix.org/toolchain/gcc/release/mips-loongson-gcc7.3-2019.06-29-linux-gnu.tar.gz

>> make BINARY=64 CC=mips-linux-gnu-gcc FC=mips-linux-gnu-gfortran HOSTCC=gcc TARGET=LOONGSON3A

```
mips-linux-gnu-gcc -O2 -DMAX_STACK_ALLOC=2048 -Wall -mabi=32 -march=mips64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.10\" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=dgemm_tt -DASMFNAME=dgemm_tt_ -DNAME=dgemm_tt_ -DCNAME=dgemm_tt -DCHAR_NAME=\"dgemm_tt_\" -DCHAR_CNAME=\"dgemm_tt\" -DNO_AFFINITY -I../.. -DDOUBLE  -UCOMPLEX  -c -DDOUBLE -UCOMPLEX -DTT gemm.c -o dgemm_tt.o
In file included from ../../common.h:558:0,
                 from gemm.c:40:
level3.c: In function 'dgemm_nn':
../../param.h:2431:25: error: 'dgemm_r' undeclared (first use in this function); did you mean 'dgemm_'?
 #define DGEMM_DEFAULT_R dgemm_r

```

**Comment by martin-frbg** [comment]
Thanks for the link, I am downloading to check this. Not immediately aware of any recent changes that could be causing this, but Loongson3A has not received much attention in the years since initial support for it was added. If you are in a hurry to get started, building with TARGET=GENERIC should work

**Comment by xinyu391** [comment]
the compiler is  mips64.
but  in getarch.c
```c
#ifdef FORCE_LOONGSON3A
#define FORCE
#define ARCHITECTURE    "MIPS"
#define SUBARCHITECTURE "LOONGSON3A"
#define SUBDIRNAME      "mips64"
```
it trate LOONGSON3A  as mips.
I think this is the reason.

**Comment by martin-frbg** [comment]
Reproduced it, but have not found the source of the problem yet. Definitely broken since before 0.2.20, as a temporary workaround you can change the "dgemm_r" near line 2440 of param.h to 200 (but for me it then crashes with a supposedly unsupported assembler instruction `rdhwr`, apparently from the rpcc function declared in common_mips64.h). There have been doubts for some time if the Loongson3 code still compiles, Loongson even offered to provide hardware for testing but unfortunately the pandemic has interfered since.

**Comment by martin-frbg** [comment]
~Hm. actually I suspect now that this is "only" a 32 bit toolchain (from the compiler defines visible with `gcc -E -dM`) ?~
Seems you need to specify CC as `CC=/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/mips-linux-gnu-gcc -mabi=64' to
make sure that the build system sees the compiler as 64bit-capable.

**Comment by martin-frbg** [comment]
`make HOSTCC=gcc CC='/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/mips-linux-gnu-gcc -mabi=64' FC='/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/mips-linux-gnu-gfortran -mabi=64' TARGET=LOONGSON3A`

works without any code changes (i.e. the -mabi=64 needs to be added to the FC as well to avoid a link error in the ctests).

**Comment by martin-frbg** [comment]
Updated the example given in README.md accordingly
