### ISSUE TITLE
OpenBLAS with Intel compiler & Windows

### ISSUE THREAD

**Issue by hbadi** [xianyi/OpenBLAS#2746]
Hi,

Does anyone succeeded to compile OpenBLAS with Intel Compiler on windows 10 with cmake ?
I use the cmake gui to configure and generate the MSVS 2017 solution but it seems that it does not contain the fortran part of openblas even if i specify the c/c++/fortran intel exe compiler path.

Best regards.

PS : Where can i download the binaries ?

**Comment by martin-frbg** [comment]
#2472 had some notes and IIRC it finally compiled with the patches developed in the context of this issue.
The precompiled binaries (cross-compiled on Linux) for 0.3.10 are on the Releases page underneath the version news

**Comment by hbadi** [comment]
Ok, great i didn't see the binary files. That's works fine with native msvc compiler. With which compiler was compiled the binary release ? I'll try to compile by myself with the intel compiler.

Thanks.

**Comment by martin-frbg** [comment]
Binary release was compiled with MXE (which provides a mingw-w64 derivative of gcc/gfortran 5.5.0)

**Comment by dbyoung720** [comment]
I uses Intel fortran  on windows 10 with cmake compile lapack successed.
same way , compile openblas 
error:
 [5868/14696] 
  OpenBLAS/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression 
  OpenBLAS/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
  OpenBLAS/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size

[OpenBlas.zip](https://github.com/xianyi/OpenBLAS/files/5010225/OpenBlas.zip)

**Comment by dbyoung720** [comment]
I use intel fortran on windows10 cmake compile lapack successed.
same way, compile openblas error.

[5734/14696] Building C object driver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\dsyrk_kernel_L.c.obj
FAILED: driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/dsyrk_kernel_L.c.obj
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo  -I..\..\ -I. /DWIN32 /D_WINDOWS /W3  -DDYNAMIC_ARCH -DNO_AVX -DSMP_SERVER -DMAX_CPU_NUMBER=12 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.10.dev\"" /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fodriver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\dsyrk_kernel_L.c.obj /Fddriver\level3\CMakeFiles\driver_level3.dir\ /FS -c driver\level3\CMakeFiles\dsyrk_kernel_L.c
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size

[5737/14696] Building C object driver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\csyrk_kernel_U.c.obj
FAILED: driver/level3/CMakeFiles/driver_level3.dir/CMakeFiles/csyrk_kernel_U.c.obj
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe  /nologo  -I..\..\ -I. /DWIN32 /D_WINDOWS /W3  -DDYNAMIC_ARCH -DNO_AVX -DSMP_SERVER -DMAX_CPU_NUMBER=12 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.10.dev\"" /MD /O2 /Ob2 /DNDEBUG /showIncludes /Fodriver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\csyrk_kernel_U.c.obj /Fddriver\level3\CMakeFiles\driver_level3.dir\ /FS -c driver\level3\CMakeFiles\csyrk_kernel_U.c
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2057: expected constant expression
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2466: cannot allocate an array of constant size 0
E:/Source/OpenBLAS/driver/level3/syrk_kernel.c(65): error C2133: 'subbuffer': unknown size
[5738/14696] Building C object driver\level3\CMakeFiles\driver_level3.dir\CMakeFiles\csyrk_kernel_L.c.obj

[OpenBlas.zip](https://github.com/xianyi/OpenBLAS/files/5010248/OpenBlas.zip)

**Comment by martin-frbg** [comment]
That error message suggests that the parameter GEMM_UNROLL_MN is not defined for your cpu, which "should not happen". What kind of hardware (cpu model) are you building OpenBLAS with ?

**Comment by dbyoung720** [comment]
![Untitled](https://user-images.githubusercontent.com/11304997/89103426-768c6b00-d444-11ea-8e11-67acd2f57fde.png)

**Comment by martin-frbg** [comment]
I cannot reproduce this on Linux, and cannot explain it unless VS fails to run the C preprocessor on the affected files at all (maybe there is a project paramert in VS that needs to be set to achieve this). (The SGEMM_UNROLL_MN etc. are defined in common_param.h as the maximum of the corresponding M and N parameter unless a dedicated MN was given in param.h. In the syrk_kernel.c file , "subbuffer" is declared as `subbuffer[SGEMM_UNROLL_MN * SGEMM_UNROLL_MN]` )

**Comment by dbyoung720** [comment]
Yes, I looked at the configuration parameters.
I want to know, under vs, which value should I set?
Viewing files in cmake directory.

**Comment by dbyoung720** [comment]
WIN10(2004) compile openblas, The tests are as follows:

mode 1 :
  Ninja + VS2017 + Intel fortran 2020.2.254 + CMake
  -DBUILD_WITHOUT_LAPACK=OFF -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON
  Build error. 
  lapack_netlib participate in compile
[1.zip](https://github.com/xianyi/OpenBLAS/files/5054574/1.zip)

mode 2 :
  VS2017 + Intel fortran 2020.2.254 + CMake
  -DBUILD_WITHOUT_LAPACK=OFF -DNOFORTRAN=0 -DDYNAMIC_ARCH=ON
  CMake automatically searches for fortran compilers installed on the machine
  No need to specify fortran compile location manually.
  CMake test fortran compile is success, but lapack_netlib do not participate in the compilation
  Build error.  (as above + any other)
[2.zip](https://github.com/xianyi/OpenBLAS/files/5054576/2.zip)

  -DBUILD_WITHOUT_LAPACK=OFF -DNOFORTRAN=0 -DDYNAMIC_ARCH=OFF
  lapack_netlib do not participate in the compilation
  Success generation openblas.lib(MT compile)
  But openblas_utest build error
[3.zip](https://github.com/xianyi/OpenBLAS/files/5054582/3.zip)


relapack，can not be compiled in either mode


Conclusion: in WIN10(2004), with Intel fortran, openblas cannot be compiled due to the problem of writing openblas script.

**Comment by martin-frbg** [comment]
The error in 3.zip is the same as at the start of  #2472 - the build system "thinks" it built the fortran files in lapack-netlib so it tries unsuccessfully to use them in the openblas_utest. Also from #2472 it is probably safe to assume that ninja is needed for proper linking of mixed-language builds. So that brings us back to the question why your installation (apparently) does not run the preprocessor to do parameter substitution on the C files. Can you try with adding `-DTARGET=NEHALEM` to the cmake options (just in case the -DNO_AVX caused some problem with cpu detection) ?

**Comment by dbyoung720** [comment]
Add -DTARGET=NEHALEM, the problem remains
Error is the same as above

**Comment by isuruf** [comment]
It looks like you are using Visual studio compiler as the C/C++ compiler and Intel Fortran as the Fortran compiler. You should use the Intel compiler as the C/C++ compiler.

**Comment by MitsuhaMiyamizu** [comment]
what @isuruf said is correct, you cannot use ```ifort``` with MSVC, the ABI of MSVC is definitely not compatible with that of ```ifort```, according to my own experience, I've tested a mixed C/Fortran code, only ```icc``` and ```ifort``` can handle this, it's better to use Intel C/C++ Compiler with Intel Fortran Compiler.

**Comment by martin-frbg** [comment]
Thank you both, I've added a note to the top of the wiki page about compilation in Visual Studio now.
