### ISSUE TITLE
cblas.h:30:61: error: unknown type name 'cpu_set_t'; did you mean 'sigset_t'?

### ISSUE THREAD

**Issue by mshadian** [xianyi/OpenBLAS#2763]
I get this error while building a project which uses OpenBLAS. Any ideas?!

**Comment by martin-frbg** [comment]
Does adding an`#include <sys/resource.h` help ?

**Comment by brada4** [comment]
cpu_set manual says `#include <sched.h>` and OpenBLAS source code does that already.

**Comment by martin-frbg** [comment]
@mshadian can you be more specific about the build environment please ? The cpu_set_t parts are only used on Linux, where I believe they should be available in both glibc and uClibc

**Comment by martin-frbg** [comment]
A possibility could be that you used the "raw" cblas.h from the build directory, rather than the processed copy that a `make install` would produce in the installation directory. Does the cblas.h that you used include "common.h" or openblas_config.h ?
The former is only used during the build of OpenBLAS itself, the latter has several build-time defines added, including the information that it is a Linux build (OPENBLAS_OS_LINUX) which triggers the automatic inclusion of sched.h
