### ISSUE TITLE
Missing dependency in pkg-config file when using openmp

### ISSUE THREAD

**Issue by TimoRoth** [xianyi/OpenBLAS#2789]
When statically linking against libopenblas.a:

```
libopenblas.a(cblas_daxpy.o): in function `num_cpu_avail':
axpy.c:(.text+0x21): undefined reference to `omp_in_parallel'
...
```
Followed by a whole bunch of similar errors.

This is fixed by adding -lgomp to the linker commandline, however that library is not listed in the pkg-config file for openblas, which is what's being used for this build.

I'm using the latest Version, 0.3.10, of openblas.

**Comment by martin-frbg** [comment]
Probably caused by 
https://github.com/xianyi/OpenBLAS/blob/9ee21a0a39fe5e0ba178b6dce2ba8b71e4dc2dc6/c_check#L335
(which removes openmp from the libraries line in an effort to work around a problem in the PGI compiler.
I thought I had already made that depend on the compiler name, but apparently I only applied the change to the corresponding f_check script.
EDIT: no - unrelated. I can force adding it to the pkgconfig file but admit I am a bit confused why this has not come up before.
The cmake-generated openblas.pc does not even spell out the "EXTRALIB" dependencies that the make-generated onehasg-
So is a pkg-config file required to name additional dependencies or not ?
