### ISSUE TITLE
Regarding OpenBLAS behavior with OpenMPI on HPL benchmark

### ISSUE THREAD

**Issue by nervermore2** [xianyi/OpenBLAS#2818]
Currently I'm using OpenBLAS together with OpenMPI for HPL benchmark. I've seen issues discussing about setting the OpenBLAS to be single-threaded to avoid conclifts with OpenMPI, however, I've also seen on issue talking about HPL program has its own copy per node, so that multi-threaded OpenBLAS would conflict with OpenMPI when doing HPL benchmark. I'm wondering if anyone has any recommendations about if I should set the num_thread = 1?
I'm asking this since I found sometimes when compiling OpenBLAS, sometimes multiple nodes causes very slow performance when running the benchmark. Most of the time my program is being held with schedule_yield. I'm just wondering if anyone has same experience.

**Comment by nervermore2** [comment]
Also another weird behavior is, I think HPL use LAPACK, which we need to build it with gfortran. However, when I install OpenBLAS with gcc 7.2.1 with gfortran 6.4.1, probably due to imcompatible version, OpenBLAS outputs `ldgfortran cannot be found`. However, I still was able to run it with HPL and get a very high result (much higher than others with correct output). 
In contrast, if I build with gcc 6.4.1 with gfortran 6.4.1. OpenBLAS outputs everything correctly, however, I was stucked in the schedule_yield. Anyone have any idea why this is happening? Both are using `make FC=gfortran` only. No other parameters are used.

**Comment by nervermore2** [comment]
##Update##
`with gcc 6.4.1 with gfortran 6.4.1. with numthreads = 72`, My performans is really bad due to schedule_yield. However, if I set numthead=1, then my performances approches the one I compiled with gcc 7.2.1 and gfortran 6.4.1. However, I'm still confused why OpenBLAS gives great results for my HPL program even if LAPACK is not installed.
In addition, does anyone know if gcc version affect performance? For instance, does gcc 7.2.1 has better performance than compiling with gcc 6.4.1 or 4.8.5?

**Comment by martin-frbg** [comment]
Use the exact same versions of gcc and gfortran - your mixed build probably did not even load due to the missing libgfortran, or may have crashed due to ABI differences. Use single-threading if you see MPI interfering with threads. If I remember correctly, HPL uses BLAS but no LAPACK so building without a fortran compiler should be fine - you can certainly look that up. Performance with newer compilers _should_ in general be better (improved optimizations, added support for recent cpu models) but of course it will depend on your hardware how much of an improvement you will see.

**Comment by nervermore2** [comment]
Thanks!
