### ISSUE TITLE
Add a Roadmap

### ISSUE THREAD

**Issue by twmr** [xianyi/OpenBLAS#2861]
Since OpenBLAS received a grant last year, it would be nice if it were
documented what has already been achieved due to the grant and what
users/developers can still expect in the next months/years.

**Comment by brada4** [comment]
Would you , please, be so kind, and provide reference for any grant received, as it stands currently, does not ring pockets.

**Comment by martin-frbg** [comment]
My work on OpenBLAS is currently funded (_in part_) by a fraction of a CZI grant received by the NumPy project (and managed by NumFOCUS). I am not sure if it makes sense to publish a roadmap as it was largely soft targets that were agreed upon rather than particular new features, and as far as I know NumPy has not published any roadmap or committments specifically related to that grant either. In this sense I am working as an independent contractor for NumFOCUS on behalf and at the suggestion of the NumPy project.

**Comment by twmr** [comment]
I read about the grant here: https://labs.quansight.org/blog/2019/11/numpy-openblas-CZI-grant/

**Comment by martin-frbg** [comment]
Not much to add to that blog post (especially since it links to the full proposal) except that my actual payment is a bit lower than the sum mentioned there, and the grant covers just that single year (with a proposal for an extension submtted AFAIK)
