### ISSUE TITLE
-mavx2 not set when compiling with Flang

### ISSUE THREAD

**Issue by dnoan** [xianyi/OpenBLAS#2917]
It is very nice to see Clang/Flang support in version 0.3.11. I just tried building with Clang/Flang 10 and it worked fine. I haven't tested how it runs yet but I noticed that the Fortran code was compiled without `-mavx2` (on Zen). Is this by design? Adding `-mavx2` for Flang in `Makefile.x86_64` and then compiling worked fine.

**Comment by martin-frbg** [comment]
Not really by design - "historically" the build system did not add cpu-specific compiler flags on its own except where absolutely necessary. This could probably be improved.
Note that a few ugly bugs have surfaced in the last couple of hours - your shared library will probably be missing all double precision complex functions right now, see #2909 for the trivial fix.
