### ISSUE TITLE
Compilation error in driver/others/memory.c  on solaris

### ISSUE THREAD

**Issue by anaswain** [xianyi/OpenBLAS#2945]
Hello Experts,
I am facing issue while compiling OpenBLAS 0.3.11 on Solaris SPARC.
Get the following error in driver/others/memory.c.
"memory.c", line 1770: undefined symbol: cpu_set_t
"memory.c", line 1770: syntax error before or at: cpuset
cc: acomp failed for memory.c

Is OpenBLAS supported on Solaris?
If yes any suggestion to fix this would be appreciated.

Thanks,
Ananta

**Comment by anaswain** [comment]
1706 int get_num_procs(void) {
   1707   static int nums = 0;
   1708
   1709 cpu_set_t *cpusetp;    
   1710 size_t size;
   1711 int ret;
   1712 int i,n;
   1713
   1714   if (!nums) nums = sysconf(_SC_NPROCESSORS_CONF);
   1715 #if !defined(OS_LINUX)
   1716      return nums;
   1717 #endif

From the code it looks like line 1709 is intended only for Linux because other OS return at line 1716.

**Comment by martin-frbg** [comment]
Fairly certain this used to work, and I believe there were no recent changes in that part of the code. The early return at line 1716 is for systems that are not expected to use the GNU libc, everything after that depends on varying levels of support for cpu affinity in particular versions of the glibc.
Which version of Solaris is that  ? I do not have local hardware, but can test on Solaris 10 or 11 in the gcc compile farm.

**Comment by martin-frbg** [comment]
Could/Should probably move the declarations inside the `#if defined(GLIBC_PREREQ)` a few lines below. BTW what compiler are you using ?

**Comment by anaswain** [comment]
Hi,
It is solaris 11.3. And using cc compiler from solaris studio 12.6.

**Comment by martin-frbg** [comment]
Moving the declarations (#2946) seems to fix it, but I am now getting an error in the LAPACK fortran code - f90 claiming that MAXLOC is not a valid intrinsic. Not sure what to make of that - it would break Reference-LAPACK as well - maybe just a missing compiler flag or I have the wrong flavor of "f90" in the path on that system.

**Comment by martin-frbg** [comment]
BTW please update to 0.3.12 (or use the current `develop` branch from github)  if you can, 0.3.11 had some nasty bugs unfortunately.

**Comment by martin-frbg** [comment]
Apparently need FC=f95 to get around the MAXLOC intrinsic error

**Comment by anaswain** [comment]
Thanks Martin.

I could get around the memory.c issue now. But facing an issue later in
fortran code while buildiling OpenBLAS-0.3.5/lapack-netlib/SRC

gfortran -O2 -Wall -frecursive -m32 -m64 -fPIC -c -o sgbsv.o sgbsv.f
gfortran: error: may not use both -m32 and -m64

Found that make.inc file having the wrong options. And this file is created
on the fly.
Any idea which file can I modify to get proper make.inc and which is
correct flag to use - m32 or m64?

**Comment by martin-frbg** [comment]
I do not know the OS and compiler setup in Solaris, but if type of binary is misdetected from the default compiler settings you can specify BINARY=32 or BINARY=64 on the `make` command line. (In your case, probably the C compiler from Solaris Studio was found to be 32bit by default, and the gfortran compiler 64bit - which does look a bit strange.
Are you actually building 0.3.5 now, which is quite old ?

**Comment by martin-frbg** [comment]
Reopening this as there appear to be more issues with Solaris Studio builds - my own build attempts with Solaris Studio 12.4 may be flawed by not knowing if my compiler environment is set up correctly (using a gcc buildfarm machine for this) - I have added the "bin" directory of the solarisstudio12.4 installation to my PATH, and also added /usr/ccs/bin which contains ar and ranlib. (And set LD_LIBRARY_PATH to point to the solarisstudio12.4/lib)

First issue is the Solaris Studio `cc` choking on a C++-style comment in param.h (claiming syntax error for unsupported command "Common" in amax.S), second is that functions get a verbatim "NAME" or "CNAME" symbol due to the `-UNAME -UCNAME` in Makefile.system (which was a known and handled problem for the PGI compiler already)

With that out of the way, the tests fail to link although `nm` and `gnm` both show all the "missing" symbols to be present in 
the static library. (Possibly the library is part 32bit or something weird like that ?) I will prepare a PR for the solved issues of course, can you comment on environment settings or compiler options necessary for working with solaris studio ?
EDIT: 32/64bit compiler mess caused by makefile entries that were for added for using the Sun compiler on x86.With that out of the way, the dot kernels and c/zswap all return wrong results at least when compiled with solarisstudio12.3, and there are a bunch of segmentation faults in the lapack testsuite. Seems the sparc code has not been built in a while.

**Comment by anaswain** [comment]
Hi Martin,

I have some queries on OpenBLAS supported OSes.
1- Is it supported on HP-UX on itanium 64bit?
2- If so is gfortran mandatory or we can use other native fortran compiler
available with hp-ux.
3- Can I use gcc instead of native cc for openBLAS compilation? cc on hp-ux
giving problem with inlined assembly code. It is not  recognizing "asm".

Thanks and Regards,
Ananta

**Comment by martin-frbg** [comment]
Hi Ananta,

a difficult question - Itanium used to be supported in the original GotoBLAS more than ten years ago so the code is still there, but I do not have access to any such system and I do not know if anybody ever tried to compile OpenBLAS on Itanium since then.
gcc is probably required for the inline assembly, but the fortran code (which is basically just the "netlib" Reference-LAPACK) should compile with any native fortran compiler that supports at least fortran90.

**Comment by anaswain** [comment]
Hi Martin,

I got the list of supported OS in the "GotoBLAS_01Readme.txt" file. HP-UX
is not listed there, does that mean HP-UX is not supported?


1. Supported OS

     Linux
     FreeBSD(Also it may work on NetBSD)
     OSX
     Soralis
     Windows 2k, XP, Server 2003 and 2008(both 32bit and 64bit)
     AIX
     Tru64 UNIX

Thanks,
Ananta

**Comment by martin-frbg** [comment]
Essentially correct - that list is from the original GotoBLAS2 as well, but we do not mention HP-UX in the newer README.md either.
My last contact with HP-UX was some ten years before I became involved with OpenBLAS. From what I remember I would not expect major difficulties when compiling OpenBLAS (at least with gcc and related GNU tools installed - the "cc" compiler from hp was quite bad) but I have no means of trying it myself now.

**Comment by martin-frbg** [comment]
Hm. I stumbled upon a cmake issue thread involving HP-UX/ia64 at https://gitlab.kitware.com/cmake/cmake/-/issues/17137 and while cmake has much more demanding requirements (C++ 11) than OpenBLAS, the whole thread does not look encouraging.
Seems people cannot even get a somewhat recent gcc to build, and run into linker bugs even with the old versions that can be built. Anyway the "Itanium" support from GotoBLAS2 can be Itanium2 at best, given how long ago it was written.
