### ISSUE TITLE
MMPERF - single core matmul performance benchmark

### ISSUE THREAD

**Issue by s-trinh** [xianyi/OpenBLAS#3112]
This is not an issue, but rather a link that could be interesting for the OpenBLAS community:
- [MMPERF - single core matmul performance benchmark](https://mmperf.org/)

**Comment by martin-frbg** [comment]
Thanks for the pointer, this does look interesting indeed.

**Comment by brada4** [comment]
Just MHO, results are fine, method is sane.
There is a known inconsistency with some skylake-x CPUs where AVX-512 and AVX2 preforms worse than AVX under virtualisation. Seems that MKL catches it sporadically in 2nd picture. It should be more or less on even outcome in every place.  
For completeness on Apple M1 - one should try apple accelerate BLAS which uses "matrix acceleration" coprocessor unreachable otherwise (and highlight the fact OpenBLAS is not yet fine-tuned there)

**Comment by martin-frbg** [comment]
Added the link to a new subsection "benchmarking" in the (still rather poshly named) "developer manual" in the wiki. (Have not run the benchmark with the current version yet, not sure which they were comparing to on their site as they seem to suggest to apt-get whatever binary package is/was available)
