### ISSUE TITLE
Can not link test_cblas_dgemm.c

### ISSUE THREAD

**Issue by ChrisNabold** [xianyi/OpenBLAS#3174]
I have compiled oipenblas using Mingw-64 -> which created the following directories C:/openblas/include, C:/openblas/lib and c:/openblas/share
I also compiled Lapack without Build_shared_libs but with Lapacke -> which creted  several directories in c:/Lapack/Build
c:/Lapack/build/include and c:/lapack/build/lib with liblapack.a liblapacke.a
I have a file c:/temp/test_cblas_dgemm.c
but when I try to link it I alwas get the error undefined reference to cblas_dgemm
Something with my gcc -command 
Any help is appreciated 
Thank you

**Comment by martin-frbg** [comment]
So what command are you using for linking ? Presumably you would need to specify the C:\openblas\lib path to the compiler so that the libopenblas can be found (`-Lc:/openblas/lib -lopenblas`). (And by the way your build of OpenBLAS will also contain Lapack and Lapacke by default if you have a fortran compiler installed, so there should be no need to build it separately)

**Comment by ChrisNabold** [comment]
Dear Martin,

 

Thank you for your help. I did not realize that openblas contaoins lapack.

I tried it and it worked!

 

Thank you 

Best regards

Chris
