### ISSUE TITLE
SVD convergence error in the presence of nan's

### ISSUE THREAD

**Issue by rgommers** [xianyi/OpenBLAS#3225]
There seems to be a regression that came in after the `0.3.13` release. In `0.3.12` and `0.3.13`, this works fine:
```
>>> a = np.array([[1, np.nan], [1, 1]])
>>> np.linalg.svd(a)
```
With `0.3.15` this does not converge. I cannot easily try `0.3.14` because it's not packaged on conda-forge. Users and packagers are observing this on multiple macOS and Linux systems, see https://github.com/numpy/numpy/issues/18914 for details.

**Comment by martin-frbg** [comment]
Bisecting now, suspect it could be one of the recent merges from Reference-LAPACK 3.9.1

**Comment by martin-frbg** [comment]
Right, imported from Reference-LAPACK PR 471 "Handle norm NaN value in xGESDD":
https://github.com/Reference-LAPACK/lapack/pull/471 which makes LAPACK return an error code rather than silently propagating the NaN like it "always" did (I notice now that the original issue ticket https://github.com/Reference-LAPACK/lapack/issues/469 claimed that the code would "exit" or "crash" at that point, which is probably untrue unless it refers to the user's code).
As an aside this means that you would also see this when building against pure "netlib" LAPACK 3.9.1

**Comment by rgommers** [comment]
Argh, so much fun. So not a bug from your perspective, and we should do something LAPACK-version-dependent in NumPy to handle this?

**Comment by martin-frbg** [comment]
Not sure if my (frog) perspective counts, I have raised the issue with the more illustrous members of the LAPACK team. Historically, NaN handling appears to have been something that LAPACK has not exactly excelled at. BTW the patch came from a matplotlib guy so at least it seems to stay in the family...

**Comment by mattip** [comment]
> which makes LAPACK return an error code rather than silently propagating the NaN like it "always" did

Is this now "return an error code and propagate the NaN" or "return an error code and not propagate the NaN"? If the latter, that would seem to break backward compatibility.

**Comment by martin-frbg** [comment]
Early return with error code set and arguments unchanged, which is what some other LAPACK routines already did.

**Comment by martin-frbg** [comment]
Closing here as discussion has taken place in the linked numpy ticket and my impression is that we're agreed to go forward with this change now.
