### ISSUE TITLE
openblas build failed with the latest Windows SDK 10.0.20348.0

### ISSUE THREAD

**Issue by Cheney-W** [xianyi/OpenBLAS#3274]
The latest windows sdk include the following contents in the "C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\um\winnt.h" file (line 6799 ~ line 6949):
```
typedef union _AMD64_MXCSR_REG {
    DWORD Value;
    struct {
 ...
        DWORD RC        : 2;    // bit 14:13
...
    } DUMMYSTRUCTNAME;
} AMD64_MXCSR_REG;

FORCEINLINE
DWORD
_convert_fpcr_fpsr_to_mxcsr (
    _In_ DWORD Fpcr,
    _In_ DWORD Fpsr
    )
{
...
    MxCSR.RC = ((Fpcr2.RMode & 2) >> 1) || ((Fpcr2.RMode & 1) << 1);
...
}
FORCEINLINE
VOID
_convert_mxcsr_to_fpcr_fpsr (
    _In_  DWORD MxCsr,
    _Out_ DWORD *Fpcr,
    _Out_ DWORD *Fpsr
    )
{
...
    Fpcr2.RMode = ((MxCsr2.RC & 2) >> 1) || ((MxCsr2.RC & 1) << 1);
...
}
```
The member DWORD RC of above structure conflicts with the macro #define RC in the intermediate file: cgemm_rc.c, cgemm_thread_rc.c, zgemm_rc.c and zgemm_thread_rc.c when build openblas, which causes openblas build failed with following errors:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winnt.h(6875): error C2059: syntax error: '='
C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um\winnt.h(6939): error C2059: syntax error: '&'
```
For fixing this issue, I did the following changes in the source file, and then openblas build successfully.
1. Remove the RC from the line 8 of the https://github.com/xianyi/OpenBLAS/blob/develop/driver/level3/CMakeLists.txt
2. Remove the GEMM_RC, GEMM_THREAD_RC, GEMM3M_RC and GEMM3M_THREAD_RC from the line 82 of https://github.com/xianyi/OpenBLAS/blob/develop/interface/gemm.c

I'm not sure if my change is suitable, just a little attempt on my part.

**Comment by martin-frbg** [comment]
I remember we had something similar years ago when winnt.h started to define "CR", the solution back then was to change the `define CR` in OpenBLAS to `define CR=CR` - curiously it looks like this was only changed in driver/level3/Makefile but not in the corresponding CMakeLists.txt, but nobody complained in the years since then. (I'll need to look into how to make this change in the CMakeLists.txt - the simple solution will not work as it would affect other entries in the intermediate file (and its name).)

Simply removing the "RC" and "GEMM_RC" entries will make it build, but with some functions missing from the library.

**Comment by martin-frbg** [comment]
Can you please check if the build works with the attached, modified cmake/utils.cmake ?
[utils.zip](https://github.com/xianyi/OpenBLAS/files/6662045/utils.zip)

**Comment by Cheney-W** [comment]
Awesome! You are so efficient.
I have tested your changes and this issue has been fixed successfully.

**Comment by martin-frbg** [comment]
Thank you very much for testing (and good thing you did not see me fumbling with cmake commands...)
