### ISSUE TITLE
Document `DYNAMIC_ARCH=0` and 64-bit interface changes

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#3307]
Thanks for the 0.3.16 release. I see in the release notes there is a new `DYNAMIC_ARCH=0` option. It would be nice to mention it somewhere in user-facing documentation like the wiki or the [README.md](https://github.com/xianyi/OpenBLAS/blob/974acb39ff86121a5a94be4853f58bd728b56b81/README.md#support-for-multiple-targets-in-a-single-library)

Also NumPy is starting to use the 64-bit interfaces by default. It would be helpful to document that we need to add `64_` to the utility functions listed in the [extension wiki page](https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions) and in the [README.md](https://github.com/xianyi/OpenBLAS/blob/974acb39ff86121a5a94be4853f58bd728b56b81/README.md#setting-the-number-of-threads-at-runtime) like `openblas_get_config64_`, although we really should have known that since we needed to add it to all the other functions anyway.

**Comment by martin-frbg** [comment]
There is no DYNAMIC_ARCH=0 option as such, there are only added safeguards so that specifying DYNAMIC_ARCH=0 instead of leaving that option out will no longer have the unwanted effect of setting DYNAMIC_ARCH=1. 
You will only need to add a prefix or suffix of your choice if you want different builds to coexist, this is (I think) mentioned in Makefile.rule

**Comment by mattip** [comment]
OK, thanks. Sorry for the noise.
