### ISSUE TITLE
error with arm-none-eabi-gcc

### ISSUE THREAD

**Issue by jie-fei** [xianyi/OpenBLAS#3351]
my cpu core is cortex-a7, when I compile openblas with "make BINARY=32 CC=arm-none-eabi-gcc  NOFORTRAN=1  HOSTCC=gcc TARGET=ARMV7", it reports error:
"In file included from zhpr2_k.c:41:
../../common.h:126:10: fatal error: sys/mman.h: No such file or directory"

**Comment by martin-frbg** [comment]
If this is some kind of embedded system you could try adding "OS_EMBEDDED=1"  (from PR #3073), but you would need to provide your own implementation of the `malloc` and `free` functions - please see the wiki entry https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-on-Cortex-M
~~If not an embedded system, it could be that there is something wrong with your toolchain installation so that it does not find its header files.~~

**Comment by martin-frbg** [comment]
(Actually nothing wrong with the toolchain installation probably, just that "arm-none-eabi-gcc" is for "bare metal" without any high-level operating system or libc that would provide memory management. If that is what you want to use, the wiki entry I mentioned will hopefully provide a starting point. Otherwise you will need a toolchain like arm-linux-eabi-gcc matching your target OS.)

**Comment by Evanok** [comment]
Hi,

@jie-fei Did you find a solution to compile libopenblas with baremetal?
I am able to compile libopenblas with my baremetal toolchain with this command line:

make HOSTCC=gcc CC=arm-none-eabi-gcc CROSS=1 TARGET=ARMV7 USE_THREAD=0 NO_LAPACK=1 NOFORTRAN=1 NO_SHARED=1 BINARY=32 ONLY_CBLAS=1

Modification inside build system:

```
diff --git a/Makefile.system b/Makefile.system
index bada954c..d97d892a 100644
--- a/Makefile.system
+++ b/Makefile.system
@@ -791,6 +791,9 @@ CCOMMON_OPT += -mfloat-abi=softfp
 FCOMMON_OPT += -mfloat-abi=softfp
 endif

+CCOMMON_OPT += -mfloat-abi=hard
+CCOMMON_OPT += -DOS_EMBEDDED -DEMBEDDED
+
 ifeq ($(OSNAME), Android)
 ifeq ($(ARM_SOFTFP_ABI), 1)
 EXTRALIB       += -lm
```

But I have some trouble linking the static library output file with my baremetal code:

```
arm-none-eabi-ld: ../../XXXX/OpenBLAS/libopenblas.a(memory.o): in function `atoi':
memory.c:(.text+0xc0): multiple definition of `atoi'; ../../lib/libcircle.a(util.o):/XXXX/raspberrypi3_circle/lib/util.cpp:658: first defined here
```
I can fix this issue easily by just removing the atoi implementation in openblas side.

```
arm-none-eabi-ld: ../../XXXX/OpenBLAS/libopenblas.a(cblas_sgemv.o): in function `cblas_sgemv':
gemv.c:(.text+0x368): undefined reference to `__assert_func'
arm-none-eabi-ld: ../../XXXX/OpenBLAS/libopenblas.a(memory.o): in function `blas_memory_alloc':
memory.c:(.text+0x358): undefined reference to `fwrite'
arm-none-eabi-ld: memory.c:(.text+0x480): undefined reference to `_impure_ptr'
make: *** [../../Rules.mk:160: kernel7.img] Error 1
```

What about this one? I don't understand the error because there is no fwrite call in openblas library... 
I did not declare my own malloc/free implementation. Is it related?

Thanks,
Arthur.

**Comment by martin-frbg** [comment]
driver/others/memory.c has some `fprintf(stderr,...` that may cause it to go looking for fwrite, and some of the codes in interface/ use STACK_ALLOC from common_stackalloc.h which has an assert() if STACK_ALLOC_PROTECT is defined (which it is at the top of that header file). Try getting rid of those, and also see
https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-on-Cortex-M (if you haven't already)

**Comment by Evanok** [comment]
Thanks, Martin for your quick answer!

My first try was using Cmake but the compilation failed very quickly. I will try to focus my effort on the Makefile solution for now. 

I am not very skilled at using Cmake...
My cmake process:

define my cmake toolchain file:

```
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER "arm-none-eabi-gcc")
set(CMAKE_CXX_COMPILER "arm-none-eabi-g++")

set(CMAKE_EXE_LINKER_FLAGS "--specs=nosys.specs" CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

Run cmake:

```
cmake .. -DCMAKE_C_COMPILER=arm-none-eabi-gcc -DCMAKE_TOOLCHAIN_FILE:PATH="toolchain.cmake" -DNOFORTRAN=1 -DTARGET=ARMV7 -DEMBEDDED=1 -DUSE_THREAD=0   -DBUILD_WITHOUT_LAPACK=1 -DBUILD_SINGLE=1 -DBUILD_STATIC_LIBS=1 -DNOFORTRAN=1
cmake --build .
```

Build error output sample:

```
/home/arthur/work/repository/raspberrypi3_circle/XXXX/OpenBLAS/kernel/arm/amax_vfp.S:430: Error: attempt to use an ARM instruction on a Thumb-only processor -- `subs r12,r12,#1'
/home/arthur/work/repository/raspberrypi3_circle/XXXX/OpenBLAS/kernel/arm/amax_vfp.S:431: Error: attempt to use an ARM instruction on a Thumb-only processor -- `bne amax_kernel_S10'
/home/arthur/work/repository/raspberrypi3_circle/XXXX/OpenBLAS/kernel/arm/amax_vfp.S:442: Error: attempt to use an ARM instruction on a Thumb-only processor -- `bx lr'
```

I am not able to find all the options available from the Makefile as CROSS or  ONLY_CBLAS for example in the CMakeList.txt.

**Comment by martin-frbg** [comment]
Unfortunately it is still possible that the cmake build options do not reflect all that is supported by the Makefiles. However, ONLY_CBLAS should be accepted by the build scripts (in the cmake folder) that get invoked from the toplevel CMakeLists.txt. The CROSS option should be equivalent to cmake's built-in CMAKE_CROSSCOMPILING variable. The build error you got seems to be indicative of a mis-specified cpu (you have `-DTARGET=ARMV7` where the wiki page suggests using `ARMV5`)
