### ISSUE TITLE
Why the speed of the first calculation is obviously not as good as the subsequent calculations

### ISSUE THREAD

**Issue by yuanAIhan** [xianyi/OpenBLAS#3377]
When I use it to calculate the gemm, but I find that the first must be slow most! Could you tell how realize this?  It is NUMA optimization? Can you tell me some code about it?

**Comment by martin-frbg** [comment]
Not necessarily NUMA effects, but the first call ends up with all the overhead for thread creation and memory allocations. Also, (particularly in benchmarks that do nothing else,) later calculations may benefit from having code and/or data still in some level of cache.

**Comment by yuanAIhan** [comment]
Are there any optimizations for the numa architecture?

**Comment by martin-frbg** [comment]
Not specifically optimizations, but OpenBLAS can be made more "NUMA-aware" by disabling the default NO_AFFINITY=1 setting (see comments in Makefile.rule)

**Comment by brada4** [comment]
If you do malloc, then time memsets, first try will be slow, because of memory overcommitment actual physical memory is allocated on access.
Another way with NUMA is to use one NUMA node by setting OPENBLAS_NUM_THREADS to only use node-sized thread pool. It is sometimes faster than full-size task, and if you manage to run one swarm per NUMA node it is certainly faster.

**Comment by brada4** [comment]
PS I dont think it is openblas specific. Any software starts to work well once it spins/warms up completely.
