### ISSUE TITLE
Seems that mips(32) needs their own generic target

### ISSUE THREAD

**Issue by brada4** [xianyi/OpenBLAS#3444]
Seen here: https://github.com/openwrt/packages/pull/17077

**Comment by martin-frbg** [comment]
If I remember correctly, the MIPS32 targets are basically all P5600 anyway, with the added quirk that MSA capability is handled as a property of the compiler rather than the cpu itself (which I guess would "often" work when building on the actual hardware and/or with a vendor compiler). Not sure if there is a cpuid bit that could be checked instead, or - I guess - on Linux at least it might now even be possible to get it from feature flags in /proc/cpuinfo.
