### ISSUE TITLE
ddot_k_PRESCOTT segfaults when called on non-memory aligned data

### ISSUE THREAD

**Issue by ogrisel** [xianyi/OpenBLAS#3453]
As discussed in https://github.com/scipy/scipy/issues/14886 and https://github.com/scikit-learn/scikit-learn/issues/21361.

Given that prescott is an old architecture, I don't think it impacts many users. We only discovered it because older version of OpenBLAS would wrongly detect SkylakeX CPU as Prescott, but this is no longer the case in 0.3.17 and 0.3.18 (and maybe 0.3.16 as well IIRC).

I am not sure if OpenBLAS officially supports being called with non-memory aligned data. This fact that we face this problem in the scikit-learn test suite is a consequence of a low level issue in joblib https://github.com/joblib/joblib/issues/563 that we intend to fix anyways (but I don't know yet how...).

**Comment by martin-frbg** [comment]
There are no official guarantees, particularly for original GotoBLAS kernels written for ancient cpus where there may have been significant performance impact from using unaligned accesses. I did change a bunch of `movaps` instructions in the copy kernels to their `movups` counterpart quite a while ago (see issue #1137) and already had misgivings back then that this would only shift the problem to various other old kernels. (More recently, that change has even been suspected to cause problems on an old Core2  #3263 but that may have been a unique hardware problem)
You would get PRESCOTT as a fallback in DYNAMIC_ARCH scenarios when the library gets installed on any unrecognized x86_64 cpu , so the problem is not necessarily limited to SkylakeX but may reappear in the future.

**Comment by ogrisel** [comment]
Note that the Nehalem and Haswell kernels do not have the issue. So maybe changing the fallback would be a quick way to not have to fix legacy code if you no longer want to maintain those.

**Comment by martin-frbg** [comment]
It would probably be safest to include a "generic" build in the DYNAMIC_ARCH lineup, but I am not all too happy with how bloated that is already. On the other hand, even after "fixing" ddot similar problems remain elsewhere, not least in the (I)AMAX SSE kernels which are used by almost all x86_64 configurations. (Un)fortunately I do not own any Prescott or Core2 anymore where I could look for performance impacts, and neither does the gcc compile farm. One might argue that it is now another three years since I last mentioned these concerns, so this outdated hardware is even less likely to be relevant today)

**Comment by brada4** [comment]
Are you sure it is about alignment running prescott code on skylakex?

**Comment by martin-frbg** [comment]
@brada4 I'd think it is a perfectly plausible assumption - while SKX would certainly have no problems dealing with unaligned data if given a choice how to handle them, the old GotoBLAS assembly kernels are rife with `movaps` statements that are bound to cause a segfault in this situation. (And it is probably safe to assume that it would have seemed natural ~15 years ago to make doubly sure that all data is aligned to achieve best performance on the hardware available at the time)

**Comment by brada4** [comment]
https://github.com/scipy/scipy/issues/14886#issue-1030526706 hmm

**Comment by martin-frbg** [comment]
@brada4 why "hmm" ? If the old OpenBLAS did not recognize the CPUIDs of the new hardware, DYNAMIC_ARCH there fell back to Prescott kernels as the last resort for anything unknown.
Prescott uses ddot_sse2.S which contains several mov**a**ps instructions (while SKX kernel has mm512_load**u** and Nehalem,Haswell etc do mov**u**ps), unaligned data then causes segfault as already seen in the old ticket from 2017).

A sufficient workaround for someone unfortunate enough to be locked in with 0.3.9 (and all its shortcomings uncovered since then) should be to `export OPENBLAS_CORETYPE=HASWELL` on their futuristic hardware. The only open question is how to handle such events in the future - change all old kernels in case they may get used again on current hardware and with data layout they were not designed for (and risk killing performance for anybody still using the less versatile hardware for which they were originally written), change the DYNAMIC_ARCH fallback to avoid the old kernels, or document the potential problem and leave the code as it is.

**Comment by brada4** [comment]
The idea that old kernel allegedly writes input that is mprotect()-ed?

**Comment by ogrisel** [comment]
> The idea that old kernel allegedly writes input that is mprotect()-ed?

In scipy/scipy#14886 we originally suspected that the problem was caused by the fact that the data buffer was readonly but then we discovered afterwards that this same memory buffer was also not memory aligned. So latter property is likely the cause of the problem. I can run experiments to confirm this if it's really needed.

**Comment by martin-frbg** [comment]
I really do not think that would be needed - it is clear to me that non-alignment is the cause here, and this trap has probably existed for close to twenty years. For the case at hand, I think the priority should be to get joblib fixed (assuming that this is most likely to be distributed with affected programs, while with OpenBLAS the primary danger would be from outdated versions preinstalled on users' systems, which cannot be fixed retroactively anyway).  On the other hand, Prescott is not the only problematic cpu, as  the old DDOT code is also used on other x86_64 cpus from the early 2000s up to and including some that came out in 2008: Intel Core2/Penryn and  Dunnington, Via Nano and AMD Opteron, Bobcat and Barcelona.

**Comment by ogrisel** [comment]
Another question: why would OpenBLAS fallback to PRESCOTT when new unknown CPU ID are detected but it's easy to see that those CPUs have the AVX2 flags. In this case, instead of falling back to old PRESCOTT one could fallback to the earliest CPU architecture with AVX2 support, no?

**Comment by martin-frbg** [comment]
Correct, except in the case where the builder provided a shorter DYNAMIC_LIST of models to support (but in the worst case one would get a fallback to Prescott again, as that cpu is guaranteed to be always included). The alternative would be to replace PRESCOTT in its role as dumb fallback with GENERIC (plain C kernels and all GEMM only 2x2)
