### ISSUE TITLE
Issues when building OpenBLAS with cmake

### ISSUE THREAD

**Issue by rafaelcfsousa** [xianyi/OpenBLAS#3458]
Hi, I tried to build OpenBLAS using the **CMakefile** and I realized that the build does not work as expected for most of the architectures (e.g., ARM64, RISCV, POWER, MIPS, etc). In addition, for some cases the build crashes, e.g., -DTARGET=POWER8.

After a careful analysis, I figured out that the issue described above comes from the fact that the parser used by **cmake** to read the **kernel/arch/KERNEL\*** files is not working properly.

Below I list some of the issues that may be found:
1) The parser does not treat statements such as ifdef and ifndef.
2) The code below crashes if CMAKE_MATCH_1 is not defined.
```
 if (DEFINED ${${CMAKE_MATCH_1}} AND ${${CMAKE_MATCH_1}} STREQUAL ${CMAKE_MATCH_2})
```
3) The way that the code above checks if the variable is defined should be:
```
if (DEFINED ${CMAKE_MATCH_1} ...)
```
4) The code below does not check if CMAKE_MATCH_1 is defined so that, if it is not defined, the build crashes.
```
if (NOT ( ${${CMAKE_MATCH_1}} STREQUAL ${CMAKE_MATCH_2}))
```

Besides that, there are some other missing features, as shown below:

1. Comments are not treated
2.  Fails to parse more complex structures, like the following:
```
ifeq(...)
    ifneq(...)
        SGEMM_KERNEL=sgemm_kernel_option1.c
        DGEMM_KERNEL=dgemm_kernel_option1.c
    else ()
        SGEMM_KERNEL=sgemm_kernel_option2.c
        DGEMM_KERNEL=dgemm_kernel_option2.c
    endif()
else ()
    SGEMM_KERNEL=sgemm_kernel_option3.c
    DGEMM_KERNEL=dgemm_kernel_option3.c
endif()
```
3. Even though the statement ifdef is implemented, some patterns are not considered, like the one below:
```
ifeq ($(SGEMM_UNROLL_M)x$(SGEMM_UNROLL_N), 8x8)
```

I have already worked on a solution to solve all points mentioned above (#https://github.com/rafaelcfsousa/OpenBLAS/commit/fb891f33da3428602d765905b1395a9a7e798e4a). I would like to know if it is ok to PR it?

**Side-effect:**
Before invoking the parser to read the KERNEL files, some routines (e.g., SetDefaultL1) are called to define some default kernels (e.g., set(SAMAXKERNEL amax.S)). After that, the parser is finally called to tie which source file implements which kernel. Given that the current parser does not have support to ifeq/ifndef, the variables that were defined previously (e.g., in SetDefaultL1) are redefined as shown in the example below:
```
ifndef SAMAXKERNEL
SAMAXKERNEL = amax_sse.S
endif
```
With this patch, these variables would not be redefined, given that they were defined previously.

**Comment by martin-frbg** [comment]
Well, the cmake build system is some kind of second-class citizen here still. When I added the present capability to the parser about a year ago, it was just a hack to get it to make sense of what was in the KERNEL files for x86_64 and power targets at the time.  Obviously changes crept in recently (like the "8x8" in the CortexA53 SGEMM that you quoted) that it cannot handle, and I suspect the number of cmake users on anything other than x86 could be rather low. For arm64, mips and riscv architectures there has been only very limited testing of the cmake build system, so some cpu targets there may not yet build with cmake, in particular when doing cross-builds. 
So a PR would certainly be welcome. Note however that the redefinitions you describe under "Side-effect" may be unsightly but intentional, i.e. they would need to be compared to the outcome from the plain gmake build where the Makefile.L? contain fallbacks for anything not covered by the appropriate KERNEL.cpu and KERNEL files. In the current cmake layout,  the "corresponding" SetDefaultL? routines get called first instead of last, so some of what they define as fallbacks get overridden later. (I notice there is even a comment to this effect at the start of kernel.cmake - we certainly do not want to prevent the redefinition here, unless and until we manage to fix the sequence in which these files are read)

**Comment by rafaelcfsousa** [comment]
Hi @martin-frbg, if we change the order the KERNEL.* files (and SetDefaultL? routines) are read/executed, this issue can be fixed. I will submit a PR that fixes the parser taking also into consideration what I describe above.

Note: I checked the files that are generated by the cmake with/without my changes using -DDYNAMIC_ARCH=1 on x86_64. The same number of files are generated, besides that, they are equal. Well, there are other issues related to cmake on Power, but I will leave them to another PR given that they are arch-related (and depend on this one).

Thank you!
