### ISSUE TITLE
OpenBLAS extensions

### ISSUE THREAD

**Issue by ivan23kor** [xianyi/OpenBLAS#3515]
Hi, I have developed a convolution algorithm that relies on packing and computation microkernels used in the BLAS libraries.

I added my algorithm to BLIS as [a BLIS addon](https://github.com/flame/blis/blob/master/docs/Addons.md).
Currently, I have my convolution algorithm as a part of cblas in OpenBLAS which is not the right way.
Is there a better way to leverage the microkernels for other algorithms?

**Comment by brada4** [comment]
You can link -lopenblas to your final program or library that contains (only) your function?
Internals around microkernels are wildly non-portable between BLIS, OpenBLAS, Atlas, MKL and such concept is absent from reference LAPACK.

**Comment by ivan23kor** [comment]
@brada4, I don't think you understand my question.
I have already repurposed GEMM_ITCOPY, GEMM_ONCOPY and GEMM_KERNEL_N to convolution.
As of now, I registered my solution as cblas_conv in the build tree similarly to how it is done for cblas_sgemm.
However, this is an ugly design as convolution is not a BLAS routine.

Not having my algorithm in the OpenBLAS build tree is also inconvenient, because I have to include files from the OpenBLAS tree defining the aforementioned microkernels, type definitions, block sizes, etc.
Linking -lopenblas is also a problem in this case, as the microkernel symbols are not exported, only the interface symbols are. So I would have to build OpenBLAS and link with each microkernel object file separately.

For example, BLIS has a way to repurpose their microkernels to other algorithms and register them as an addon (please, check [this](https://github.com/flame/blis/blob/master/docs/Addons.md) to understand what I mean)
I think OpenBLAS should have a concept "extension", if there is no such thing yet.
Non-BLAS routines that rely on OpenBLAS building blocks would be registered as an extension (with optional enabling build flags).
The closest existing thing I could find is [the helper functions](https://github.com/xianyi/OpenBLAS/tree/develop/driver/others) are in their own category and are exported independently of the rest of BLAS interface.

OpenBLAS does not have to accept all of the extensions into the main repo (e.g., my convolution code), but there should be a common way to register extensions and a template for how to do it.

**Comment by martin-frbg** [comment]
Indeed OpenBLAS does not currently have any provisions for add-ons, so putting your extra code in cblas would seem fine (if you want it to have a CBLAS-like interface). I have not looked at how the BLIS method works - in particular, I think one would want to expose the added function by including its interface in a header file that comes with the library. Is the add-on expected to be delivered separately, installing its own header(s) ? Otherwise if it is integrated with the generic library code, I see no advantage in having its presence depend on an additional build option (that also sees to its appearing in the main header), unless it is a very big and convoluted bunch of code. OpenBLAS already provides a handful of BLAS extensions, as you noticed ~/driver/others or perhaps also ~/interface would be plausible locations if you want to keep it separate from the "proper" level2/level3 BLAS

**Comment by brada4** [comment]
convolution is ton of _copy and one huge _gemm, First approach would be to map algorithm to BLAS API, and optimize after. I would bet on _copy call latency as a culprit.

**Comment by ivan23kor** [comment]
Thanks for the feedback about the current state of extensions support in OpenBLAS.
BLIS includes everything in its only exported header blis.h.
The amount of code to be exported for an extension is small and independent of BLAS operations, so I agree with @martin-frbg that there should be no separate build option and the extension functions can be declared in cblas.h.

@brada4, my convolution code is my thesis WIP so I cannot make it public yet. However, I could prepare a PR for with some dummy code - let's say, register GEMM code as a new OpenBLAS extension.

**Comment by ivan23kor** [comment]
If somebody else in the future will need an OpenBLAS extension, (s)he will find this thread.
For my needs, linking sources into libopenblas and generating a separate header with manually exported definitions works fine.
