### ISSUE TITLE
What is `USE_OPTIMIZED_BLAS` used for?

### ISSUE THREAD

**Issue by emmenlau** [xianyi/OpenBLAS#3599]
This is not a bug but merely a question. I'm quite new to BLAS and LAPACK, and while I understand the basic concept what they are useful for, there are a number of things that I do not fully grasp.

One such question is why OpenBLAS would have the `USE_OPTIMIZED_BLAS` option. Is this only for benchmarks against another BLAS library, or does OpenBLAS actually support falling back to another BLAS library? What would that be used for?

I was thinking that it would be really cool if OpenBLAS could at runtime check which of a number of BLAS libraries is faster for a specific method and bind that dynamically. But that is not whats happening here, no? Do such wrapper libraries exist?

**Comment by martin-frbg** [comment]
This option is only present in the build files of the LAPACK source that OpenBLAS imports from the reference implementation (Reference-LAPACK here on github, otherwise known as "netlib"), and is not actually used when building LAPACK as a part of OpenBLAS. In the original context of Reference-LAPACK, the option makes sense as the reference implementation also contains the unoptimized reference BLAS, and by default compiles and links LAPACK against it. Within OpenBLAS, the BLAS
references are naturally satisfied using OpenBLAS code (and some LAPACK routines are replaced with optimized versions as well).
I am not aware of a wrapper that does runtime checks to select the best implementation on the fly, and I question its practicability.

**Comment by emmenlau** [comment]
Thanks a lot @martin-frbg , that's a very helpful answer. I'm closing this issue then.
