### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by OgreTransporter** [xianyi/OpenBLAS#3615]
I try to build OpenBLAS with CMake/Visual Studio. But, I have to switch off LAPACK because of two errors.

**1.**

https://github.com/xianyi/OpenBLAS/blob/ee4244538cc8c2ec1ccb6d0cd6a799bb9bd75a63/lapack/CMakeLists.txt#L115
https://github.com/xianyi/OpenBLAS/blob/ee4244538cc8c2ec1ccb6d0cd6a799bb9bd75a63/CMakeLists.txt#L206

Two projects with the same name do not work with Visual Studio. Visual Studio unfortunately does not distinguish between upper and lower case.

Fix:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -203,8 +203,8 @@ endif ()

 # add objects to the openblas lib
 if(NOT NO_LAPACK)
-  add_library(LAPACK OBJECT ${LA_SOURCES})
-  list(APPEND TARGET_OBJS "$<TARGET_OBJECTS:LAPACK>")
+  add_library(LAPACK_TMP OBJECT ${LA_SOURCES})
+  list(APPEND TARGET_OBJS "$<TARGET_OBJECTS:LAPACK_TMP>")
 endif()
 if(NOT NO_LAPACKE)
   add_library(LAPACKE OBJECT ${LAPACKE_SOURCES})
```

**2.**

```
sgetrf_parallel.obj : error LNK2019: unresolved external symbol "slaswp_ncopy" referenced in function "inner_basic_thread".
dgetrf_parallel.obj : error LNK2019: unresolved external symbol "dlaswp_ncopy" referenced in function "inner_basic_thread".
cgetrf_parallel.obj : error LNK2019: unresolved external symbol "claswp_ncopy" referenced in function "inner_basic_thread".
zgetrf_parallel.obj : error LNK2019: unresolved external symbol "zlaswp_ncopy" referenced in function "inner_basic_thread".
```

**Comment by martin-frbg** [comment]
Interesting, I guess (1) did not come up earlier as nobody could build the Fortran LAPACK with VS anyway, so had to use NOLAPACK (and you are building the current "develop" branch rather than one of the releases that do not yet have the C LAPACK) ?
Not sure what is going on with (2) - do you get any earlier errors for the "unresolved" functions ? (These should get built from the kernel/CMakeLists.txt, using generic C sources on x86_64, so no obvious reason why they could be missing)

**Comment by OgreTransporter** [comment]
In fact, I didn't notice that until now either, because LAPACK was always automatically disabled until ed8c028f7fc30cc2327410b8051c99f8eb1f58cb. Of course I think it is great if C LAPACK is available.

The error message (2) I also do not understand, because I found the functions in kernel.

**Comment by martin-frbg** [comment]
For (1), perhaps make it LAPACK_NETLIB rather than LAPACK_TMP ? (Just a nicer name that distinguishes it from the "other" lapack which is the handful of LAPACK functions that OpenBLAS overrides with its own implementations.
For (2), can you check what symbols names are there in the library at this point, just in case this is a problem with missing or additional underscores on the symbol name ? (Guessing something like dumpbin /symbols would do this on Windows)

**Comment by martin-frbg** [comment]
I wonder why we do not see these issues in CI - are you building in the Visual Studio "developer command prompt" environment, or in the VS IDE ?

**Comment by OgreTransporter** [comment]
I create the project via the normal command line with CMake and then open the project in the IDE to build.

```
cmake -G "Visual Studio 17" -A x64 -D CMAKE_INSTALL_PREFIX:PATH=D:\OpenBLAS\install -D CMAKE_DEBUG_POSTFIX:STRING=d -D BUILD_SHARED_LIBS:BOOL=ON D:\OpenBLAS\src
```

**Comment by martin-frbg** [comment]
must be some weirdness in the IDE then - if you look in azure-pipelines.yml around line 64, the CI job   starts basically the same. Only it then does `cmake --build . --config Release` still on the command line instead of building the project in the IDE

**Comment by OgreTransporter** [comment]
CMake actually works and also creates two projects with LAPACK, but the IDE cannot open both because they have the same name. You can build it with MSBuild, but then I somehow get the error message from (2).

**Comment by martin-frbg** [comment]
guess these are some of the reasons why the wiki page about building OpenBLAS on Windows has always instructed to build outside the IDE...
Can you check if the "missing" Xlaswp_ncopy objects are mentioned in any of the project files that got created ?

**Comment by OgreTransporter** [comment]
I'll take a look at it tomorrow. Currently I only need BLAS and not LAPACK. But it would be a pity if OpenBLAS would not work completely on all platforms. It is also easier to build OpenBLAS than the original BLAS and LAPACK. Fortran on Windows is more difficult anyway and with CMake there is a simple tool to build libraries across platforms.

**Comment by martin-frbg** [comment]
Looks like the generator messes up in the generation of the definitions for both `?laswp_ncopy` and `?neg_tcopy` kernels on Windows, e.g. build\kernel\CMakeFiles has a file `claswp_ncopy` without the `.c` extension, and the `#include` of the original source path in it has `OpenBLAS-develop/kernel/x86/_2` instead of `OpenBLAS-develop/kernel/generic/zlaswp_ncopy_2.c`

**Comment by martin-frbg** [comment]
Oops. Pretty much the same garbage on Linux CMAKE builds, looks like some fairly recent breakage that did not get caught by any of the tests.
