### ISSUE TITLE
How to use Openblas's subroutine to solve linear equation?

### ISSUE THREAD

**Issue by HPC4AI** [xianyi/OpenBLAS#3666]
Hi, I have some questions.
1 For Openblas, is the function to solve the linear equation LAPACKE_dgesv? 
2 How should I compile it when I want to use Openblas to solve linear equation? Is `make BINARY=64 USE_THREAD=1 NUM_THREADS=64 USE_OPENMP=1` right? There are 64 cores(2 sockets, 32 cores/per sockets) on my machine and I want to use OPENMP.
3 Which command should I enter to solve linear equation for better performance using Openblas' subroutine? Is `numactl -i 0-1 ./xx` good enough？
Thanks a lot.

**Comment by martin-frbg** [comment]
1. OpenBLAS is an optimized implementation of the standard BLAS functions, and it includes the reference implementation of the LAPACK standard from netlib.org, so all documentation of BLAS and LAPACK on netlib.org applies. So yes, LAPACKE_dgesv is  valid approach to solving linear equations.
2. These options are correct. (If you are working with very large matrix sizes, adding INTERFACE64=1 may be necessary or you'll get addressing issues when array indexes no longer fit into a normal 32bit integer number)
3. Unfortunately I cannot suggest anything better for a start, you may have to experiment if performance is unsatisfactory. What is your hardware and operating system ?

**Comment by brada4** [comment]
2. You dont need OpenMP to utilize multiple cores. USE_THREADS is sufficient.


3. typically fastest would be to size task to fall into one NUMA node, i.e OMP_NUM_THREADS=32 OPENBLAS_NUM_THREADS=32 (or 16 if you called hyperthreads CPUs). Resetting default placement with numactl has no effect whatsoever. Just let threads fall into otherwise idle CPUs.
