### ISSUE TITLE
openblas_set_num_threads not found

### ISSUE THREAD

**Issue by TeddyAlbina** [xianyi/OpenBLAS#3881]
Hello,

I'm new in the openblas game, i compiled it on aws linux 2 then when i tried to use it i got the error `error: symbol lookup error: undefined symbol: openblas_set_num_threads (fatal)` , my understanding is that the header files openblas_config.h is not included in the build.

I tried to edit CMakeCache.txt without success (i added the path to the build directory)

```
//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include;/home/ec2-user/OpenBLAS/build
```

bu then i got into trouble

![image](https://user-images.githubusercontent.com/24303374/210458959-ddf30505-bf4f-4bf0-8f10-8bd5922db174.png)

So my question is how to fix that problem ?

Thank you.

**Comment by TeddyAlbina** [comment]
The function seems there

 
![image](https://user-images.githubusercontent.com/24303374/210470890-24610780-72a9-4749-b513-0025dcec3fc7.png)

**Comment by martin-frbg** [comment]
I do not think a missing header is the problem here (openblas_config.h is generated by cmake, and anyway the prototype for openblas_set_num_threads is in cblas.h, which your code should include rather than openblas_config.h directly).
Where exactly did you encounter the error - perhaps you are not linking to the libopenblas.a that you built, or including a different (generic) cblas.h in your source that does not have the prototype ?

**Comment by martin-frbg** [comment]
Did you get this sorted ?

**Comment by martin-frbg** [comment]
Please reopen / append here if necessary
