### ISSUE TITLE
Questions about compiling in the Windows on ARM64 environment

### ISSUE THREAD

**Issue by aTerminal** [xianyi/OpenBLAS#3918]
According to the guidance given by the wiki:
https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Windows-on-ARM64
I try to compile OpenBLAS in my WoA environment, the operating system is Windows 11 22H2 (ARM64). When it came time to build, I found that ```make``` was not included in the prerequisites. I tried ```make``` in mingw with x86 emulation and found that it cannot run successfully (requires AVX512 instruction set, which apparently does not exist under ARM64 architecture). May I ask where I need to find the ```make``` prepared for the Windows on ARM64 environment? Or does this compilation need to be done on an x86 machine?
Thank you very much for your reply.

**Comment by brada4** [comment]
There is experimental CMake support that builds using ninja like all inside visual studio.
MSYS2 and llvm clang highly recommended. There is aarch64 release of those around.

Ps there is some misconception in your assumptions, AVX is not reachable from x86 32bit mode.

**Comment by martin-frbg** [comment]
As far as I know the 32bit x86 `make` should work just fine in the emulation. Most likely you left out some crucial options like HOSTCC and TARGET (see the first paragraph of the wiki page) that would make sure that the `getarch` component of the build system does the right thing. (Misdetection of the x86 emulation layer instead of the actual hardware would probably lead to a weird mix of Intel and Arm characteristics in the generated config.h and Makefile.conf)
