### ISSUE TITLE
How to get rid of -march=skylake-avx512

### ISSUE THREAD

**Issue by samfux84** [xianyi/OpenBLAS#4040]
Hi,

I am trying to build OpenBLAS 0.3.19 and 0.3.20 from source on our HPC cluster. It has several generations of hardware and I build on the oldest hardware, which has Intel Skylake CPUs.

I am setting explicitly 

-march=core-avx2

through CFLAGS, CXXFLAGS as this is supported on all our hardware (including different Intel and AMD cpu types), but the installation always overrides this with

-march=skylake-avx512

even if I set explicitly NO_AVX512=1 when running make.

How can I enforce that "-march=skylake-avx512" is not set?

Would this require to write a patch that removes "-march=skylake-avx512" form all makefiles and getarch.c or is there a simpler way to achieve this?

Any help is appreciated.

Best regards

Sam

**Comment by martin-frbg** [comment]
This is not supposed to happen, NO_AVX512=1 forces cpu type detection to assume HASWELL at best. Can you please post the complete set of options you use for the build ? (From what you wrote, it should be something like "TARGET=HASWELL DYNAMIC_ARCH=1 NO_AVX512=1"). Is there a particular reason why you are trying 0.3.19 and 20 rather than the current release ?

**Comment by samfux84** [comment]
@martin-frbg : Thank you for your reply. I think I  found the reason. I am sorry, there was a mistake in my buildscript such that NO_AVX512=1 was not properly set in the make script.

**Comment by martin-frbg** [comment]
Actually if non-AVX512 Skylake/KabyLake/whatever-lake  is your oldest generation, it should be sufficient to set TARGET=HASWELL DYNAMIC_ARCH=1 (so that all the common code is built to be compatible with Haswell) without the NO_AVX512=1, unless you actually want to avoid using AVX512 on the newer machines as well (e.g. for reasons of reproducibility). OTOH if you really want to avoid AVX512 everywhere, just TARGET=HASWELL without even the DYNAMIC_ARCH=1 is probably enough (resulting in faster compilation and much smaller library),as there are few differences between the HASWELL and ZEN targets.

**Comment by samfux84** [comment]
Thank you for your reply and for the build tips. Currently I build without DYNAMIC_ARCH=1 and build with the HASWELL target.

When building software stacks, continuity and reproducibility are important. I also build many packages that depend on OpenBLAS (it is my favorite BLAS implementation and I appreciate that it also contains LAPACK).

I already started to test building newer OpenBLAS versions than 0.3.20 but there is one use case, where I noticed a problem and would like to rebuild other packages (PETSc) with the same OpenBLAS version that I originally used.
