### ISSUE TITLE
When the computation load is small, openblas will use only one thread continuously.

### ISSUE THREAD

**Issue by liuaibin** [xianyi/OpenBLAS#4199]

**Comment by martin-frbg** [comment]
This is by design - for small loads, the overhead of distributing the load over multiple threads and managing concurrent access to the data is usually larger than the performance gain from working in parallel. The switchover point from single
to multithreading is defined individually in the respective interface files, or more generally through the compile-time parameter GEMM_MULTITHREAD_THRESHOLD
Do you have a test case where a single thread is actually slower ?
