### ISSUE TITLE
Wrong .dll name in .lib file of windows release 0.3.24 

### ISSUE THREAD

**Issue by FlyinTeller** [xianyi/OpenBLAS#4227]
I couldn't find a similar issue and it seems to me that this should be a bug.

I have downloaded OpenBLAS-0.3.24-x64 from sourceforge (https://sourceforge.net/projects/openblas/files/v0.3.24) and used it to compile openCV. After linking my own application against opencv, it looks for `lipopenblas.exp.dll`, which does not exist, as the dll that is shipped in the sourceforge archive is (correctly) called libopenblas.dll.

On further inspection, I have seen that `dumpbin /all libopenblas.lib` contains
```
RAW DATA #6
  00000000: 6C 69 62 6F 70 65 6E 62 6C 61 73 2E 65 78 70 2E  libopenblas.exp.
  00000010: 64 6C 6C 00                                      dll.
```

so it looks to me that the `.lib` file incorrectly specifies a dll name that is incorrect. 

The only mentioning of this in any way I could find was https://www.itworks.hu/running-whisper-cpp-on-windows/ which contains instructions to just rename the DLL

**Comment by martin-frbg** [comment]
Oops, sorry - the Windows builds are cross-compiled on Linux, and this time (and for the previous release as well) I had used mingw's dlltool to generate the .lib and .exp, instead of transferring the .def to an actual Windows host and running lib.exe there. Obviously I have missed this one discrepancy - apparently one needs to supply the dll name to dlltool as well to keep it from getting creative.

**Comment by FlyinTeller** [comment]
Creative indeed :). Any chance to replace the existing release with a corrected one so we can avoid the rename on our end?

**Comment by martin-frbg** [comment]
Done now for both 0.3.23 and 0.3.24 (and the .lib and .exp were made with Microsoft lib.exe again just to be sure).
