### ISSUE TITLE
Problem when installing openblas

### ISSUE THREAD

**Issue by Pixie8888** [xianyi/OpenBLAS#4231]
Hi,

I first installed pytorch (gpu version=1.21.1), then I install openblas with "conda install openblas-devel -c anaconda". But this command will always degrade pytorch to cpu version. It causes problem for futher gpu training. How to solve this problem?

![image](https://github.com/xianyi/OpenBLAS/assets/72333326/e6f0aa64-a96f-4d0b-b0a9-6f5080e2732a)

**Comment by rgommers** [comment]
@Pixie8888 PyTorch in the conda `defaults` channel depends on MKL, and OpenBLAS and MKL both provide a BLAS library and are hence incompatible. Why do you need to install `openblas` in that environment? I recommend using `mkl` in that environment, and if you only want `openblas` by itself then create a separate conda environment.

**Comment by Pixie8888** [comment]
Hi,
Becaus I want to install MinkowskiEngine (https://github.com/NVIDIA/MinkowskiEngine), which requires to install openblas.
It seems that if I install pytorch gpu version with pip, the problem is gone.

**Comment by rgommers** [comment]
That README has the following guidance:
```
#      \ # uncomment the following line to override to openblas, atlas, mkl, blas
#      --install-option="--blas=openblas" \
```
You should always aim to use the same BLAS library for all your dependencies, otherwise you'll get reduced performance (sometimes quite badly) due to different libraries using different OpenMP/pthreads threadpools. Since you want to combine MinkowskiEngine with PyTorch and PyTorch depends on MKL (the wheel on PyPI statically links MKL), your best choice here is to use `--install-option="--blas=mkl`.

> It seems that if I install pytorch gpu version with pip, the problem is gone.

Mixing conda packages and wheels may be the worst option. Everything from conda is bettter than everything from PyPI (https://pypackaging-native.github.io/key-issues/native-dependencies/blas_openmp/ explains why), and everything from PyPI in second best.

**Comment by brada4** [comment]
You need to choose between packages like anaconda OR pypi wheels  OR  build pypi . Mixing them is certain doom with analysing binaries, memory dumps, everything crashing etc. You need to check "MKL" versions of packages - if they are built with MKL headers then all imports will be in form of mkl_saxpy which means they go unaffected by library mess with generic API-s names.

**Comment by rgommers** [comment]
@Pixie8888 if those explanations answered your question, can you close this issue?

**Comment by Pixie8888** [comment]
Sure. Thank You!

**Comment by brada4** [comment]
This issue is better placed downstream like pypi or some ML discussion. Here best we can tell omp and blas do not have same ABI in all cases ;-)
