### ISSUE TITLE
Support for Cortex M7

### ISSUE THREAD

**Issue by tblaha** [xianyi/OpenBLAS#4570]
Dear all, thanks for this awesome project!

I have an STM32H743 with a cortex M7 core of the armv7e-m architecture. I would like to crosscompile openblas and the included netlib clapack using `arm-none-eabi-gcc 10.3.1`. All my attempts so far have failed:
- https://github.com/OpenMathLib/OpenBLAS/wiki/How-to-use-OpenBLAS-on-Cortex-M gives me a host of `Error: attempt to use an ARM instruction on a Thumb-only processor -- `
- Based on issue #3351 I also used the Makefile build-system with the `Makefile.rule` listed at the bottom. I also changed added `--specs=nosys.specs -DOS_EMBEDDED -DEMBEDDED` to the `CCOMMON_OPT` to prevent linker issues with baremetal systems. This actually compiles a `libopenblas.a`, but of when I link this to my cortex M7 project this results in `conflicting architecture profiles A/M` linker errors
- When I replace the architecture flags in `Makefile.arm` to `-mfloat-abi=hard -mfpu=vfpv3 -mlibarch=armv7e-m -march=armv7e-m` to match my target architecture, then I get gcc complains that `target CPU does not support ARM mode`
- When I then replace `-marm` with `-mthumb` (and also `.arm` by `.thumb` in the `PROLOGUE` in `config_arm.h`) then the code doesn't assemble with, for instance, `amax_vfp.S:343: Error: thumb conditional instruction should be in IT block -- `vmovgt.f32 s0,s4'`. I don't know much about ARM assembly, so here is where my troubleshooting currently ends.

Does anyone know if it's just currently impossible to compile for my architecture, or is this some misconfiguration of the compiler? What would the possible steps be? Thanks in advance!

`Makefile.rule`
```
TARGET = ARMV7
CROSS = 1
export NOFORTRAN = 1
DYNAMIC_ARCH = 0
CC = arm-none-eabi-gcc
HOSTCC = gcc
BINARY=32
USE_THREAD = 0
USE_OPENMP = 0
NO_SHARED = 1
NO_CBLAS = 1
NO_LAPACK = 1
NO_LAPACKE = 1
BUILD_SINGLE = 1
BUILD_DOUBLE = 0
BUILD_COMPLEX = 0
BUILD_COMPLEX16 = 0
```

**Comment by martin-frbg** [comment]
Perhaps try with  `-march=armv7-a`  -- and the ARMV5 target as named in the wiki page uses only plain C kernels so should be less likely to have conflicting instruction set requirements than the assembly kernels for V6/V7 targets. But Cortex-M is probably one of the less common use cases

**Comment by martin-frbg** [comment]
Can you try 
```
make HOSTCC=gcc CC=/opt/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc NO_LAPACK=1 NOFORTRAN=1 TARGET=ARMV5 USE_THREAD=0
```
with the `CCOMMON_OPT += -marm` in Makefile.system commented out, and the COMMON_OPT line in Makefile.rule set to `-O2 -DOS_EMBEDDED=1 -fPIC --specs=nosys.specs -mcpu=cortex-m7 -mthumb` ? 
I suspect earlier versions of gcc may have been less strict about having `-marm` among the compile options for a thumb-only cpu.
 (The main effect of using TARGET=ARMV5 instead of ARMV7 is that it uses plain C kernels instead of the (inline) assembly ones - while this may have a small drawback in terms of performance, it circumvents the `instruction should be in IT block` errors that you noticed. From what I've read now, it might be possible to fix those by inserting `IT ge` before each invocation of the VMOVCOND macro in amax_vfp.S and similarly elsewhere but I do not have any (_experience with_) such embedded hardware to try if it works in practice)
