### ISSUE TITLE
Stack overflow with openblas 0.3.26 against LAPACK 3.11 test suite

### ISSUE THREAD

**Issue by h-vetinari** [xianyi/OpenBLAS#4574]
In conda-forge, we've been blocked for a long time from enabling newer LAPACK versions by default by failing tests in the LAPACK 3.10.1 test suite when run against MKL.

In the context of figuring out these errors, the Intel people asked me if it's possible to test against 3.11.0 as well, which I did in https://github.com/conda-forge/blas-feedstock/pull/114. Through this, I noticed that there are failures with openblas builds on windows (while linux/osx run fine):

```
98% tests passed, 2 tests failed out of 82

Total Test time (real) =  97.47 sec

The following tests FAILED:
	 25 - LAPACK-xeigtstd_dec_in (Failed)
	 54 - LAPACK-xeigtstz_zec_in (Failed)
```

<details>
<summary>more detailed logs</summary>

```
25/82 Test #25: LAPACK-xeigtstd_dec_in ...........***Failed    0.47 sec
Running: D:/bld/blas-split_1711250773222/work/build/bin/xeigtstd.exe
ARGS= OUTPUT_FILE;D:/bld/blas-split_1711250773222/work/build/TESTING/dec.out;ERROR_FILE;D:/bld/blas-split_1711250773222/work/build/TESTING/dec.out.err;INPUT_FILE;D:/bld/blas-split_1711250773222/work/TESTING/dec.in
Test OUTPUT:

Test ERROR:

CMake Error at D:/bld/blas-split_1711250773222/work/TESTING/runtest.cmake:36 (message):
  Test D:/bld/blas-split_1711250773222/work/build/bin/xeigtstd.exe returned
  Stack overflow

[...]

54/82 Test #54: LAPACK-xeigtstz_zec_in ...........***Failed    0.09 sec
Running: D:/bld/blas-split_1711250773222/work/build/bin/xeigtstz.exe
ARGS= OUTPUT_FILE;D:/bld/blas-split_1711250773222/work/build/TESTING/zec.out;ERROR_FILE;D:/bld/blas-split_1711250773222/work/build/TESTING/zec.out.err;INPUT_FILE;D:/bld/blas-split_1711250773222/work/TESTING/zec.in
Test OUTPUT:

Test ERROR:

CMake Error at D:/bld/blas-split_1711250773222/work/TESTING/runtest.cmake:36 (message):
  Test D:/bld/blas-split_1711250773222/work/build/bin/xeigtstz.exe returned
  Stack overflow
```

</details>

**Comment by martin-frbg** [comment]
Which compiler ? And can you work around it by supplying a larger /STACK: size to the linker ? https://github.com/Reference-LAPACK/lapack/issues/987 is somewhat related (though the stack requirements supposedly were fixed in the LAPACK testsuite 3 years ago, and the CLAPACK that issue was raised against is ancient). Possibly some new test with huge static arrays may have crept in again after LAPACK 3.10, but you should be seeing the exact same problem with Reference-LAPACK

**Comment by martin-frbg** [comment]
cf. https://github.com/Reference-LAPACK/lapack/pull/553

**Comment by martin-frbg** [comment]
more to the point, this should have been addressed by https://github.com/OpenMathLib/OpenBLAS/pull/4088 from 0.3.24 (copying https://github.com/Reference-LAPACK/lapack/pull/854)

**Comment by martin-frbg** [comment]
Of course the original Reference-LAPACK PR only made it into their 3.12.0 release, so if you are actually __mixing__ a NO_LAPACK=1 OpenBLAS with your own build of an unpatched 3.11.0 Reference-LAPACK , you will still get this and other since-resolved LAPACK errors. (But then you should probably be looking at the issue tracker for Reference-LAPACK anyway, instead of putting that here.)

**Comment by h-vetinari** [comment]
> But then you should probably be looking at the issue tracker for Reference-LAPACK anyway, instead of putting that here.

In my defense, all builds in https://github.com/conda-forge/blas-feedstock/pull/114 are running the same unpatched LAPACK test suite, and only openblas + windows showed this failure (MKL failed even earlier for unrelated reasons).

After backporting https://github.com/Reference-LAPACK/lapack/pull/854, things work now, thanks a lot! 🙏 

I'll make a point to double-check the lapack repo for related issues in the future.
