### ISSUE TITLE
BLAS tests still fail with larger N

### ISSUE THREAD

**Issue by loveshack** [xianyi/OpenBLAS#458]
#333 was closed but never fixed.  It still reports "suspect" with 0.2.11.

**Comment by loveshack** [comment]
This is fixed in 0.2.14 for zblat3 but the equivalent for dblat3 and sblat3 still reports a suspect result with n=100.

**Comment by loveshack** [comment]
Closed accidentally

**Comment by loveshack** [comment]
With version 0.2.16, DBLAT3 passes as well as ZBLAT3, though SBLAT3 still fails in those conditions (n=100 on sandybridge, single-threaded).

**Comment by martin-frbg** [comment]
Revisiting this as I was running tests in the context of fixing #601, single-threaded SANDYBRIDGE target (on Kaby Lake hardware) with current "develop": 
CBLAT3 passes even at N=265 (with what appears to be an isolated "suspect" result for CSYR2K at N=150), 
SBLAT3 and DBLAT3 likewise (with a suspect SSYR2K/DSYR2K at N=100 and N=150, again bracketing values like N=99,101 and N=149,151 pass)
ZBLAT3 test was run only up to N=205 due to memory constraints but behaves similar to CBLAT3 (mostly OK with seemingly isolated ZSYRK2 hickups at 150, and again at 200 - at the latter datum ZHER2K is flagged as suspect as well).

OK to close this, or should the intermittent "suspect" results for SYR2K be cause for concern ?

**Comment by loveshack** [comment]
I asked my former boss, on whose behalf I reported the issue.  He said
he'd have a look when he had time, but I haven't heard back yet; I'll
let you know when I do.  (I hadn't realized there had been an
improvement since I checked a version or two ago -- good!)
