### ISSUE TITLE
How to Accurately Measure cblas_sgemm Performance on Multiple CPU Cores?

### ISSUE THREAD

**Issue by solahn** [xianyi/OpenBLAS#4622]
Hi, I'm using the cblassgem() function of the OpenBLAS library.

I am performing openblassgem with 3 cpu cores using multi-CPU cores.

I want to measure the execution time of the openblastgem function accurately. (Or I want to make sure that all the threads assigned to openblastgem are shut down.)

Is there a function for synchronization like cudaDeviceSyncronize() in cuda?

**Comment by martin-frbg** [comment]
There is no such synchronization call, and idle threads will linger for a short time that is configurable when building the library (please see Makefile.rule). See the benchmark directory for some simple timing codes - it is usually necessary to average over a number of runs to remove jitter (probably caused by other system activity).
In case yiu find that thread distribution between your cpu nodes is not optimal, you can try experimenting with the OMP_PROC_BIND and OMP_PLACES environment variables (if using OpenMP), or use taskset
