### ISSUE TITLE
Very slow when having many small matrices and many threads

### ISSUE THREAD

**Issue by jeromerobert** [xianyi/OpenBLAS#478]
I'm using OpenBLAS 0.12 on Linux, built with  NO_AFFINITY=1 TARGET=SANDYBRIDGE.

My application is executing many blas call on many small matrices (smaller than 100x100). It's multi-threaded and each thread manage a large number of matrices. As matrices are independent I don't need any thread synchronization which make the application fast. It works well with reference BLAS and MKL but it is slow with OpenBLAS. On one thread OpenBLAS is much faster than reference BLAS but on 12 threads my speedup is 2 instead of 11 with the reference BLAS. 

Profiling shows that the problem is in blas_memory_alloc (the loop line 993) and blas_memory_free. blas_lock is probably the culprit. I tried with both USE_TREAD=0 and USE_THREAD=1 but it did not change anything.

My understanding is that blas_memory_alloc is design for multi-threading on few large matrices. So I tried to replace it with a simple wrapper to malloc/free like this 

    void *blas_memory_alloc(int procpos) {
        return malloc(BUFFER_SIZE);
    }

but it crash. It seems that I'm misunderstanding how blas_memory_alloc should really work.

Would it be possible to make blas_memory_alloc efficient in my use case ? Else can I get any guideline on writting a dedicated memory allocator ?

**Comment by xianyi** [comment]
@jeromerobert , I fixed a segfault bug with MAX_ALLOC_STACK on develop branch. Could you test the performance? Thank you.

**Comment by jeromerobert** [comment]
@xianyi I compare cdefdb2 with fb02cb0

DGEMV T is 25 time slower on 20x20 matrices on one thread. On 2 threads it's 200 time slower.

DGEMV N is of course not impacted.

**Comment by xianyi** [comment]
@jeromerobert , thank you. I will try to figure out how to allocate stack buffer for dgemv_t.

**Comment by jeromerobert** [comment]
@xianyi Now I can see the overflow at kernel/x86_64/dgemv_t.S:252 but I'm not skilled enough to guess the required buffer size to run this assembly code.

**Comment by xianyi** [comment]
@jeromerobert ,
You can read the C code https://github.com/xianyi/OpenBLAS/blob/develop/kernel/x86_64/dgemv_t_4.c .

The problem is that it uses the buffer for matrix x and y as following.

```
#define NBMAX 2048

xbuffer = buffer;
ytemp   = buffer + NBMAX;
```

**Comment by jeromerobert** [comment]
What a fool, I already fixed it for single precision:
https://github.com/xianyi/OpenBLAS/blob/master/kernel/x86_64/sgemv_t_4.c#L309

I guess that it just need to be adapted in [d,c,z]gemv_t_4.c. I'll test it tomorrow.

**Comment by jeromerobert** [comment]
@xianyi  #543 fix the bug for me on 62231ab so you probably just have to revert 9798481 and fd9fd42

**Comment by xianyi** [comment]
@jeromerobert , thank you for your patch. I will also try dgemv_t on other old machines.

**Comment by martin-frbg** [comment]
I see a significant slowdown in real-world code (elk.sourceforge.net, running "make test" with the included testcases) with the current codebase unless I either disable MAX_STACK_ALLOC or revert 9798481 as suggested above. "Significant" here means 10 percent of total execution time, making the current state of the develop branch of OpenBLAS actually slower than the netlib reference code.

**Comment by wernsaar** [comment]
Hi,

I ran some tests on elk. With MAX_STACK_ALLOC , a lot of tests are 
aborted with SIGSEGV and core dump.
Here are some numbers without the flag  MAX_STACK_ALLOC on my Bulldozer 
machine:

using Netlib:

real    4m49.582s
user    16m28.847s
sys    0m21.202s

using OpenBLAS, compiled for 8 threads:

real    5m22.954s
user    24m5.231s
sys    0m35.373s

using OpenBLAS, compiled for 1 thread:

real    4m20.537s
user    13m57.770s
sys    0m22.006s

Please provide more details, how you compiled OpenBLAS and elk

Best regards
Werner

**Comment by martin-frbg** [comment]
Thanks for testing. Strange, I did not encounter segfaults with current git develop (and 9798481 manually reverted) on Haswell - did see segfaults in gemm before Xianyi and Jerome started fixing the new MAX_STACK_ALLOC code of course). 
My Makefile.rule has USE_OPENMP=1 FCOMMON_OPT = -frecursive MAX_STACK_ALLOC=2048 set,
elk is built with  -O3 -ffast-math -funroll-loops -fopenmp -march=native in both F90_OPTS and F77_OPTS. gcc on this machine is 4.7.2 20130108 (opensuse default for 12.3), though I intend to test with more recent releases later. 
Normally the tests take around 227sec with OpenBLAS (quite constant since at least 0.2.12 despite all
recent code improvements), 212sec with the fallback blas+lapack included in the elk tarball, and 210sec
with the latest public snapshot of ATLAS (3.11.33). These numbers will most probably be different for
bigger problems (larger matrix sizes), but these would take days to run while I am concentrating on
quick-and-dirty tests between production runs. Unfortunately I will be away from this machine until next
weekend, though I may be able to arrange access to equivalent hardware if needed.

**Comment by jeromerobert** [comment]
As Elk is multi-threaded I compiled OpenBLAS with `USE_THREADS=0` and run both tests with `OMP_NUM_THREADS=12` :

OpenBLAS USE_THREADS=0:

    real	4m35.420s
    user	13m52.152s
    sys	0m14.712s

Elk embedded BLAS:

    real	4m44.414s
    user	14m41.732s
    sys	0m14.372s

I also get a segfault on test-001 with MAX_STACK_ALLOC=2048. I will investigate.

**Comment by xianyi** [comment]
@martin-frbg , thank you for the test. I have reverted 9798491.

I think we need to test more case to fix segfault.

**Comment by martin-frbg** [comment]
I was under the impression that I would have to set USE_OPENMP=1 as the elk application uses openmp - in the past I had also set USE_THREADS=0 as it seemed to make sense not to create subthreads, but the build process started complaining about this combination of build options recently. I did do a quick test with NUM_THREADS=1 after reading wernsaar's comment this morning but did not notice any improvement.

**Comment by xianyi** [comment]
@martin-frbg , The `USE_THREAD=0` is only for the sequential  library. If you set `USE_OPENMP=1`, OpenBLAS will use OpenMP instead of Pthread.

**Comment by martin-frbg** [comment]
Silly me, should have looked at what the define does instead of jumping to conclusions. With my misunderstanding out of the way, I am happy to report that OpenBLAS is indeed faster than netlib, as it should be. (No new comparison against ATLAS as I am traveling with an aging Nehalem laptop and will need to find a baking tin for use as a heat spreader a.k.a. HPC platform soon.) Did not see a segfault in test-001, valgrind did not find anything amiss there either (not that it was completely silent, but none of its warnings pointed to a problem in OpenBLAS)

**Comment by jeromerobert** [comment]
Indeed there is not crash with the Nehalem kernel. With the Sandybridge one I need to set stack_alloc_size to m+n+3 instead of m+n to make it work. Still no clues why.

**Comment by jeromerobert** [comment]
All x86_64 kernels but Nehalem and Atom are segfaulting with test-001.

**Comment by martin-frbg** [comment]
Found me an old abandoned Prescott that exhibited the segfaults, and your m+n+alignment fix indeed solved the problem. Guess there is no interest in non-performance figures for this old system...

**Comment by wernsaar** [comment]
Hi,

I ran further tests on ELK and found that the most important blas 
functions are
dgemm_ and dsymv_. I added optimized dsymv_ functions for haswell and 
sandybridge.

Best regards

Werner

**Comment by martin-frbg** [comment]
Great, thank you very much for that. (BTW just noticed that there appears to be an unrelated change for ARM in the Haswell patch, but you probably know that). 
Most important developments occuring due to an already closed issue :-)
Now while I am stirring up trouble already, may I suggest pulling in the fix from jeromerobert's ee71dd3 even if only as a temporary measure, given that MAX_STACK_ALLOC is currently the default on the develop branch, making that branch kind of broken-by-default on many systems ?

**Comment by wernsaar** [comment]
Hi,

I would be nice, if you can give me some elk.in files for medium sizes
( runtime > 300 seconds )

Best regards

Werner

**Comment by martin-frbg** [comment]
Certainly, though it would be easier for me when I do it next weekend when I am back at/near university.  I guess you already saw the "examples" subdirectory in the elk tarball ? At least the "Al" and "GaAs" cases should not take exceedingly long, cases Ru-ELF, AlAs-fatbands,Fe-fermisurface might be interesting as they execute additional code paths. Running them is as easy as running the tests, just cd to the directory containing the respective elk.in file and invoke elk there. 
If it is just longer runtime you are interested in to get better profiling data, you can also edit the elk.in files of the various "tests" to remove the "maxscl 1" that makes them bail out after just one iteration of what would be a longer ("self consistent field procedure") cycle.
