### ISSUE TITLE
交叉编译问题

### ISSUE THREAD

**Issue by anbof** [xianyi/OpenBLAS#4788]
交叉编译中出现Error: invalid operands (*UND* and *UND* sections) for `*‘

**Comment by martin-frbg** [comment]
Can you post more context please ? This error could mean that your compiler is too old, or you are using a 32bit compiler for 64bit (or 64bit compiler for 32bit), or that the cross-compile is trying to use the host assembler instead of the assembler from the cross-compiler toolchain

**Comment by anbof** [comment]
cmake \
--DCMAKE_CROSSCOMPILING=ON
-DCMAKE_SYSTEM_NAME="windows" \
-DCMAKE_SYSTEM_PROCESSOR="x86_64"\
-DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
-DCMAKE_Fortran_COMPILER=x86_64-w64-mingw32-gfortran\
-DUSE_THREAD=1 \
-DNUM_THREADS=64 \
-DUSE_OPENMP=1 \
-DTARGET=HASWELL \
-DDYNAMIC_ARCH=1 \  添加-DDYNAMIC_ARCH=1 编译出现Error : invalid operands (UND and ABS sections) for ’ 报错，不添加这个-DDYNAMIC_ARCH=1编译是成功的

**Comment by martin-frbg** [comment]
This is probably caused by AVX512 instructions in the codes for SkylakeX and Cooper Lake targets... Which version of the mingw gcc are you using ? (I do get a clean build with the mingw32-gcc version 10 that ships with Ubuntu 22.04LTS - and even with mingw32-gcc version 9 I "only" get an error "invalid register for .seh_savexmm" for some of the COOPERLAKE kernels in the default build.) Are you sure that you have the x86_64-w64-mingw32 package of binutils installed as well ?

**Comment by anbof** [comment]
是的，我安装的是x86_64-w64-mingw32 10版本

**Comment by martin-frbg** [comment]
I'm sorry, it turns out I was actually testing with the current `develop` branch instead of 0.3.27. The difference is almost certainly #4656

**Comment by anbof** [comment]
感谢您的帮助，用当前分支编译是成功编译的
