### ISSUE TITLE
invalid read from ddot_k on barcelona

### ISSUE THREAD

**Issue by juliantaylor** [xianyi/OpenBLAS#494]
below file creates an invalid read with valgrind on an athlon phenom 2 (barcelona)

```
==29878== Invalid read of size 16
==29878==    at 0x400EB9: ddot_k (dot_sse2.S:440)
==29878==    by 0x40077C: main (test.c:11)
==29878==  Address 0x51fc050 is 16 bytes inside a block of size 24 alloc'd
==29878==    at 0x4C2ABA0: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29878==    by 0x40070E: main (test.c:6)
```

``` c
#include <stdlib.h>
#include "cblas.h"

int main(int argc, char * argv[])
{
    double * a = malloc(3*8);
    a[0] = 1;
    a[1] = 2;
    a[2] = 3;
    double * b = &a[1];
    cblas_ddot(2, b, 1, a, 1);
}
```

the memory is overlapping which may be invalid input for dot, but on other cpu's (e.g. core2 or haswell) there is no valgrind error.

**Comment by xianyi** [comment]
@juliantaylor , I just gdb dot_sse2.S. I think this invalid read is by design. 

In your case, the start address of b is unaligned accessing for SSE2. Because OpenBLAS/GotoBLAS try to use aligned load instructions, it need to read one more double floating number, which causes the invalid reading in valgrind.
Although OpenBLAS reads one invalid element, it doesn't use the invalid data.

**Comment by juliantaylor** [comment]
but is this allowed?
so far I know you can read beyond allocation boundaries on a page basis on x86, does the code check for this? Otherwise it could trigger access violations.
