### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by RS-Gits** [xianyi/OpenBLAS#4995]
"interface"

**Comment by martin-frbg** [comment]
See the Makefile/CMakefile in "interface" please - sources in that folder are processed twice, once with CBLAS defined and once without, to generate the BLAS and CBLAS versions of the respective functions (which forward through the level2/level3 block matrix setup codes in "driver" to the machine-specific BLAS kernels under "kernel/architecture" - where files KERNEL.targetname define which BLAS kernel file is actually used for a specific target).

Also note that there is a pending fix for the "generic" GEMM3M implementation in PR #4976 - the underlying issue is that the C kernels in kernel/generic that several targets fall back to have never actually had a working GEMM3M implementation. In 0.3.28 I wanted to redirect callers to standard C/Z GEMM as a stopgap measure, but missed some differences in (non)implementation details.
