### ISSUE TITLE
OMP error with GCC 4.9.2

### ISSUE THREAD

**Issue by antinucleon** [xianyi/OpenBLAS#500]
Hello,
I think gcc 4.9.2 changes exception specifier of omp and lead to this error. But I am not very sure about this. I can compile OpenBLAS with gcc 4.9.2, but while compile other program using openblas, it showed this

```
/usr/local/lib/gcc/x86_64-redhat-linux/4.9.2/include/omp.h:75:37: error: declaration of ‘int omp_get_num_procs() throw ()’ has a different exception specifier
 extern int omp_get_num_procs (void) __GOMP_NOTHROW;
                                     ^
In file included from ./OpenBLAS/cblas.h:5:0,
                 from ./mshadow/mshadow/./base.h:98,
                 from ./mshadow/mshadow/tensor.h:14,
                 from src/updater/./sgd_updater-inl.hpp:8,
                 from src/updater/updater_impl-inl.hpp:8,
                 from src/updater/updater_impl.cpp:4:
./OpenBLAS/common.h:526:5: error: from previous declaration ‘int omp_get_num_procs()’
 int omp_get_num_procs(void) __attribute__ ((weak));
     ^
```

**Comment by martin-frbg** [comment]
The declaration of omp_get_num_procs in common.h is inside an #ifdef USE_OPENMP block, where the "__attribute__ ((weak))" variant form that appears to clash here is in the #else branch.
So you probably need to define USE_OPENMP in your own Makefile as well, if you include the OpenBLAS headers in your code.

**Comment by xianyi** [comment]
@antinucleon ，how do you compile OpenBLAS? `make USE_OPENMP=1`?

**Comment by xerus** [comment]
I am also affected by this. My projects uses GNU OpenMP Library and OpenBlas, so it includes:
#include <openblas/cblas.h>
#include <omp.h>

Why common.h does not include <omp.h> https://github.com/xianyi/OpenBLAS/blob/develop/common.h#L646 instead of declaring these OpenMP symbols?

It is included in https://github.com/xianyi/OpenBLAS/blob/develop/common_thread.h#L43 anyway...

**Comment by martin-frbg** [comment]
I suspect the problem lies elsewhere - the _installed_ cblas.h should never include the "private" common.h used at build time (what it includes instead is openblas_config.h with relevant build-time constants). So either you were including the cblas.h from the OpenBLAS source directory, or you used cmake to install an earlier version of OpenBLAS sometime in the past (the early attempts at cmakefiles simply grabbed all .h files from the build directory and dumped them in the target include path as none of the developers really understood cmake back then).

**Comment by xerus** [comment]
yeah, I used cmake. After cleaning up everything it is ok. Thanks!
