### ISSUE TITLE
Support for vfpv3-d16 on ARMV7

### ISSUE THREAD

**Issue by buffer51** [xianyi/OpenBLAS#662]
Hi,

I was wondering if OpenBLAS supported building for ARMv7 for Android with other FPU than NEON.
According to https://developer.android.com/ndk/guides/abis.html#v7a, NEON is optional which means that it could not be present on a device, which results in a crash or incorrect results.

They recommend building with `-mfpu=vfpv3-d16`. I tried to modify the flags in Makefile.arm, but that resulted in errors when building `dgemm_kernel`:
```Error: D register out of range for selected VFP version -- 'fmacd d8,d0,d16'```

Is there support for VFPv3-D16 or only for VFPv3-D32 and NEON?

Cheers,
Paul

**Comment by xianyi** [comment]
@buffer51 , The `D16` means there are only 16 fp registers. In ARMV7 assembly kernels, we uses 32 fp registers for `D32`. Therefore, you cannot compile the ARMV7 assembly kernels for `vfpv3-d16`.

I think you can try the pure C kernels.

**Comment by buffer51** [comment]
Oh right.. It would decrease performance a lot no?

What would be the appropriate flags for it?

**Comment by xianyi** [comment]
@buffer51 , the C kernels' performance is not good.

The ARMV5 target uses pure C kernels.

1) Edit `Makefile.arm`

From
```
ifeq ($(CORE), ARMV5)
CCOMMON_OPT += -marm -march=armv5
FCOMMON_OPT += -marm -march=armv5
endif
```

To, e.g.

```
ifeq ($(CORE), ARMV5)
CCOMMON_OPT += -marm -march=armv7-a -mfpu=vfpv3-d16  (-mfloat-abi=hard or softfp)
FCOMMON_OPT += -marm -march=armv7-a -mfpu=vfpv3-d16  (-mfloat-abi=hard or softfp)
endif
```
2) `make TARGET=ARMV5`

**Comment by mhsmith** [comment]
Isn't it also possible to use `TARGET=ARMV6`, as was recommended in https://github.com/xianyi/OpenBLAS/issues/388?

**Comment by martin-frbg** [comment]
Certainly looks like it should be possible (and probably the preferred solution, as it would use optimized assembly kernels rather than the C fallback), could you try ?

**Comment by mhsmith** [comment]
I've tried an ARMv6 build on an ARMv7 Android device, and of course it works. I don't have access to a device which has ARMv7 but lacks VFPv3-D32: it seems that in practice, those devices were rare even [as long ago as 2013](https://stackoverflow.com/a/9406914/). 

NEON has been [compulsory since Android 6.0](https://source.android.com/compatibility/cdd), which was released in 2015, and according to the Android documentation, [NEON implies VFPv3-D32](https://developer.android.com/ndk/guides/cpu-arm-neon.html).
