### ISSUE TITLE
OpenBlas with static link to mingw

### ISSUE THREAD

**Issue by slegall56** [xianyi/OpenBLAS#779]
Hi, 
I compiled OpenBlas 0.2.15 with msys + mingw in x86 on windows. Everything worked well.
But my lib "libopenblas.dll" depends on other dll such as libgcc_s_dw2-1.dll and also msvcrt.dll. 
Is it possible to link to these libraries in static instead of dynamic in order to get "libopenblas.dll" independant to other dll.
Seb

**Comment by martin-frbg** [comment]
You should be able to get rid of the libgcc_s dependency by specifying -static-libgcc among the linker flags. Statically linking against msvcrt appears to be not officially supported due to licensing issues, but there are some instructions on the 'net for patching and rebuilding mingw to work around this, e.g. http://anselm-kruis.de/cgi-bin/weblog_basic/index.php?p=4 (which I have not tried)
In practice, given that an msvcrt.dll should be present on every windows installation I suspect the external dependency on this microsoft c runtime library is only going to cause problems if you try to link a VS-built project against the mingw-built openblas dll.

**Comment by brada4** [comment]
But how it is OpenBLAS's problem that it uses CRT (C runtime) and mingw uses only possible option on Windows - Microsoft's DLL?
Also on msdn you can find authoritative options that (1) you cannot trust that msvcrt dll in windows is as good as redist, i.e you must always redist before use (2) while there is official doc on how to link msvcrt inside your executable it comes with strong warnings that such DLL will not work if it is imported alongside different MCVCRT to some module (3) also appcompat depends on runtime imports, like W10 still has W95-old MSVCRT shim libs (i.e ones that remap calls to newer version)

**Comment by slegall56** [comment]
Ok I understand. Thank you guys

**Comment by slegall56** [comment]
I'm just new in msys and mingw but how do I specify -static-libgcc among the linker flags to get rid of libgcc_s_dw2-1.dll. 
Currently, I just open msys console and type "make" and it generates my libopenblas.dll and libopenblas.dll.a. I just don't know where to specify -static-libgcc. Is it an argument of make or do I have to modify the makefile ? If yes where is it ?

**Comment by martin-frbg** [comment]
You could try invoking make as
make LDFLAGS='-static-libgcc'

**Comment by slegall56** [comment]
if I do that, after 5 min of compilation I get this : 
gcc.exe : error: static-libgcc: No such file or directory

**Comment by slegall56** [comment]
Stupid I am , I wrote static-libgcc instead of -static-libgcc

**Comment by slegall56** [comment]
Thank you martin it works. I can close it for good
