### ISSUE TITLE
Reduce optimized kernels in DYNAMIC_ARCH mode

### ISSUE THREAD

**Issue by xianyi** [xianyi/OpenBLAS#791]
So far, OpenBLAS/GotoBLAS compiled many optimized kernels for old x86/x86_64 architectures. It causes a big binary and lots of maintain works. I plan to remove old optimized kernels for old architectures.

I plan to only compile the following kernels in DYNAMIC_ARCH mode.

Generic (C codes)
Intel: Core2, Nehalem, Sandy Bridge, Haswell
AMD: Barcelona, Bulldozer, Piledriver, Steamroller

Any suggestions?

**Comment by carlkl** [comment]
+1, but I propose to add PRESCOTT and NORTHWOOD (win32) to support older CPUs.

**Comment by jeromerobert** [comment]
For me it does not matter. I only use the architecture you plan to keep but I also find OpenBLAS binaries small enough (so smaller than MKL).

**Comment by brada4** [comment]
It is well on the topic:
https://gcc.gnu.org/svn/gcc/trunk/gcc/config/i386/x86-tune.def
@jeromerobert MKL libblas.so is ~50MB

x86 does not look like growing.  What about leaving it as it is and divorce cpuid so that Nehalem (or Core2?) is the architecture also for future CPUs(and kernels retired if they are found defective)? Say geode (mmx+3dnow) is still being sold...

x86_64 Is Avoton handled by Core2?

**Comment by carlkl** [comment]
One big advantages of OpenBLAS is the dynamic runtime selection of kernels over a wide range of CPU architectures. Many OSS projects recentlly don't support non-SSE2 CPU's anymore, so OpenBLAs could do the same: that is removing three targets for x86.

Also some targets could be possibly removed due to negligible differences to others. Supporting SSE2 or SSE3 only CPUs with at least some optimized assembler BLAS routines is desirable IMHO.

**Comment by xianyi** [comment]
To improve the stability, I need to setup buildbot to test every supported kernels. To remove some old kernels, we can have a lower maintain cost. 

Meanwhile, I cannot find a machine to run some old AMD kernels with 3dnow instructions.

**Comment by brada4** [comment]
Then it must go for certain.... It is like 5 years since last was made.

**Comment by cparrott73** [comment]
I concur with carlkl's comment above - would like to see PRESCOTT support retained, at least, as an optimized fallback for older CPUs.  I am also perfectly fine with dropping CORE and NEHALEM, though others might feel differently.

**Comment by ogrisel** [comment]
+1 for including at least one optimised fallback architecture that is guaranteed to work on any old  CPU that has SSE2/3 or more. To me it seems that PRESCOTT can do that. I am not sure about NORTHWOOD.

**Comment by Diazonium** [comment]
I would hate to see NEHALEM support gone, we have access to a fairly large cluster based on Nehalem cpus.
We also have a few core2 boxes we still use. No Prescott boxes though, even if we had, they are too slow to do anything useful at this point.

**Comment by martin-frbg** [comment]
Adressed in #1607, further changes can be discussed in #1607 I think.
