### ISSUE TITLE
What is the best configuration for DYNAMIC_ARCH for x86 and x86-64?

### ISSUE THREAD

**Issue by carlkl** [xianyi/OpenBLAS#793]
This is an addon to [Reduce optimized kernels in DYNAMIC_ARCH mode](https://github.com/xianyi/OpenBLAS/issues/791). 
The objective of `DYNAMIC_ARCH` is to build the OpenBLAS library in a `generic` mode with moderate optimization for a wide range of possible architectures.
OpenBLAS contains a lot of options for building in `Makefile.rule`. Some options for a *generic* optimization for the Intel/AMD architectures are obvious:

- using `gcc -O2 -march=x86-64 -mtune=generic` for x86-64
- using `gcc -O2 -mtune=generic` for x86

with SSE2-only CPU's in mind this could changed to:

- using `gcc -O2 -march=pentium4 -mtune=generic -mfpmath=sse -msse2` for x86

One question is about the maximum number of threads to be given for the build configuration, i.e.:

- `NUM_THREADS=16` for x-86-64
- `NUM_THREADS=64` for x86

Another question is if `MAX_STACK_ALLOC=2048` is still the best bet given the latest changes in trunk.

The last question is about the stacksize, that *could* be configured during linking: i.e.:

`-Wl,--stack,16777216` 

OpenBLAS uses the standard stacksize given by binutils right now.

**Comment by brada4** [comment]
You can run
( . $CONFIG_SITE ; make )
on most linuxes, that is very likely to set tuna=generic and other flags used for most distribution packages.

Adding too much gcc flags hurts OSX users (or debian enthusiasts for that sake) with clang.

Why do you want to desupport my 18-core haswell? It is 2 of them in the server and they have hyperthreading enabled.

**Comment by carlkl** [comment]
@brada4, my impression is, that an optimal set of configurations depends on the OS and of course on the needs of the user. 

My question targets on an advice for a building this library as generic as possible and to describe that at the Wiki pages of this repository.

**Comment by jeromerobert** [comment]
The maximum  `MAX_STACK_ALLOC`  value depends on the application and the operative system. Most of application does not extensively use the stack so a value of 4194304 (4MiB) should work. I just chose 2048 to be very conservative. A too high value will trigger a stack overflow.

Starting with some value `MAX_STACK_ALLOC` will not improve performance because the computation time will hide the `blas_memory_alloc` time. I agree that is would be nice to know this value. I tend to use 4096 but may be it's bit more. It should not be very hardware nor OS dependent.

The default value of `NUM_THREADS` is the number of logical cores (physical cores would be better ?) of the building system (for x86 archs at least). A downside of increasing it is that OpenBLAS allocate more memory. When making portable OpenBLAS build I use `NUM_THREADS=24` because I know my clients do not have chips with more than 24 cores. Anyway I think it's acceptable for people who have uncommon and expensive hardware to rebuild OpenBLAS. The default `NUM_THREADS` value should be for mere mortal that is IMHO not more than 24.

MKL with a decent set of kernels is close to 200MiB.

**Comment by xianyi** [comment]
@carlkl , I don't think the `gcc -O2 -march=pentium4 -mtune=generic -mfpmath=sse -msse2` flag can get significant performance benefit compared to the default setting.

@jeromerobert , I want to change `NUM_THREADS` flags. For example, use `malloc` to alloc the array on runtime instead of  `array[NUM_THREADS]`.

**Comment by carlkl** [comment]
@jeromerobert, thanks for this, as this is very useful. 
@wernsaar, some more comments about that, especially for the Windows platform?
@xianyi, I think the default flags will be ok. `-march=pentium4 -mtune=generic` is typically recommended for x86 generic usage with at least SSE2 support. With `-mfpmath=sse -msse2` I suppressed the *minor* precision errors for the OpenBLAS tests on Windows.

**Comment by brada4** [comment]
@carlkl do you have any proof that -O2 is very bad?

**Comment by carlkl** [comment]
I can't remember ever having made such a statment.

**Comment by brada4** [comment]
To ensure compatibility we should not change -march of default compiler. Which for gcc on x86 usually boils down to -march=i686 (no MMX, aiias -march=pentiumpro -mtune=generic)
Anything else just leaves compatibility behind.

**Comment by carlkl** [comment]
I will stick to the recommendations of https://github.com/xianyi/OpenBLAS/issues/793#issuecomment-192937963 for my work and will close this issue.
