### ISSUE TITLE
Optimize OpenBLAS for LinuxOne s390x zEC13 SIMD: BLAS 1/2 double precision

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#884]

**Comment by ashu-22** [comment]
It does not work out well.Please, someone, provide me some assistance for it

**Comment by martin-frbg** [comment]
Can you clarify what it is you want help for ? From your github account it does not exactly look like you are working on optimizing code for powerful IBM mainframe systems

**Comment by ashu-22** [comment]
But I want to work on that thing!

**Comment by quickwritereader** [comment]
Hi guys. Actually, this issue is almost complete. But I should still consult Xianyi  about this work to see if it suits needs. After consulting Xianyi probably I will pull request or maybe still try to do needed things. Recently, I'm resting. I am going to start to work on Openblas in September for IBM z-series.
For blas 1/2 double you could use my forked version

**Comment by quickwritereader** [comment]
Hi guys. My pr targeted this issue. But It is still open. I consulted Xianyi before PR.

**Comment by martin-frbg** [comment]
@quickwritereader Please advise if you would like me to close it ? Thanks for all your work BTW, I had left your PR open for a few days before merging it only because I am not qualified to judge zarch assembly myself.
PS: technically this is David Edelsohn's call I think (and I notice your PR specifically excluded nrm2 from his requirements)

**Comment by ashu-22** [comment]
I do not know about that system very much.So, I could not tell you about
the various imp configurations.

**Comment by quickwritereader** [comment]
@martin-frbg 
Yes you are right Its better to wait for them @xianyi  @edelsohn , though I consulted Xianyi and informed about it to Edelsohn.   

nrm2 c implementation had overflow technique  Afaik on these functions presicion and correctness matter more than performance.  And as it was also memory bound function I was reluctant to simd it for the sake of applying simd and losing performance. Otherwise without overflow tecnique It could be done just by modifing dot product. 
If it will matter I try to look again how I could simd that base c implementation.  
 Or I just can do without overflow and users could use this for more correctness: 
find alpha=max (x)
Scale x1= (1/alpha)*x
then nrm2 (x)=blas_nrm2(x1) *alpha

**Comment by edelsohn** [comment]
Is everything merged? I believe that we're only waiting for @xianyi

**Comment by quickwritereader** [comment]
Yes my latest works were merged [pr 1288](https://github.com/xianyi/OpenBLAS/pull/1288)
I hope these suit initial needs. I think after ibmcloud simd fix we will see if works suit devs need ,too
