### ISSUE TITLE
c/zgemv bugs with inputs containing NaN

### ISSUE THREAD

**Issue by xianyi** [xianyi/OpenBLAS#929]
@andreasnoack reported this bug on Power8.

**Comment by andreasnoack** [comment]
I used the following program
```fortran
program test

    real*8 :: z
    complex*16 :: a(5,5), x(5), y(5)

    write(*,*) 'enter 0.0'
    read(*,*) z

    a(:,:) = 0.0d0
    x(:) = 0.0d0
    y(:) = (0.0d0, 0.0d0)/z

    write(*,*) 'this value should be nan', y(1)

    call zgemv('N', 5, 5, (1.0d0, 0.0d0), a, 5, x, 1, (0.0d0, 0.0d0), y, 1)

    write(*,*) '...but now it should be zero', y(1)

end program
```

**Comment by brada4** [comment]
Case A: NaN is a poison we return NaN
Case B:
On entry, BETA specifies the scalar beta. When BETA is supplied as zero then Y need not be set on input. Still NaN
Case C: we use -O99 compiler flag and coerce NaN to zero
Case D: Our compiler inlines 1000 calls deep and mistakes x/0*0 for a zero when symbolic result is undetermined.

Which is the proper NaN propagation?

**Comment by martin-frbg** [comment]
Formally the behaviour may be undefined, as the documentation only has "... y need not be set" instead of "y is ignored", but it is quite a different case from supplying NaN as an active variable to a computation. Also I suspect it "just works" in stock netlib on that platform, and in openblas on other platforms that use different assembly routines. I'd hazard a guess that this is just another case where a register is zeroed using an instruction that fails for NaNs (cf. #740), but it would probably be not too expensive to just zero Y unconditionally on entry when BETA is zero either (?)

**Comment by xianyi** [comment]
@andreasnoack , I clear the vector when BETA=0.

**Comment by andreasnoack** [comment]
Thanks. I'll try to rebuild the development branch

**Comment by andreasnoack** [comment]
Thanks. It works. Next from Julia's test suite is https://github.com/xianyi/OpenBLAS/issues/946 😃
