### ISSUE TITLE
Update LAPACKE to latest master

### ISSUE THREAD

**Issue by vladimir-ch** [xianyi/OpenBLAS#971]
Would it be possible to update (at least) lapack-netlib/LAPACKE to the latest master? It contains a fix for the bug https://github.com/Reference-LAPACK/lapack/issues/59 that is causing failures in our tests https://github.com/gonum/lapack/pull/143.

**Comment by martin-frbg** [comment]
Probably quicker to do a pull request with just the fix for lapack#59. (As far as I know, OpenBLAS tends to synchronize to major releases of LAPACK and just cherry-pick patches in between. At least in the past when the "netlib" LAPACK was not yet on github and there was only their user forum to go to, lapack bugs were sometimes fixed here first.)
