### ISSUE TITLE
OpenBlas crash when running with Caffe visualstudio 2010

### ISSUE THREAD

**Issue by thuanvh** [xianyi/OpenBLAS#976]
Hello,
I have got a crash message when run OpenBlas with Caffe in the function cblas_sgemm.
Exception that I got is: "0xC0000005: Access violation reading location 0x0000004b."
I build OpenBlas 0.2.19 on Mingw32 (DYNAMIC_ARC=1 BINARY=32) and Caffe build in visual studio 2010.
One interesting thing that there is no error if Caffe is built in visual studio 2015.
I must use visual studio 2010 for Windows XP sp3. I tried both with Visual Studio 2015 for XP, but it is also failed with the same message.

Thank you,
Thuan

**Comment by martin-frbg** [comment]
Which CPU (so that people know which implementation of sgemm to look at) ? And can you produce a
minimal example that shows the problem - the exception as such only tells that some function probably tried to access element no. 75 (4b in hexadecimal numbers) of some array that is smaller than that. At that point it is not really clear if the error is in OpenBLAS, caffe (or the compiler that built these two codes) or in the data you throw at it. If it works when caffe is built with a newer compiler, perhaps VS2010 just miscompiles the caffe code or current mingw uses an API model that is incompatible with old releases of VS ?

**Comment by thuanvh** [comment]
Thank @martin-frbg 
I have just figured out that I used VS2015 (on Windows 10) to build for VS2010. Then I switched to build caffe on VS2010 in Windows XP. 
Now, there is no exception thrown.
Thank you.

**Comment by martin-frbg** [comment]
Glad to know you got it sorted. Could you please close this issue then ?
